### ISSUE TITLE
Can I emulate two processes in the same emulation context?

### ISSUE THREAD

**Issue by jt0dd** [qilingframework/qiling#1007]
Basically, when my emulated process makes a system or API call, I want to trace the instructions executed by the OS / kernel to fulfill it.

Can that be done with this framework? I don't fully understand how unicorn / qemu are structured under the hood, so it's hard to think of how to do it without seeing some example or documented feature. I'm imagining it would be something like, for example, replacing the `ntQuerySystemInfo_x86` windows API call with your own handler, which then emulates that like this example:

https://github.com/qilingframework/qiling/blob/master/examples/ntQuerySystemInfo_x86.py

but then it would be a separate, isolated emulation. Something like this is what I'm imagining:

```
def dissassem(ql, address, size):
    buf = ql.mem.read(address, size)
    for i in md.disasm(buf, address):
        print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))

def my_NtQuerySystemInformation(ql, address, params):
    sub_proc = ql.run(["rootfs/x86_windows/bin/NtQuerySystemInformation.exe"])
    sub_proc.hook_code(dissassem)
    # return outcome of the system call or API call process

ql = Qiling("rootfs/x86_windows", libcache=True)
main_proc = ql.run(["my_program.exe"])
main_proc.hook_code(dissassem)
// and whatever the code would be to hook our handler to that NtQuerySystemInformation Windows API call
```

Can the framework currently do something like this?

**Comment by jt0dd** [comment]
If this isn't possible, I want to help add it. I just need to know if it can be done and some guidance. In addition to this, I want to help add support for the API and system calls the docs mention aren't supported yet.

**Comment by jt0dd** [comment]
So looking into the source, I'm starting to understand a bit more about how the emulation is running, it's different than I was imagining. I was thinking the full kernel / OS was being emulated to some extent, but it seems really only the binaries relevant to the executed process are being emulated... Are instruction traces like this already showing the instructions executed by any Windows API calls? 
```
def dissassem(ql, address, size):
    buf = ql.mem.read(address, size)
    for i in md.disasm(buf, address):
        print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```

**Comment by xwings** [comment]
if you need a full disasm output, verbose will help. please refer to

https://docs.qiling.io/en/latest/print/#verbose

**Comment by kabeor** [comment]
@jt0dd Hi, maybe I'm misunderstand, do you mean can Qiling run real native syscall? If you mean that, answer is no, Qiling will output syscall name and hook them to Qiling syscall implementation.

**Comment by jt0dd** [comment]
@kabeor As brilliant and powerful as this tool is, when I think about what we can do with this, considering the fact that we cannot possibly ever achieve a 1:1 emulation equivalence to bare metal... well, emulation will always be very susceptible to evasion. The attacker will always be able to know "I'm in Qemu, I'm in Unicorn, I'm in Qiling" and this poses a significant limitation for our ability to use the tool for accurate analysis. Would it be possible to use some kind of black-box analysis against the OS / CPU to get nearly 1:1 hardware / software behavior emulation of a target environment? So let's say we know the attacker is targeting a very specific endpoint, we then "snapshot" / analyze that endpoint to dynamically generate a 1:1 emulation and analyze the true behavior of the threat against that specific endpoint configuration the attacker is targeting. Is such an emulation system plausible?

**Comment by kabeor** [comment]
@jt0dd Well, in my opinion, Unicorn just emulates CPU instructions and Qiling provides a environment to emulate OS layer stuff like syscall, IO, etc... So in theory, a software doesn't know it's running in Qiling(Give me an example if I'm wrong, thx). But you are right, it can call on features not supported by Qiling. But, plz note that _**Qiling is a framework not a tool**_. It can adapt any software's needs through custom code. We can always provide an environment where conditions are met. Besides, `perfect 1:1 behavior equivalence` must be a huge project, Qiling needs implement all the details of all supported operating systems, this is tantamount to reimplementing the operating system. I guess I don't have a good solution to this now.

If you have any ideas, please feel free to share them.

**Comment by jt0dd** [comment]
@kabeor "So in theory, a software doesn't know it's running in Qiling(Give me an example if I'm wrong, thx)", There exists a lot of hidden undocumented functionality in CPUs which emulation developers (who engineer their frameworks based on the documentation) cannot hope to replicate, especially since the behavior varies between processors. This means that through black-box analysis, the attacker can, without much manual effort, find discrepancies between how the CPU should work (which is usually how emulators behave) and how it really works, and by executing certain instructions that expose discrepancies they can identify emulation, and even specific emulators. Domas [demonstrated this](https://youtu.be/ajccZ7LdvoQ?t=1733) capability at DEFCON 2017. Beyond this specific technique, there are others, for example, Blackthorne et al showed us this with their AVLeak tool which you can [read about](https://www.usenix.org/system/files/conference/woot16/woot16-paper-blackthorne.pdf) or watch the video presentation: [AVLeak: Fingerprinting Antivirus Emulators for Advanced Malware Evasion](https://www.youtube.com/watch?v=a6yOwvFds78). 

"We can always provide an environment where conditions are met." I would argue that perhaps this isn't the case, or rather we can, but only on a case by case basis. Any automated threat detection which might leverage our emulation frameworks seem to suffer from this problem. The problem is **uncertainty**. It's demonstrated in the Domas research above and broken down in [this diagram](https://www.reddit.com/r/cybersecurity/comments/qopemf/i_attempted_to_diagram_everything_ive_learned/) I had peer reviewed on Reddit to explain the concept visually. This uncertainty means there are undocumented behaviors in our environment that we can never know about (all of them) but the attacker can always find (one of them) through black box analysis, even if the emulation engineer carefully attempts to remove any static fingerprints of the emulator.

"[...] this is tantamount to reimplementing the operating system. I guess I don't have a good solution to this now. [...] If you have any ideas, please feel free to share them."

Yes and that's clearly not a viable approach. I can't say I have a great solution yet, you guys' understanding of the kernel is far beyond my own especially with the Demigod addition to the code by Nguyen et al, that was some amazing stuff. But I have been thinking about it, because low level emulation really is vital for peering ahead into a program's behavior for just-in-time endpoint threat detection once a hook is triggered. It's an important problem to solve, since the kernels seem to be massive fuzzballs of components built on top of each other over generations of developers and no one really knows about how every piece works. It's too much work for any open source development community to mirror these systems 1:1 in emulation.

I thought of one approach but it won't really work. We could focus instead on an approach to analyzing the hardware circuits of every component, every bus, every controller, the CPU, RAM, all the hardware connected to a specific system. If we could dynamically analyze and emulate those _hardware_ circuits accurately, we could just take all the firmware and kernel and OS and libraries the entire software state of the system directly from the system and just run it. Then we would theoretically, if we had emulated the hardware correctly, get a 1:1 emulation of the computing system without doing any manual development to replicate the OS, kernel, drivers, etc, we could just run all of that from an image. But the timing would be a discrepancy, the attacker would detect it, and we're back where we started. So that won't work.

Well, why do we even care about emulation in the first place? We want to see what some instructions will do, before they're done. And we want to see what's going on in the registers maybe, without running a debugger (which the attacker can also detect). Maybe we can solve those things through sandboxing and bare metal processing and some new CPU capabilities for secretly gathering those register states for analysis without the attacker being the wiser. Debuggers can't do this secretly. Emulation can, and it's the only tool we have for this right now, so we work with what we have, even if the result is vulnerable to evasion.

**Comment by kabeor** [comment]
@jt0dd thx for your examples, learned a lot from there! Have to say, T think there is no 100% perfect emulation. Even if there is, malware still can find different ways. The only thing that can do as well as the real machine is machine.
