### ISSUE TITLE
I am trying to fuzz linux_x8664

### ISSUE THREAD

**Issue by KA2010** [qilingframework/qiling#1032]
**I am trying to fuzz linux_x8664, it was working fine but after I download unicorn2 & unicornafl2 it gave me this error, How might i solve it?**
/qiling/examples/fuzzing/linux_x8664$ AFL_DEBUG=1 ./fuzz.sh
./fuzz.sh: 3: [[: not found
[+] Loaded environment variable AFL_DEBUG with value 1
[+] Loaded environment variable AFL_PATH with value /home/kawkab/qiling/examples/fuzzing/linux_x8664/AFLplusplus
[+] Loaded environment variable AFL_AUTORESUME with value 1
[+] Loaded environment variable AFL_DEBUG with value 1
afl-fuzz++3.15a based on afl by Michal Zalewski and a large online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eißfeldt, Andrea Fioraldi and Dominik Maier
[+] afl++ is open source, get it at https://github.com/AFLplusplus/AFLplusplus
[+] NOTE: This is v3.x which changes defaults and behaviours - see README.md
[+] No -M/-S set, autoconfiguring for "-S default"
[*] Getting to work...
[+] Using exponential power schedule (FAST)
[+] Enabled testcache with 50 MB
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[+] You have 48 CPU cores and 2 runnable tasks (utilization: 4%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.md.
[*] Setting up output directories...
[+] Detected prior run with AFL_AUTORESUME set. Resuming.
[+] Output directory exists, will attempt session resume.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Checking CPU core loadout...
[+] Found a free CPU core, try binding to #0.
[*] Scanning 'afl_outputs/default/_resume'...
[+] Loaded a total of 9 seeds.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] No auto-generated dictionary tokens to reuse.
[*] Attempting dry run with 'id:000000,time:0,orig:id:000008,src:000000,time:4881,op:havoc,rep:8'...
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] Extended forkserver functions received (81000001).
[*] Using SHARED MEMORY FUZZING feature.
[D] DEBUG: calibration stage 1/8
[D] DEBUG: calibration stage 2/8
[D] DEBUG: calibration stage 3/8
[D] DEBUG: calibration stage 4/8
[D] DEBUG: calibration stage 5/8
[D] DEBUG: calibration stage 6/8
[D] DEBUG: calibration stage 7/8
[D] DEBUG: calibration stage 8/8
    len = 3, map size = 580, exec speed = 4711 us
[*] Attempting dry run with 'id:000001,time:0,orig:id:000007,src:000000,time:2413,op:havoc,rep:8'...
[D] DEBUG: calibration stage 1/8
[D] DEBUG: calibration stage 2/8
[D] DEBUG: calibration stage 3/8
[D] DEBUG: calibration stage 4/8
[D] DEBUG: calibration stage 5/8
[D] DEBUG: calibration stage 6/8
[D] DEBUG: calibration stage 7/8
[D] DEBUG: calibration stage 8/8
    len = 12, map size = 589, exec speed = 3302 us
[*] Attempting dry run with 'id:000002,time:0,orig:id:000006,src:000000,time:2126,op:havoc,rep:8,+cov'...
[D] DEBUG: calibration stage 1/8
[D] DEBUG: calibration stage 2/8
[D] DEBUG: calibration stage 3/8
[D] DEBUG: calibration stage 4/8
[D] DEBUG: calibration stage 5/8
[D] DEBUG: calibration stage 6/8
[D] DEBUG: calibration stage 7/8
[D] DEBUG: calibration stage 8/8
    len = 12, map size = 588, exec speed = 3283 us
[*] Attempting dry run with 'id:000003,time:0,orig:id:000005,src:000000,time:1380,op:havoc,rep:2'...
[D] DEBUG: calibration stage 1/8
[D] DEBUG: calibration stage 2/8
[D] DEBUG: calibration stage 3/8
[D] DEBUG: calibration stage 4/8
[D] DEBUG: calibration stage 5/8
[D] DEBUG: calibration stage 6/8
[D] DEBUG: calibration stage 7/8
[D] DEBUG: calibration stage 8/8
    len = 4, map size = 588, exec speed = 3309 us
[*] Attempting dry run with 'id:000004,src:000000,time:604,op:havoc,rep:8,+cov'...
[D] DEBUG: calibration stage 1/8
[D] DEBUG: calibration stage 2/8
[D] DEBUG: calibration stage 3/8
[D] DEBUG: calibration stage 4/8
[D] DEBUG: calibration stage 5/8
[D] DEBUG: calibration stage 6/8
[D] DEBUG: calibration stage 7/8
[D] DEBUG: calibration stage 8/8
    len = 16, map size = 589, exec speed = 3237 us
[*] Attempting dry run with 'id:000005,time:0,orig:id:000003,src:000000,time:458,op:havoc,rep:2,+cov'...
[D] DEBUG: calibration stage 1/8
[D] DEBUG: calibration stage 2/8
[D] DEBUG: calibration stage 3/8
[D] DEBUG: calibration stage 4/8
[D] DEBUG: calibration stage 5/8
[D] DEBUG: calibration stage 6/8
[D] DEBUG: calibration stage 7/8
[D] DEBUG: calibration stage 8/8
    len = 2, map size = 588, exec speed = 3249 us
[*] Attempting dry run with 'id:000006,time:0,orig:id:000002,src:000000,time:49,op:havoc,rep:16,+cov'...
[D] DEBUG: calibration stage 1/8
[D] DEBUG: calibration stage 2/8
[D] DEBUG: calibration stage 3/8
[D] DEBUG: calibration stage 4/8
[D] DEBUG: calibration stage 5/8
[D] DEBUG: calibration stage 6/8
[D] DEBUG: calibration stage 7/8
[D] DEBUG: calibration stage 8/8
    len = 4, map size = 586, exec speed = 3276 us
[*] Attempting dry run with 'id:000007,time:0,orig:id:000001,src:000000,time:10,op:havoc,rep:4,+cov'...
[D] DEBUG: calibration stage 1/8
[D] DEBUG: calibration stage 2/8
[D] DEBUG: calibration stage 3/8
[D] DEBUG: calibration stage 4/8
[D] DEBUG: calibration stage 5/8
[D] DEBUG: calibration stage 6/8
[D] DEBUG: calibration stage 7/8
[D] DEBUG: calibration stage 8/8
    len = 1, map size = 577, exec speed = 3135 us
[!] WARNING: No new instrumentation output, test case may be useless.
[*] Attempting dry run with 'id:000008,time:0,orig:a'...
[D] DEBUG: calibration stage 1/8
[D] DEBUG: calibration stage 2/8
[D] DEBUG: calibration stage 3/8
[D] DEBUG: calibration stage 4/8
[D] DEBUG: calibration stage 5/8
[D] DEBUG: calibration stage 6/8
[D] DEBUG: calibration stage 7/8
[D] DEBUG: calibration stage 8/8
    len = 1, map size = 586, exec speed = 3239 us
[+] All test cases processed.
[+] Here are some useful stats:

    Test case count : 4 favored, 0 variable, 0 ignored, 9 total
       Bitmap range : 577 to 589 bits (average: 585.67 bits)
        Exec timing : 3135 to 4711 us (average: 3415 us)

[*] No -t option specified, so I'll use an exec timeout of 20 ms.
[+] All set and ready to roll!
**Segmentation fault**
kawkab@cysecuga:~/qiling/examples/fuzzing/linux_x8664$ Traceback (most recent call last):
  File "./fuzz_x8664_linux.py", line 125, in <module>
    main(sys.argv[1])
  File "./fuzz_x8664_linux.py", line 119, in main
    ql.run()
  File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/core.py", line 707, in run
    self.os.run()
  File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 139, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/core.py", line 870, in emu_start
    raise self._internal_exception
  File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/utils.py", line 163, in wrapper
    return func(*args, **kw)
  File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/core_hooks.py", line 165, in _hook_addr_cb
    ret = h.call(ql, addr, size)
  File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/core_hooks_types.py", line 35, in call
    return self.callback(ql)
  File "./fuzz_x8664_linux.py", line 96, in start_afl
    if not _ql.uc.afl_fuzz(input_file=input_file, place_input_callback=place_input_callback, exits=[ql.os.exit_point]):
  File "/home/kawkab/.local/lib/python3.8/site-packages/unicornafl/unicornafl.py", line 153, in uc_afl_fuzz
    raise UcAflError(err)
**unicornafl.unicornafl.UcAflError**

**Comment by wtdcode** [comment]
Qiling hasn't been updated to the new version and I'm testing the compatibility with the AFL++ guys at this time. Sorry for the delay and we will do it ASAP.

**Comment by KA2010** [comment]
How I know if you update yet or not ?
Could you post here please
