### ISSUE TITLE
bug/qdb-handle_bnj_arm-add-line-parsing

### ISSUE THREAD

**Issue by whoismissing** [qilingframework/qiling#1042]
https://github.com/qilingframework/qiling/blob/94bf7a3bc4e3ea0cffaaa52dbc477c11030f631b/qiling/debugger/qdb/utils.py#L309

In `qdb/utils.py::handle_bnj_arm()`, 
```python
elif line.mnemonic == "add":
        r0, r1, r2 = line.op_str.split(", ")
```

the disassembly line parsing for the instruction 

`add pc, pc, r2, lsl #2`.

fails with a `too many values to unpack (expected 3)` error.

To reproduce, use the opcode `b'\x02\xf1\x8f\xe0'` and run a single-step using `do_step()`

**Comment by ucgJhe** [comment]
First of all, thanks for using qdb. Second, this occurred due to un-handled logical bits shifting, PR #1044 should be a fix for this.
