### ISSUE TITLE
[x] [Thread 2000] Syscall ERROR: ql_syscall_execve DEBUG: list index out of range

### ISSUE THREAD

**Issue by Kirito0** [qilingframework/qiling#1048]
qiling version: 1.4.1.dev0
test.c:
```c
#include <stdio.h>
int main(int argc, char const *argv[])
{
  execve("/bin/sh", NULL, NULL);
  return 0;
}
```
And we run it with:
```python
rootfs = "./rootfs/x8664_linux"
filepath = './test'
ql = Qiling([filepath],rootfs,verbose=QL_VERBOSE.OFF,multithread=True)
ql.run()
```
We got "[x] [Thread 2000]       Syscall ERROR: ql_syscall_execve DEBUG: list index out of range".
But if we change test.c to:
```c
#include <stdio.h>
int main(int argc, char const *argv[])
{
  char *argvv[] = {"/bin/sh", NULL};
  char *envpp[] = {NULL};
  execve("/bin/sh", argvv, envpp);
  //execve("/bin/sh", NULL, NULL);
  return 0;
}
```
It works.

**Comment by elicn** [comment]
Thanks for reporting this.
Though the first form you used may be supported on some Linux systems, it is considered non-stnadard and it is not recommended. The second form, however, is.

This is the relevant excerpt from the `execve` man page [available [here](https://www.man7.org/linux/man-pages/man2/execve.2.html)]:
![image](https://user-images.githubusercontent.com/10291650/147476330-8783260d-903f-4ad3-a22d-8b956fd79f37.png)

**Comment by Kirito0** [comment]
Okay, thanks for your answers.
