### ISSUE TITLE
Does Qiling support different glibc versions?

### ISSUE THREAD

**Issue by Kirito0** [qilingframework/qiling#1059]
qiling version: 1.4.1, unicorn version: 2.0.0rc5.post1
test_qiling.py:
```python
rootfs = "./rootfs/x8664_linux"
filepath = './test'
ql = Qiling([filepath],rootfs,verbose=QL_VERBOSE.OFF,multithread=True)
ql.run()
```
test.c:
```c
#include <stdio.h>
int main(int argc, char const *argv[])
{
  puts("hello");
  return 0;
}
```
It runs normally in glibc 2.27 and 2.31 (I only modified libc.so.6 and its corresponding version of ld-linux-x86-64.so.2 in rootfs).
But if I change test.c as follows:
```c
#include <stdio.h>
int main(int argc, char const *argv[])
{
  system("/bin/x8664_hello");
  return 0;
}
```
It runs normally in glibc 2.27. But in glibc 2.31. I got:
![image](https://user-images.githubusercontent.com/16188541/148073662-ea16a08e-d3f1-4ebd-8f6b-23ca2dcc3fcd.png)
![image](https://user-images.githubusercontent.com/16188541/148073290-b19d6792-12df-4af3-9b94-e60b602cc12f.png)
I even tried to move all the libs of 2.31 over, but it still got the same error. How can I make it work correctly? Or whether Qiling can customize rootfs.

**Comment by elicn** [comment]
Customizing `rootfs` is possible and depends on the path you point the `rootfs` arg to.
As for `prctl`, code `0x3001` refers to Intel CET and we haven't implemented it yet [see here: #950].
