### ISSUE TITLE
Some problems with fuzz

### ISSUE THREAD

**Issue by a4865g** [qilingframework/qiling#1066]
Hi, I'm trying to fuzz the dlink_dir815 example. But it is not quite the same as before I ran...?

Now, In dlink_dir815 example:
```
$ python3 dir815_mips32el_linux.py afl_inputs/a 
Starting afl_fuzz().
[!] SHARED MEMORY FUZZING Feature is not enabled.
Starting afl_fuzz().
HTTP/1.1 200 OK
Content-Type: text/xml

<hedwig><result>FAILED</result><message>unable to open temp file.</message></hedwig>^Z
[2]+  Stopped                 python3 dir815_mips32el_linux.py afl_inputs/a
```

If i don't enter `ctrl + Z`,the program will hang at the end of CGI execution.

This seems a bit strange...?

I remember that there will be no "**[!] SHARED MEMORY FUZZING Feature is not enabled.**" message before Nov 2021 exec, and there will be "**Ran once without AFL attached.**" at the end.

Like this:
```
$ python3 dir815_mips32el_linux.py afl_inputs/a 
Starting afl_fuzz().
Starting afl_fuzz().
HTTP/1.1 200 OK
Content-Type: text/xml

<hedwig><result>FAILED</result><message>unable to open temp file.</message></hedwig>Ran once without AFL attached.
```

Maybe it's a problem with unicornafl2.0...?

```
$ python3 -c "import unicorn;import importlib.metadata;print(importlib.metadata.version('unicorn'))"
2.0.0rc5.post1

$ python3 -c "import importlib.metadata;print(importlib.metadata.version('unicornafl'))"
2.0.0
```

Could anybody give me a few pointers with the problem?

Or how do I go back to the previous state (Nov 2021)?

Thanks!!

**Comment by a4865g** [comment]
Resolved.

It's like [issue#983](https://github.com/qilingframework/qiling/issues/983).

Just checkout [a69141](https://github.com/qilingframework/qiling/commit/a6914111c47a7e0d372b08ec0dce95842229a3c1), and reinstall.

So, can work!

**Comment by xwings** [comment]
Cool!

**Comment by KA2010** [comment]
Hello, Could you please let me know, how you made it work, still the fuzzer is not working with me properly as the total path is not increasing at all

**Comment by a4865g** [comment]
@KA2010 

Hi, I just checkout [a69141](https://github.com/qilingframework/qiling/commit/a6914111c47a7e0d372b08ec0dce95842229a3c1),and installing it.
(You can check your unicornafl version.)

Also, you must be install [AFL++](https://github.com/AFLplusplus/AFLplusplus).

If any questions, you can screenshot the info.

Thanks!

**Comment by a4865g** [comment]
Make a small record:

AFL++ needs checkout [630ba07](https://github.com/AFLplusplus/AFLplusplus/commit/630ba07054892dfbaa477034b01c9eb8e1d7de88).
