### ISSUE TITLE
Get all memory content

### ISSUE THREAD

**Issue by pmondon** [qilingframework/qiling#1085]
Dear Qiling team,

I would like to know if there is any way to get all the memory content from a snapshot. I want to be able to parse myself all the memory to search for particular data.  I see in the debug mode that all the information are present as they are displayed yet I can't find a way to get this memory.
Thank you in advance for your time.

**Comment by wtdcode** [comment]
Snapshot in theory is just a python pickle object and thus you may unpickle it by yourself. However, it looks like a design flaw since the format of the snapshot is not specified anywhere.

**Comment by xwings** [comment]
Close for now.

We updated the codebase for Qiling and Unicorn since this issue being posted.

Feel free to try the latest version.
