### ISSUE TITLE
How does the qiling implement "current_task"?

### ISSUE THREAD

**Issue by qkenr7895** [qilingframework/qiling#1098]
Hi!
I have a question about using the demigod module to emulate the linux kernel module.

I tried to access current "task_struct" through "current", but I found that "current" was NULL.

When using "current", it seems to be translated into a GS register.
So I looked at how the GS register is implemented in qiling.

When I see the code, the address and the segment size of the GS register are defined, but the content is not defined.

I thought "current_task" content is implemented through memory snapshot or some arbitrary task_struct value.

Is it intended to implement "current_task" as zero? 
If so, is it because there's no big problem in emulating the "current" as zero?

I really appreciate of your nice emulator.
Thanks you!

**Comment by xwings** [comment]
Close for now.

We updated the codebase for Qiling and Unicorn since this issue being posted.

Feel free to try the latest version.
