### ISSUE TITLE
Migration to pyproject.toml? (PEP 517, 518 support)

### ISSUE THREAD

**Issue by nullableVoidPtr** [qilingframework/qiling#1109]
I can do this in a PR, but I wanted to ask if there were any objections before I get started on this.

As of recently, [`setup.py` has been considered deprecated](https://pip.pypa.io/en/stable/reference/build-system/setup-py/) in favor of a [build-system independent format](https://www.python.org/dev/peps/pep-0517/#source-trees).
Seeing as qiling only uses `setuptools` anyways, the plan to migrate the package to PEP 518 is to specify only `setuptools` in the `pyproject.toml` file, alongside dependencies, license, and other metadata.
This setup would either shrink or remove `setup.py` entirely; setuptools itself does not support editable installs without a `setup.py`, but that has a [workaround in `pip`](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation), although this mandates a minimum pip version of 21.3.

**Comment by elicn** [comment]
Keeping up to date with the standard is always good, but we have leave some room for slower user adoption (meaning not moving forward too fast). Specifically, this project made a decision to move to Python 3.8 just recently, so we have to make sure this change doesn't break anything.

That being said, I think this is a great idea.

**Comment by xwings** [comment]
Close for now.

We updated the codebase for Qiling and Unicorn since this issue being posted.

Feel free to try the latest version.
