### ISSUE TITLE
 “API for fake installed application” specific means?

### ISSUE THREAD

**Issue by theoyuandawang** [qilingframework/qiling#111]
When I look up the TODO file, in Windows's part: "API for fake installed application"
Wanna ask what's the specific means?
Are there any specific requirements? Is it possible to run any program like on a real Windows system?

**Comment by xwings** [comment]
Hi,

First of all, its in TODO.  This simply means we still need to work it.

So, this part simply means. How can we make API, so users can pass in "Installed Software" and make the emulator more alive

**Comment by theoyuandawang** [comment]
Thank you for responding to my issue so quickly, I will continue to try to learn the framework and think about this todo
