### ISSUE TITLE
examples/fuzzing 存在问题

### ISSUE THREAD

**Issue by Greeneyesredmetal** [qilingframework/qiling#1130]
**examples/fuzzing目录下测试报错**
       我的环境为Ubuntu20.04，遵照指导书，在git clone qiling之后，安装完成，在examples/fuzzing/dlink_dir815下进行测试，出现了No module named 'qiling.extensions.afl'错误。（PS：因为这个错误，无法使用AFL正常fuzz）

**具体细节**
```shell
$ python3 dir815_mips32el_linux.py ./afl_inputs/a 
Traceback (most recent call last):
  File "dir815_mips32el_linux.py", line 13, in <module>
    from qiling.extensions.afl import ql_afl_fuzz
ModuleNotFoundError: No module named 'qiling.extensions.afl'
```

**Comment by kabeor** [comment]
@Greeneyesredmetal Hi, can you list what commands you used when install qiling?

**Comment by Greeneyesredmetal** [comment]
i first use '''pip3 install . ''' and then it error, next i use '''python3 setup.py install'''

PS: i am sorry that i cannot remember the permission i used.

PS: during '''pip3 install .''', it occur that "PyYAML cannot uninstall", and then i added the --ignore-install, did it matter?

and today, i modified the py file, copy the afl.py to the directory, it did work.
obviously, it is not a problem, but not elegant i believe.😬😬😬
looking forward to your reply!




---- 回复的原邮件 ----
| 发件人 | Wu ***@***.***> |
| 日期 | 2022年04月16日 21:18 |
| 收件人 | ***@***.***> |
| 抄送至 | Green ***@***.******@***.***> |
| 主题 | Re: [qilingframework/qiling] examples/fuzzing 存在问题 (Issue #1130) |

@Greeneyesredmetal Hi, can you list what commands you used when install qiling?

**Comment by kabeor** [comment]
actually I think there were some problems when you install qiling at first. 
Try to:
```
make sure your python version is 3.8+
checkout to dev branch
just using 'python3 setup.py install'
```
should be fine

**Comment by Greeneyesredmetal** [comment]
thanks! I will try!



---- 回复的原邮件 ----
| 发件人 | Wu ***@***.***> |
| 日期 | 2022年04月16日 23:26 |
| 收件人 | ***@***.***> |
| 抄送至 | Green ***@***.******@***.***> |
| 主题 | Re: [qilingframework/qiling] examples/fuzzing 存在问题 (Issue #1130) |

actually I think there were some problems when you install qiling at first.
Try to:

make sure your python version is 3.8+
checkout to dev branch
just using 'python3 setup.py install'


should be fine

**Comment by Greeneyesredmetal** [comment]
> actually I think there were some problems when you install qiling at first. Try to:
> 
> ```
> make sure your python version is 3.8+
> checkout to dev branch
> just using 'python3 setup.py install'
> ```
> 
> should be fine


it work. thanks.
