### ISSUE TITLE
Can't convert emu_optname 4 to host platform based optname

### ISSUE THREAD

**Issue by tigerOrtiger** [qilingframework/qiling#1131]
***Describe the bug**

**Sample Code**
```python
ql = Qiling(["x8664_freebsd/bin/x8664_hello_asm"], "x8664_freebsd", output = "dump")
ql.run()
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tigerOrtiger** [comment]
I'm running Tenda AC15 firmware, when I visit http://127.0.0.1:8080, I can't access and display "Bad HTTP Request".
```
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
[httpd][debug]----------------------------webs.c,157
httpd listen ip = 127.0.0.1 port = 80
webs: Listening for HTTP requests at address 127.0.0.1
[x] 	Can't convert emu_optname 4 to host platform based optname
```

**Comment by tigerOrtiger** [comment]
![image](https://user-images.githubusercontent.com/37855720/163943556-08c7210d-ebc5-4dbf-ba96-0d4d938368b4.png)

**Comment by tigerOrtiger** [comment]
![image](https://user-images.githubusercontent.com/37855720/163943726-c7102d80-0235-4cb6-8662-fa260cb084bb.png)

**Comment by elicn** [comment]
Telling by the way Qiling is initialized, you are probably using an obsolete version of Qiling.
Did you `pip install` it, or cloned it from githug?

**Comment by tigerOrtiger** [comment]
Hello, I'm clone from Github

**Comment by tigerOrtiger** [comment]
bingo , I solved the problem,  I can't run the code impact error is "BlockingIOError: [Errno 11] Resource temporarily unavailable", This error occurs because the Ubuntu 20.04 virtual machine has insufficient hardware resources，I changed the running memory to 16GB and changed it to 8 cores

**Comment by elicn** [comment]
Did you manage to solve the issue?

**Comment by tigerOrtiger** [comment]
Yes, I solved my problem

**Comment by tower111** [comment]
I got this bug too 
[x] [Thread 2000]	Syscall ERROR: ql_syscall_recv DEBUG: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/tower/miniconda3/envs/iot/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 374, in load_syscall
    retval = syscall_hook(self.ql, *params)
  File "/home/tower/miniconda3/envs/iot/lib/python3.8/site-packages/qiling/os/posix/syscall/socket.py", line 676, in ql_syscall_recv
    content = sock.recv(length, flags)
  File "/home/tower/miniconda3/envs/iot/lib/python3.8/site-packages/qiling/os/posix/filestruct.py", line 116, in recv
    return self.__socket.recv(bufsize, flags)
BlockingIOError: [Errno 11] Resource temporarily unavailable

**Comment by elicn** [comment]
Hi @tower111,
I guess it would be best to create a new issue with all the necessary context.
