### ISSUE TITLE
ARM64: `Q?` registers are missing from the available register names

### ISSUE THREAD

**Issue by LukeSerne** [qilingframework/qiling#1138]
**Describe the bug**
The ARM64 `Q?` registers are missing from the available register names, so you cannot simply use `ql.reg.read("Q0")` to read the `Q0` register. In contrast, you can use `ql.reg.read("X0")` to read the `X0` register.

**Sample Code**
```python
import qiling

ql = qiling.Qiling(code=b"\0", archtype=qiling.const.QL_ARCH.ARM64, ostype='linux')

for i in range(32):
    ql.reg.read(f"Q{i}")  # doesn't work
    # the below two lines would work
    # import unicorn
    # ql.reg.read(getattr(unicorn.arm64_const, f"UC_ARM64_REG_Q{i}"))
```
**Actual behavior**
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    ql.reg.read(f"Q{i}")  # doesn't work
  File "~/.local/lib/python3.10/site-packages/qiling/arch/register.py", line 61, in read
    register = self.register_mapping[register.lower()]
KeyError: 'q0'
```
**Expected behavior**
The `Q[i]` register should be read. That is, `ql.reg.read(f"Q{i}")` in the above script should return the same value as the line below that uses the unicorn constant.

It would be nice if the `V?`, `D?`, `S?`, `H?` and `B?` registers were also added.

**Comment by wtdcode** [comment]
This is a known bug because Qiling still misses a few new features Unicorn2 brings at this moment. We would appreciate it if you would like to help. ;)

**Comment by elicn** [comment]
Covered in https://github.com/qilingframework/qiling/pull/1148/commits/8549aa7d6d67b9950d819143de15acdbcb544afe

**Comment by elicn** [comment]
@LukeSerne please re-try with a fresh `dev` copy.
