### ISSUE TITLE
Can I change the target argc using the Qiling API?

### ISSUE THREAD

**Issue by a4865g** [qilingframework/qiling#1156]
As title.

I want to try to set the amount of argv at the beginning to be different from the argc read after entering the target main().
How should I do this?

Example: Change the target argc 4 to 2
```
from qiling import Qiling
from qiling.const import QL_VERBOSE

if __name__ == "__main__":
    argv = r'examples/target -a1 -a2 -a3'.split() # <======== target argc = 4
    rootfs = r'examples/rootfs/x8664_linux'

    ql = Qiling(argv, rootfs, verbose=QL_VERBOSE.DEBUG)

    # do something to change the target argc = 2

    ql.run()
```

Could anybody give me a few pointers with the problem?
Thanks!!

**Comment by KA2010** [comment]
could you provide your code ?

**Comment by a4865g** [comment]
@KA2010 

Like:
```
def change(ql: Qiling):
    ql.reg.edi = 2
ql.hook_address(callback = change, address = ba + int(target_main_address, 16))
```

**Comment by KA2010** [comment]
@a4865g 
Thanks

**Comment by KA2010** [comment]
@a4865g 
Is I can use same function to change argv too?

**Comment by elicn** [comment]
Yes. You may set the `rsi` reg value in the same manner, but make sure it points to an allocated memory where you placed an awway of null-terminated strings.

Note that accessing function arguments is determined by the calling convention. You may take the generic approach and use the `ql.os.fcall.cc.setRawParam` that takes the argument index, value and bit size as parameters. For example:

```python
ql.os.fcall.cc.setRawParam(0, new_argc_val, 64)
ql.os.fcall.cc.setRawParam(1, new_argv_val, 64)
```
So you don't have to bother following the calling convention.
