### ISSUE TITLE
ARM: `d?` registers cannot be read

### ISSUE THREAD

**Issue by LukeSerne** [qilingframework/qiling#1179]
**Describe the bug**
The ARM `d?` registers are missing from the available register names, so you cannot simply use `ql.reg.read("d0")` to read the `d0` register. In contrast, you can use `ql.reg.read("r0")` to read the `r0` register.

**Sample Code**

```python
import qiling

ql = qiling.Qiling(code=b"\0", archtype=qiling.const.QL_ARCH.ARM, ostype='linux')

for i in range(32):
    ql.reg.read(f"d{i}")  # doesn't work
    # the below two lines would work
    # import unicorn
    # ql.reg.read(getattr(unicorn.arm_const, f"UC_ARM_REG_D{i}"))
```

**Actual behavior**

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    ql.reg.read(f"d{i}")  # doesn't work
  File "~/.local/lib/python3.10/site-packages/qiling/arch/register.py", line 61, in read
    register = self.register_mapping[register.lower()]
KeyError: 'd0'
```

**Expected behavior**
The `d[i]` register should be read. That is, `ql.reg.read(f"d{i}")` in the above script should return the same value as the line below that uses the unicorn constant.

**Comment by LukeSerne** [comment]
Ah, thank you for the information. I have updated, and `ql.arch.regs.d0` does seem to work as well. Is this behaviour planned to be removed in a future version?

**Comment by elicn** [comment]
No; all three methods are valid and may be used interchangeably.
