### ISSUE TITLE
MCU submodule available in source distribution but not in built distribution.

### ISSUE THREAD

**Issue by ohunter** [qilingframework/qiling#1183]
**Describe the bug**
When downloading the built distribution from pip, it is missing the `mcu` submodule under `/qiling/os`. This is not the case for the source distribution.

**Expected behavior**
I'd expect the `mcu` module to be available as it is present in the source distribution.

**Screenshots**
Source:
![image](https://user-images.githubusercontent.com/2663525/176396711-de16f4fa-aadc-4ad3-b365-0512e38c1f5f.png)
Built:
![image](https://user-images.githubusercontent.com/2663525/176396797-0c48f20f-4f1e-413c-8b1b-ff6f31640f2a.png)

**Comment by xwings** [comment]
could be the lacking of __init__.py missing in the mcu foldeer.

**Comment by ohunter** [comment]
That may well be, but it actually seemed to import without any issues the moment I just pasted the folder in the right place on my filesystem.

**Comment by xwings** [comment]
added __init__.py it should work in the next release.

**Comment by xwings** [comment]
Close for now.

We updated the codebase for Qiling and Unicorn since this issue being posted.

Feel free to try the latest version.
