### ISSUE TITLE
Pwndbg context won't work with gdb remote debugging

### ISSUE THREAD

**Issue by dzonerzy** [qilingframework/qiling#1188]
**Describe the bug**

Maybe this bug is pwndbg related and not qiling fault, but still worth to ask, when i use the remote gdb debugging with qiling and I connect with pwmdbg, the debugger works but the context is fucked up like in the screenshot:

![img](https://i.gyazo.com/3311b8165a5f38ff3484e5f8e49620f2.png)

**Sample Code**
```python
from qiling import *
from qiling.arch.arch import QL_ARCH
if __name__ == "__main__":
    ql = Qiling(["rootfs/hello.arm"], "rootfs")
    ql.debugger = "gdb:127.0.0.1:9999"
    ql.run()
```

**Expected behavior**
Pwndbg should just work fine

**Additional context**
The infinite loop seems to happen when pwndbg looks for binary memory mappings

**Comment by dzonerzy** [comment]
Tried that fix and seems to work but still can't show context now i have this error: 

![err](https://i.gyazo.com/db1518ab4682a1b8cb6af20ae9663b25.png)

maybe this is something you already solved

**Comment by dzonerzy** [comment]
This issue is related to pwndbg.regs.cpsr not being set and thus being None, if you tell me what I should look i can try to fix it

**Comment by wtdcode** [comment]
I'm on fixing this however it somehow involves a deeper refactor so the fix might be a bit late.

**Comment by wtdcode** [comment]
> This issue is related to pwndbg.regs.cpsr not being set and thus being None, if you tell me what I should look i can try to fix it

I can't reproduce this.

**Comment by xwings** [comment]
Close for now.

We updated the codebase for Qiling and Unicorn since this issue being posted.

Feel free to try the latest version.
