### ISSUE TITLE
Error loading kernel module nfnetlink.ko

### ISSUE THREAD

**Issue by pavel-gorbachev** [qilingframework/qiling#1192]
***Describe the bug**
When executing a load to emulate the nfnetlink.ko kernel module. An error occurs. Presumably due to passing in the lkm_dynlinker function as a string 'SHN_ABS' rather than a numeric parameter (_section = elffile.get_section(_symbol['st_shndx']))

**Sample Code**
```
#!/usr/bin/python3

import sys
from qiling import *
from qiling.const import QL_VERBOSE

def test(path, rootfs):
    ql = Qiling(path, rootfs, verbose=QL_VERBOSE.DEBUG)

    print(f"ql.loader.load_address: {ql.loader.load_address}")
    ql.run(ql.loader.load_address + 0x1205, ql.loader.load_address + 0x126c)  

if __name__ == "__main__":
    test(["nfnetlink.ko"], 
    "rootfs/x8664_linux")
```

**Expected behavior**

**Screenshots**
![изображение](https://user-images.githubusercontent.com/42390708/178729277-e82d5893-991e-497a-b98c-71ba14d185f9.png)

**Kernel module**
[nfnetlink.zip](https://github.com/qilingframework/qiling/files/9101949/nfnetlink.zip)

**Comment by aquynh** [comment]
support for LKM are not well maintained, so PR to fix bugs are welcome

**Comment by elicn** [comment]
Just comitted a fix for that specific problem.
However, like mentioned above, it looks like LKM emulation is not reliable at the moment.
