### ISSUE TITLE
gdb debugger default ip maybe wrong?

### ISSUE THREAD

**Issue by Mas0nShi** [qilingframework/qiling#1204]
***Describe the bug**
the localhost is `127.0.0.1` but set default to `127.0.01` ?

**Sample Code**

https://github.com/qilingframework/qiling/blob/6bde122b38625ab67a728a3adfbab7038e5ae8f6/qiling/debugger/gdb/gdb.py#L69

https://github.com/qilingframework/qiling/blob/6bde122b38625ab67a728a3adfbab7038e5ae8f6/qiling/debugger/gdb/gdb.py#L113

https://github.com/qilingframework/qiling/blob/6bde122b38625ab67a728a3adfbab7038e5ae8f6/qiling/debugger/gdb/gdb.py#L797

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chinggg** [comment]
Hi! I was also confused about that before, but I tried `127.0.01` with `ping` and `curl` and it worked!

**Comment by Mas0nShi** [comment]
> Hi! I was also confused about that before, but I tried `127.0.01` with `ping` and `curl` and it worked as `127.0.0.1`! (You can even try `127.1`) Maybe that's one of the weird features of IP addresses.

Thx! I guess it problem with cpython or OS parse address.

> I am not sure why the developers use it instead of something more common like localhost for the default IP.

I think it just a typo.

---

Anyway, thank you for your reply! 

Closed.

**Comment by elicn** [comment]
Hi @Mas0nShi,
Welcome to Qiling and thanks for reporting that.0This is indeed a typo and should be fixed - so I am reopening it.
As for the reason it worked, I think it is because omittions are considered as '0', just like in IPv6.

**Comment by xwings** [comment]
this bug is silly and it just worked ...
