### ISSUE TITLE
'Qiling' object has no attribute 'set_syscall'

### ISSUE THREAD

**Issue by Ryze-T** [qilingframework/qiling#1223]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/76553352/188539406-d334830c-15b8-46ab-a5f0-b3a779f5fbcf.png">

**Comment by Coinstine** [comment]
hi here, i have the same issues, could u tell me how u fix it?

**Comment by Ryze-T** [comment]
I think the API dockment is outdated，'set_syscall' became 'os_set_syscall'。
I recommend that you complete qiling-labs，and refer to this article：
https://ryze-t.com/2022/09/08/Qiling%E6%A1%86%E6%9E%B6%E5%85%A5%E9%97%A8-QilingLab/

**Comment by Coinstine** [comment]
wow, thanks bro!

**Comment by elicn** [comment]
Recommending to use an IDE with auto-completion to see where certain properties and methods are located.
And if you want to brush up your Qiling skills, then here is [another shameless plug](https://github.com/elicn/QilingLab/blob/main/solver.py) for QilingLabs.
