### ISSUE TITLE
tendaac1518_httpd.py unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

### ISSUE THREAD

**Issue by Ryze-T** [qilingframework/qiling#1229]
I followed the official documentation, used the official example:

https://github.com/qilingframework/qiling/blob/master/examples/tendaac1518_httpd.py

and still got an error :
<img width="778" alt="image" src="https://user-images.githubusercontent.com/76553352/189840810-296e4487-832f-4c49-8a41-536578047b5b.png">

I suggest that the official write a tutorial about the simulation firmware！！！

**Comment by elicn** [comment]
I recreated the environment to test it, but I am afraid I am no ARM expert, so I cannot tell exactly what's wrong there.
I did pick up the following, however:
 - The `/proc/sys/net/ipv4` folder should be created under rootfs
 - The `/proc/sys/kernel` folder should be created under rootfs
 - A file named `/proc/sys/kernel/core_pattern` is created on every run, and should be removed before running again
 - The code accesses memory on `0xfffddxxx`, which I guess has a special meaning for that particular ARM processor, but I do not know what it is. So I ended up just mapping it with `ql.mem.map(0xfffdd000, 0x1000)`, and it kept running for a while until it crashed with access to page 0, which I suspect is a result of bogus data it read from the afored address. My guess is that zeros were read from the mapped address and then used in a pointer calculation for a further access that failed.

I don't know enough to really fix this.
Perhaps @xwings knows and can help fixing it.

**Comment by Ryze-T** [comment]
> I recreated the environment to test it, but I am afraid I am no ARM expert, so I cannot tell exactly what's wrong there. I did pick up the following, however:
> 
> * The `/proc/sys/net/ipv4` folder should be created under rootfs
> * The `/proc/sys/kernel` folder should be created under rootfs
> * A file named `/proc/sys/kernel/core_pattern` is created on every run, and should be removed before running again
> * The code accesses memory on `0xfffddxxx`, which I guess has a special meaning for that particular ARM processor, but I do not know what it is. So I ended up just mapping it with `ql.mem.map(0xfffdd000, 0x1000)`, and it kept running for a while until it crashed with access to page 0, which I suspect is a result of bogus data it read from the afored address. My guess is that zeros were read from the mapped address and then used in a pointer calculation for a further access that failed.
> 
> I don't know enough to really fix this. Perhaps @xwings knows and can help fixing it.

Thank you for your help. 
And I've tried something similar, but it crashes after a while，I hope this problem will be properly solved.

**Comment by xwings** [comment]
As far as i remeber, there is some crash when running the binary. What do you trying to achive and which version of Qiling are you running ?

**Comment by Ryze-T** [comment]
Qiling: lastest
I want to run httpd successfully when I fix the crash

**Comment by xwings** [comment]
I found and the bug and the fix is in #1249
