### ISSUE TITLE
TypeError: iter_segments() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by KA2010** [qilingframework/qiling#1253]
hi, I am trying to run (hello_mips32el_linux_debug.py) but I am getting this error.
Anyone has clue of how to solve this issue?
Thanks

**Comment by bet4it** [comment]
You need to upgrade version of `pyelftools` dependency.

**Comment by KA2010** [comment]
Could you please give me the correct command because I try 
> pip install pyelftools
but the error still there

**Comment by elicn** [comment]
```sh
python3 -m pip install --upgrade pyelftools
```

**Comment by KA2010** [comment]
that solve this issue, thank you so much

**Comment by elicn** [comment]
> TypeError: **cinit**() takes at least 2 positional arguments (1 given)

Can you give more context to this?
Perhaps a Python stacktrace?
