### ISSUE TITLE
getsockname missing AF_UNIX functionality

### ISSUE THREAD

**Issue by sahinburak** [qilingframework/qiling#1261]
**getsockname** doesn't have check of AF_UNIX and AF_INIT. **getsockname** raises error on line `host, port = socket.getpeername()` which will work for AF_INET. I believe there should be check for socket.family and cover AF_UNIX case seperately.

**Comment by elicn** [comment]
Hi @sahinburak,
This one should be fixed now in `dev` branch.
Would appreciate if you could re-run your program and let us know.

**Comment by elicn** [comment]
Fixed in the recent release.
