### ISSUE TITLE
Probably wrong type for QlArchCORTEX_M ?

### ISSUE THREAD

**Issue by ucgJhe** [qilingframework/qiling#1265]
I'm working on some fix for mcu in qdb, and found this

https://github.com/qilingframework/qiling/blob/dev/qiling/arch/cortex_m.py#L66

Is this intended for some reason ? It'll break mcu tests if changed to CORTEXT_M. If this is necessary i will try to do something else for telling us that we're running COTEX_M since qdb rely on `ql.arch.type`.

**Comment by xwings** [comment]
@cla7aye15I4nd any comments ?

**Comment by elicn** [comment]
I changed that, as far as I remember, because its usages were only to determine whether it is an ARM arch (i.e. always checked if CORTEX_M or ARM).

If this is really needs to be changed, we can create an arch set to include all AArch ones and change the code accordingly.

**Comment by ucgJhe** [comment]
simply change to `QL_ARCH.CORTEX_M` will break the test, I have no idea why, need some expert here.

**Comment by elicn** [comment]
@ucgJhe, please grab the PR mentioned above and let me know whether it fixes the issue.

**Comment by elicn** [comment]
I am tentatively closing this issue.
@ucgJhe, feel free to re-open it if you think the issue hasn't been resolved.
