### ISSUE TITLE
raise QlErrorFileNotFound(f'Windows registry directory not found: "{hivedir}"!')

### ISSUE THREAD

**Issue by KA2010** [qilingframework/qiling#1268]
qiling.exception.QlErrorFileNotFound: Windows registry directory not found!
how might I get rid of this issue?
Thanks

**Comment by brandonros** [comment]
what was solution?

**Comment by brandonros** [comment]
looks like https://docs.qiling.io/en/latest/install/#important-note-on-windows-dlls-and-registry

**Comment by KA2010** [comment]
> looks like https://docs.qiling.io/en/latest/install/#important-note-on-windows-dlls-and-registry

yes
