### ISSUE TITLE
ARGV should be able to be either string or bytes

### ISSUE THREAD

**Issue by ucgJhe** [qilingframework/qiling#1269]
Example C code:
```c
#include <stdio.h> 
#include <string.h> 
 
int main(int argc, char *argv[]) { 
    printf("%d\n", strlen(argv[1])); 
    return 0; 
}
```

```python
from qiling import Qiling 
 
ql = Qiling(["a.out", "AAAA"], rootfs="/") 
ql.run() 
 
ql = Qiling(["a.out", b"\x80\x80\x80\x80"], rootfs="/") 
ql.run()
```

results should be identical

**Comment by ucgJhe** [comment]
also cc @elicn

**Comment by xwings** [comment]
what is the current output?

**Comment by elicn** [comment]
The current implementation assumes argv is `str`, and does not provide conversion for `bytes`.
Looking at the code, it appears that there are multiple changes needed across several modules to support that.

Running a program with `bytes` argv is something we need to support if we want people to be able to test programs for vulnerabilities or reproduce interesting crashes.

I'll assign myself to this for the moment and see when I can patch this.
Anyone else is welcome to take this in the meantime (:
