### ISSUE TITLE
syscall ql_syscall_ipc number = 0x1015(4117) not implemented

### ISSUE THREAD

**Issue by readermall** [qilingframework/qiling#1277]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Send us a pull request always help, or any pseudo code might be useful.

**Comment by elicn** [comment]
Hi @ireading2022, welcome to Qiling.
When opening an issue you should replace the boilerplate text with your own.
Currently there is not enough context / information we can work with to investigate the issue.

Could you please edit and provide more details? (what are you trying to emualte, which OS, is there something special about this emualtion case, what you expected it to do and what hapened evenatuall, etc.)

**Comment by ireading2022** [comment]
**Is your feature request related to a problem? Please describe.**
When I simulate the Tenda /bin/webs program, I get an error "syscall ql_syscall_ipc number = 0x1015(4117) not implemented", after debugging it is found that it is caused by qiling not implementing posix syscall ipc, does qiling have a plan to implement it?

The code that caused the error：

```
__syscall_ipc:                    # CODE XREF: semget+34↓p

li      $gp, (_GLOBAL_OFFSET_TABLE_+0x7FF0 - .)
addu    $gp, $t9
addiu   $sp, -0x18
sw      $fp, 0x10+var_s4($sp)
sw      $s0, 0x10+var_s0($sp)
move    $fp, $sp
lw      $s0, 0x10+arg_14($fp)
addiu   $sp, -0x10
lw      $v0, 0x10+arg_10($fp)
addiu   $sp, -0x20
sw      $v0, 0x40+var_30($sp)
sw      $s0, 0x40+var_2C($sp)
li      $v0, 0x1015
syscall
```

qiling reports the wrong location:
```
        for name, value in zip(param_names, params):
                # cut the first part of the arg if it is of form fstatat64_fd
                if name.startswith(f'{syscall_basename}_'):
                    name = name.partition('_')[-1]

                args.append((name, f'{value:#x}'))

            sret = QlOsPosix.getNameFromErrorCode(retval)
            self.utils.print_function(self.ql.arch.regs.arch_pc, syscall_basename, args, sret, False)

            # record syscall statistics
            self.stats.log_api_call(self.ql.arch.regs.arch_pc, syscall_name, dict(zip(param_names, params)), retval, None)
        else:
            self.ql.log.warning(f'{self.ql.arch.regs.arch_pc:#x}: syscall {syscall_name} number = {syscall_id:#x}({syscall_id:d}) not implemented')

            if self.ql.debug_stop:
                raise QlErrorSyscallNotFound(f'Syscall not found: {syscall_name}')
```

**Describe the solution you'd like**
does qiling have a plan to implement it?

**Comment by ireading2022** [comment]
The qiling reports the wrong location is https://github.com/qilingframework/qiling/tree/master/qiling/os/posix/posix.py
