### ISSUE TITLE
Update Qiling to work within Ghidra (using Ghidrathon)

### ISSUE THREAD

**Issue by as0ni** [qilingframework/qiling#1301]
First, thank you creating qiling. It is an amazing capability to automate analysis. 

**Is your feature request related to a problem? Please describe.**
Currently I cannot run qiling within Ghidra using Ghidrathon. 

**Describe the solution you'd like**
A partial solution is to add a try/except statement similar to the one for IDAPython in `qiling/os/os.py`. As a test, I replaced `import ida_idaapi` with `import ghidra` in os.py and I was able to run Qiling within Ghidra using Ghidrathon. However, I could only run a script once. If I attempted to run the same script again, I received an error: 

![image](https://user-images.githubusercontent.com/8812157/210270382-cac9468d-8bd8-4f58-819b-d0bc6228cc0d.png)

Unfortunately I'm not sure how this error can be resolved. 

Thank you for your help.

**Comment by elicn** [comment]
This is not a Qiling bug, but an old win32com one (see [here](https://www.knowbrainer.com/forums/forum/messageview.cfm?catid=25&threadid=31568), for example). I don't know how to fix this, but would guess there is a state residual that needs to be deleted before reloading.

Before reloading, run `dir()` and see if you identify anything that is related to win32com and `del` it. Perhaps that would do the trick.

**Comment by as0ni** [comment]
My workaround for now is to use Ghidra's headless analyzer. Each run of the headless feature restarts the interpreter so the above issue doesn't occur.

**Comment by elicn** [comment]
Not a Qiling bug.
