### ISSUE TITLE
can I boot a kernel with qiling?

### ISSUE THREAD

**Issue by XinDistance** [qilingframework/qiling#1302]
If I have a linux kernel image with ramfs inside. And I hook the io exception to handle the serial port output and input (for example, uart8250). In this way I don't need to simulate a hard drive. Can I boot this kernel and get a bash console by using qiling?

My question is: Does qiling support full system simulation if everything is handled properly? if not, what is missed?

**Comment by xwings** [comment]
No. Qiling is not designed to do that.
