### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by Ryze-T** [qilingframework/qiling#1312]
Ubuntu 18.04：
pip3 install qiling

![image](https://user-images.githubusercontent.com/76553352/218663571-dde460c0-c26b-46f3-a314-8bff02682bdd.png)

**Comment by elicn** [comment]
This is a prerequisite for Qiling TUI.
The [module pip page](https://pypi.org/project/python-fx/#prerequisites) says it requires a Python 3.8+. Which Python version are you using?

**Comment by Ryze-T** [comment]
Now Python's version is 3.8, but a new error is created.
<img width="727" alt="image" src="https://user-images.githubusercontent.com/76553352/218965018-4e3b2472-d3d6-4ac6-973f-77a3fddc1f9c.png">

**Comment by Ryze-T** [comment]
When I reinstall setuptools:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/76553352/218966678-d2e982d4-e815-418b-92f7-b94487972ae6.png">

**Comment by elicn** [comment]
Do you still need help on this..? I see you closed the issue.

**Comment by Ryze-T** [comment]
Thanks, I hava solved the problem。
1. Install Python3.9 https://blog.csdn.net/qq_44324181/article/details/109883222
2. sudo apt install python3.9-venv
3. python3.9 -m venv qilingenv
source qilingenv/bin/activate
git clone -b dev https://github.com/qilingframework/qiling.git
cd qiling && git submodule update --init --recursive
pip install .
