### ISSUE TITLE
Failed to run tendaac15.py

### ISSUE THREAD

**Issue by Ryze-T** [qilingframework/qiling#1314]
***Describe the bug**
OS: Vmware workstation ubuntu18.04
Version: qiling1.4.5

**Sample Code**
tendaac15.py

**Screenshots**
![image](https://user-images.githubusercontent.com/76553352/219541508-82e25a8b-0965-4cd7-89df-9d1183ce6550.png)
After "check_network" patch:
![image](https://user-images.githubusercontent.com/76553352/219541858-4134fb72-0dfe-4052-ab09-8967d6161bce.png)

But if I use WSL2-ubuntu18.04 ,It works fine. 

 Can you publish a sample tutorial of the arm architecture, not just the code, but also the ideas for analysis and modification？
 I have contacted a number of users, all of whom have failed in this similar area and cannot resolve it.

**Comment by xwings** [comment]
What is the issue ? from the screenshot it seems running fine

and what do u mean by "a sample tutorial of the arm architecture"

**Comment by Ryze-T** [comment]
The screenshot above shows the dead loop in the function called  "check_network":
<img width="591" alt="image" src="https://user-images.githubusercontent.com/76553352/219544583-d9051a59-bc59-4241-966e-a8e273522dda.png">
The right situation：
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/76553352/219544229-a2da92e8-90b2-44c8-9d13-acb85f90ed43.png">


And I mean, I think most users need how to write tendaac15.py and how to debug and solve the error, not just a piece of code，

**Comment by elicn** [comment]
Start by creating the necessary directories trees:
```sh
cd linux_rootfs_dir_on_qiling
mkdir -p ./etc
mkdir -p ./proc/sys/net/ipv4
```
