### ISSUE TITLE
Debugger not supported

### ISSUE THREAD

**Issue by Ryze-T** [qilingframework/qiling#1332]
***Describe the bug**
TendaAC1518.py:
 ql.debugger=":9999"
Error: Debugger not supported
![image](https://user-images.githubusercontent.com/76553352/228798234-0d741a60-f329-4c6c-ae01-ae5a548532fb.png)

**Sample Code**
![image](https://user-images.githubusercontent.com/76553352/228798140-a9292332-1839-4783-a025-5e3b4f2d77e8.png)

**Comment by Ryze-T** [comment]
![image](https://user-images.githubusercontent.com/76553352/229007868-024f1b9e-bd13-48eb-ac18-9e79d5537f95.png)
I used tencent Cloud machine。
Does it matter?

**Comment by Ryze-T** [comment]
ql.debugger = "gdb:0.0.0.0:9999"

this code can solve it

**Comment by Ryze-T** [comment]
But When I used Ida Pro debug. tendaac18.py，It errors：
![image](https://user-images.githubusercontent.com/76553352/229010413-72aa142e-18b1-4a33-8ffb-747f4ea7e5f3.png)

**Comment by elicn** [comment]
It says "Address already in use", so you probably have another session opened with the same port number.
Just use another port number and it should be fine.

**Comment by Ryze-T** [comment]
Thanks,It work

**Comment by Ryze-T** [comment]
When I don't use debug options,It works:
![image](https://user-images.githubusercontent.com/76553352/229728874-b950b0e0-5f52-4e0d-9347-478502617b52.png)

When I open debug options and gdb connect it and run, It doesn't work:
![image](https://user-images.githubusercontent.com/76553352/229729372-b1d7ee76-5e2c-422e-9229-751bb8d706cb.png)
![image](https://user-images.githubusercontent.com/76553352/229729656-c8411ca0-86af-4637-a44e-99267e4d5868.png)
![image](https://user-images.githubusercontent.com/76553352/229729731-14ca203e-2f4a-4518-ba79-0bb9465c5eda.png)

**Comment by elicn** [comment]
I don't understand the problem you encounter, and the purpose of the attached screenshots is unclear to me.
Can you please clarify the situation?

**Comment by elicn** [comment]
Hey @KA2010, let me know what is the exact scenario in which you encounter the problem. Maybe we should re-open this one.
