### ISSUE TITLE
Host print fails after guest closes stdout

### ISSUE THREAD

**Issue by AminoACID123** [qilingframework/qiling#1338]
I am emulating a simple arm linux program, printing the executed basic block address during the emulation. Everything works fine until the emulated program calls `close(1)`. Below is the error message.

```
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [Errno 9] Bad file descriptor
``` 

It seems that closing `stdout` in the guest will affect host's too. Is that true?

**Comment by elicn** [comment]
Yes, that could be true and this is fixed as part of a new PR (#1336).
Why did you close the issue?

**Comment by AminoACID123** [comment]
I thought it might not be a serious problem, just avoid using print, so I closed this issue. Glad to know it has been fixed.

**Comment by elicn** [comment]
The fix is currently pending, so I reopen this.

**Comment by AminoACID123** [comment]
When will the fix be merged?

**Comment by elicn** [comment]
The fix has been merged to `dev`.
