### ISSUE TITLE
syscall ql_syscall_ftruncate64 number = 0xc2(194) not implemented

### ISSUE THREAD

**Issue by SRSG** [qilingframework/qiling#1340]
When I emulated a lighttpd program, I got this error.
```
0x9031288c: syscall ql_syscall_ftruncate64 number = 0xc2(194) not implemented
2023-04-21 11:25:34: server.c.305) ftruncate failed for: /run/lighttpd.pid: Operation not permitted
```
Do you have a plan to implement this syscall?

**Comment by elicn** [comment]
As stated in man pages, `ftruncate64` is a synonym to `ftruncate`.
Until it is properly added, you may use the `ftruncate` hook like this:

```python
from qiling.os.posix.syscall.unistd import ql_syscall_ftruncate

# ... init Qiling instance here but do not run yet

ql.os.set_syscall('ftruncate64', ql_syscall_ftruncate)
```

If you are emulating a 32-bits architecture, such as MIPS O32, the 64 bits value is split into two arguments. Usually glibc will take care of it, but in case it doesn't you would need to write a small shim to work around that:

```python
def __ftruncate64_shim(ql: Qiling, fd: int, length_lo: int, length_hi: int):
    return ql_syscall_ftruncate(ql, fd, (length_hi << 32) | length_lo))

ql.os.set_syscall('ftruncate64', __ftruncate64_shim)
```
Let me know if that helps.

**Comment by SRSG** [comment]
Thanks for your help and it works.
