### ISSUE TITLE
socket() returns -1 due to unimplement AF_BLUETOOTH

### ISSUE THREAD

**Issue by SRSG** [qilingframework/qiling#1342]
When I emulated a webs program, I got a socket error that returns -1.This caused the program to exit.
```
[=] 	close(fd = 0x4) = 0x0
[=] 	socket(domain = 0x10, socktype = 0x3, protocol = 0x1f) = -0x1 (EPERM)
[=] 	exit_group(code = 0xffffffff) = ?
```
This call is `socket(16, 3, 31)`.Then I checked the file `/usr/include/x86_64-linux-gnu/bits/socket.h` to get these :
```
#define AF_BLUETOOTH	PF_BLUETOOTH
#define PF_BLUETOOTH	31	/* Bluetooth sockets.  */
```
Also I find that qiling's socket.py only has `AF_UNIX, AF_INET, AF_INET6`.Do you have a plan to perfect qiling' socket or implement the `AF_BLUETOOTH`?

**Comment by elicn** [comment]
That could be a future fix.
As of now, there is no plan to implement this.
