### ISSUE TITLE
Invalid instruction when emulation arm version libcrypto.so.1.1

### ISSUE THREAD

**Issue by HclX** [qilingframework/qiling#1343]
***Describe the bug**

Emulation fails with the following message:
```
[x]     Hexdump:
[x]     00 0e a0 f2 1e ff 2f e1
[x]     Disassembly:
[x]     PC = 0x9026b188

[x]     Memory map:
```

After checking this is inside of an arm version of libcrypto.so.1.1 file, here is the disassembled bytes in ghidra:
```
         *************************************************************
         *                           FUNCTION                         
         *************************************************************
         undefined  FUN_00062188 ()
             undefined         r0:1           <RETURN>
            FUN_00062188                  XREF[1]:     entry:0005d184 (c)   
        00062188 00  0e  a0  f2      vmull.p64  q0 ,d0 ,d0   <========== HERE
        0006218c 1e  ff  2f  e1      bx         lr
        00062190 68               ??         68h    h
```

**Comment by elicn** [comment]
While Unicorn supports several CPUs of each architecture, Qiling does not specify which one it should use, so Unicorn picks up the default one. Most chances that this specific instruction (part of ARM Neon SIMD instructions) is not supported by that default CPU. We are planning on making that (choosing a specific CPU) a configurable setting.

**Comment by HclX** [comment]
Any idea to get around this issue before the feature is available?

**Comment by elicn** [comment]
Sorry for missing this for a long time..
The CPU selection feature has already been integrated into `dev` branch a while ago: see #1376
I am tentatively closing this, do not hesitate to re-open if the problem remains.
