### ISSUE TITLE
Qiling.hook_address() signature changed

### ISSUE THREAD

**Issue by jeffli678** [qilingframework/qiling#137]
In the second example of the readme, there is one line of code:
```
ql.hook_address(0x00401016, force_call_dialog_func)
```
I tried to run it but it fail. I troubleshooted it and found the correct code should be:
```
ql.hook_address(force_call_dialog_func, 0x00401016)
```
And it then runs without any problem. You would better either change the function signature or update the readme. 

However, I have to say the readme version is better and the one in the actual code is less intuitive.

**Comment by aquynh** [comment]
Please make a pull req

**Comment by jeffli678** [comment]
> Please make a pull req

Please have a look at #138

**Comment by xwings** [comment]
merge and close
