### ISSUE TITLE
memory module function called map_anywhere return zero

### ISSUE THREAD

**Issue by helloobaby** [qilingframework/qiling#1372]
```
ql = Qiling([r'rootfs/x86_windows/a690000.dll'], rootfs=r"rootfs/x86_windows",verbose=QL_VERBOSE.DEFAULT)
arg1 = ql.mem.map_anywhere(4096)
assert(arg1) # arg1 is zero
```

Why does this happen?

**Comment by wtdcode** [comment]
https://github.com/qilingframework/qiling/blob/9a78d186c97d6ff42d7df31155dda2cd9e1a7fe3/qiling/os/memory.py#L529

`map_anywhere` searches available free segments from the lowest possible address, in most cases, 0.

**Comment by helloobaby** [comment]
Function failure returns None instead of 0
