### ISSUE TITLE
credit reversing.kr for the crackmes

### ISSUE THREAD

**Issue by jeffli678** [qilingframework/qiling#139]
So I was wondering why those examples are all familiar to me. Turns out they are mostly from reversing.kr and I have solved them previously. I think it would be better to credit reversing.kr for these crackmes. If there is no problem with this, I will create it a pull request.

**Comment by xwings** [comment]
sure. please make a pull request.

thanks !

**Comment by xwings** [comment]
Close, since more than 60 days no response
