### ISSUE TITLE
Invalid name in restore function

### ISSUE THREAD

**Issue by Satsuoni** [qilingframework/qiling#1393]
***Describe the bug**
The snapshot "save" and "restore" functions use different names for "os".  ("os" and "os_context")
See this [line](https://github.com/qilingframework/qiling/blob/9b37c3b5cd85164404bf278a4404cc5eb9204970/qiling/core.py#L698) vs [this one](https://github.com/qilingframework/qiling/blob/9b37c3b5cd85164404bf278a4404cc5eb9204970/qiling/core.py#L653). 
**Sample Code**
```python
count=[0]
def trace_cb(ql: Qiling, address: int, size: int, count):
  ql.save(reg=True, mem=True, hw=False, fd=False, cpu_context=True, os=True, loader=True,snapshot="savestate")
ql = Qiling(["x86_windows/test.exe"], "x86_windows")
ql.hook_code(trace_cb, count)
ql.run()
```

Then, after crash
```python
ql = Qiling(["x86_windows/test.exe"], "x86_windows")
ql.restore("savestate")
ql.run(begin=ql.arch.regs.eip)
```

**Expected behavior**
"restore" loads os heap data.

**Additional context**
I had to add heap saving to windows to avoid "memory not available" errors when running restored emulation.
```python
    def save(self) :
        ret={}
        ret["heap"]=self.heap.save()
        return ret

    def restore(self, saved_state):
        if "heap" in saved_state:
          self.heap.restore(saved_state["heap"])
```

**Comment by elicn** [comment]
I fixed the inconsistency in #1390 (pending).
As for the heap save and restore, all OS subclasses need to implement save and restore on their own. That worth a separated issue.
