### ISSUE TITLE
Code style for qiling

### ISSUE THREAD

**Issue by 0ssigeno** [qilingframework/qiling#143]
Is not  important as all the other issues, but my editor is giving me a hard time because the project doesn't follow the pep8 style guide.
Can I reformat the project to pep8 or do you use another style guide that I can follow?

**Comment by xwings** [comment]
YES and YES and YES.

There are some part we did not follow strictly(due to our lamelyness). your help is needed and very much appreciated.

**Comment by xwings** [comment]
btw, we got gitter.im chatroom, please join us !

**Comment by xwings** [comment]
Windows and Core is more or less done, we need to refactor rest of the code.

**Comment by xwings** [comment]
close for now. since we are always refactoring.
