### ISSUE TITLE
MapViewOfFile should map entire file if dwNumberOfBytesToMap is zero

### ISSUE THREAD

**Issue by russdill** [qilingframework/qiling#1430]
MapViewOfFile currently maps none of the file if dwNumberOfBytesToMap is zero. This causes neolite compressed binaries to fail decompression. See:

https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffile

> [in] dwNumberOfBytesToMap
> 
> The number of bytes of a file mapping to map to the view. All bytes must be within the maximum size specified by [CreateFileMapping](https://learn.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createfilemappinga). If this parameter is 0 (zero), the mapping extends from the specified offset to the end of the file mapping.

**Comment by elicn** [comment]
Should be fixed now. Please let us know if the problem persists.
