### ISSUE TITLE
Generic printf function does not implement microsoft specifiers 

### ISSUE THREAD

**Issue by kbsec** [qilingframework/qiling#1433]
***Describe the bug**
The implementation of printf/wprintf has incorrect behavior when used for windows. 
see documentation here: 
https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170

If I have time in the next few weeks, I'll submit a pr :) 
**Sample Code**
```c
#include <windows.h>
#include <stdio.h> 

# define W 

int main(){
  // https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170
  // The windows implementation of printf/wprintf 
  // type field characters does not confirm to ISO C stanards 
  // In particular, the behavior of %s/%S is differnt depending on 
  // on wether printf/wprintf is called 
  #ifdef W
  wprintf(L"I am a C string %s\n", "hello world!");
  wprintf(L"I amd a Wide C string %s\n", L"hello world!");
  #else 
  printf("I am a C string %s\n", "hello world!");
  printf("I amd a Wide C string %S\n", L"hello world!");
  #endif 

}
```
```bash
 x86_64-w64-mingw32-gcc windows_printf.c -DW -o wprintf.exe
 x86_64-w64-mingw32-gcc windows_printf.c  -o printf.exe
```

**Expected behavior**
wine64  wprintf.exe 
I am a C string hello world!
I amd a Wide C string h

wine64 printf.exe 
I am a C string hello world!
I amd a Wide C string hello world!

**Screenshots**
![image](![image](https://github.com/qilingframework/qiling/assets/11823496/06461e4e-d148-498c-a266-e9645b8ef509))

**Additional context**

**Comment by kbsec** [comment]
Looks like y'all are aware:
https://github.com/qilingframework/qiling/blob/9a78d186c97d6ff42d7df31155dda2cd9e1a7fe3/qiling/os/utils.py#L129-L142

```cmd
PS C:\vagrant> .\printf.exe
I am a C string hello world!
I amd a Wide C string hello world!
PS C:\vagrant> .\wprintf.exe
I am a C string hello world!
I amd a Wide C string h
PS C:\vagrant> 
```

```bash
./qltool run --verbose off  --rootfs rootfs/x8664_windows -f rootfs/x8664_windows/bin/wprintf.exe
./qltool run --verbose off  --rootfs rootfs/x8664_windows -f rootfs/x8664_windows/bin/printf.exe
```
both of these lead to issues with strings being misinterpreted 
one work around for now is to hook wprintf and swap %s-->%ls and %S --> %s and then call printf

**Comment by elicn** [comment]
The link you provided for the screenshot circles back to this issue, so we can't see it the problem. If this is about handling `%S` as wide strings, that should be an easy fix.

**Comment by kbsec** [comment]
Ah my fault:
![image](https://github.com/qilingframework/qiling/assets/11823496/ffe2ece4-681e-426b-82a8-00fbd79d7aac)

it is  just for handling %s vs %S for wprintf :)

**Comment by elicn** [comment]
Should be fixed now. Please let us know if the problem persists.
