### ISSUE TITLE
hook_HeapAlloc does not respect HEAP_ZERO_MEMORY

### ISSUE THREAD

**Issue by russdill** [qilingframework/qiling#1436]
HeapAlloc isn't zero'ing memory from the heap before returning it when the HEAP_ZERO_MEMORY flag is passed.

https://learn.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapalloc

> HEAP_ZERO_MEMORY 0x00000008 The allocated memory will be initialized to zero. Otherwise, the memory is not initialized to zero.

**Comment by elicn** [comment]
Should be fixed now. Please let us know if the problem persists.
