### ISSUE TITLE
IDAPythonStdOut logging device error when setting up in IDA pro

### ISSUE THREAD

**Issue by pmondon** [qilingframework/qiling#1494]
***Describe the bug**
IDA pluging thows an error when trying to start emulation

**Sample Code**
  File "/home/user/ida/plugins/qilingida.py", line 1037, in ql_start
    self.qlemu.start()
  File "/home/user/ida/plugins/qilingida.py", line 889, in start
    self.ql = Qiling(argv=self.path, rootfs=self.rootfs, verbose=QL_VERBOSE.DEBUG, env=self.env, log_plain=True, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/qiling/core.py", line 169, in __init__
    self._log_file_fd = setup_logger(self, log_devices, log_plain, log_override)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/qiling/log.py", line 199, in setup_logger
    raise TypeError(f'unexpected logging device type: {type(dev).__name__}')
TypeError: unexpected logging device type: IDAPythonStdOut

**Comment by 0x410c** [comment]
same

**Comment by elicn** [comment]
There's already a PR pending today fix this, but currently Qiling breaks on the new Unicorn release. Please allow a few days for the fixes.
