### ISSUE TITLE
UC_ERR_ARG when attempting to write to c1_c0_2 arm register

### ISSUE THREAD

**Issue by wr3nchsr** [qilingframework/qiling#1510]
**Describe the bug**
The `c1_c0_2` register in arm raises an `Invalid argument (UC_ERR_ARG)` error when writing to it. 
*This was tested with qiling version 1.4.6 and unicorn version 2.1.1*

**Sample Code**
Run the example `hello_arm_linux_debug.py` or the following code:
```python
ql = Qiling(code=bytes(1000), archtype=QL_ARCH.ARM, ostype=QL_OS.LINUX)
```
This will call the `enable_vfp` function from `QlArchARM` which will attempt to write to `c1_c0_2` and raise the error.

**Screenshots**
<img width="1118" alt="Screenshot 2024-11-14 at 12 02 55 PM" src="https://github.com/user-attachments/assets/7306ed09-b23e-4914-8690-4c455f26044d">

**Additional context**
This is caused because of [this unicorn commit](https://github.com/unicorn-engine/unicorn/commit/4055a5ab109c1d8d2da06515f3e117ca57faf179#diff-e041ac9c63925383ab2c6112647b9dcdd48ef34024c8170d4090dd5ecbfbc8a3L327) which changed the default return value of `reg_write` function from `UC_ERR_OK` to `UC_ERR_ARG`.
<img width="1469" alt="Screenshot 2024-11-14 at 11 39 58 AM" src="https://github.com/user-attachments/assets/ee0a80ae-ce60-42d5-af15-2e782659f000">

Furthermore, the switch case handling register `UC_ARM_REG_C1_C0_2` in the `reg_write` function is commented out as shown [here](https://github.com/unicorn-engine/unicorn/blob/master/qemu/target/arm/unicorn_arm.c#L437) which causes the function to return the default return value.
<img width="652" alt="Screenshot 2024-11-14 at 11 55 33 AM" src="https://github.com/user-attachments/assets/a5ec3b06-bc5d-4b1a-ad88-ca3896175e32">

and the register `UC_ARM_REG_C1_C0_2` is commented as depreciated and should be replaced with `UC_ARM_REG_CP_REG` [here](https://github.com/unicorn-engine/unicorn/blob/master/include/unicorn/arm.h#L185).

**Comment by elicn** [comment]
Unicorn upgrade to version 2.1.1 broke Qiling which has not adapted yet, however that is to be resolved soon. Currently there are three options to work around this:
1. Wait for Qiling to catch up with latest Unicorn changes
2. Apply pending changes in Qiling (#1499) and adjust your code accordingly. That is, using the newly introduced methods `ql.arch.cpr.read` and `ql.arch.cpr.write` (see commit https://github.com/qilingframework/qiling/pull/1499/commits/3c5ff2d097b874cac51bb2c417c992c70c95d7d7 for examples of how to use it)
3. Revert Unicorn to version 2.0.1

**Comment by elicn** [comment]
Qiling has reverted Unicorn dependency to 2.0.1
