### ISSUE TITLE
hook_MapViewOfFile throwing exception while emulating windows binary

### ISSUE THREAD

**Issue by chintanhshah** [qilingframework/qiling#1515]
***Describe the bug**
I am trying to emulate one of the windows binary that calls Kernerl32!MapViewOfFile. I see that there is a hook already implemented in os/windows/dlls/kernel32/fileapi.py. 
![image](https://github.com/user-attachments/assets/86058eb3-6a1c-4db6-b70d-e6ec12722972)

While emulating the PE , it throws an exception and come out . 
![image](https://github.com/user-attachments/assets/e9b2c170-cec9-4819-9217-003483212e45)

**Sample Code**
```python
ql = Qiling(["x8664_freebsd/bin/x8664_hello_asm"], "x8664_freebsd", output = "dump")
ql.run()
```

**Expected behavior**
Error thrown is at line 602 within fileapi.py..It should return the new address of where the file is mapped in the memory. 

**Screenshots**

**Additional context**

**Comment by elicn** [comment]
Hi there,
It looks like you are using an outdated version of Qiling; this code has changed about 10 months ago (here: https://github.com/elicn/qiling/commit/0e7927015dbe0ae73520422a72a03d7ebbcbb6a4). Recommending to checkout `dev` branch and use it instead. If you experience issues when working with the `dev` branch, let us know on TG.
