### ISSUE TITLE
Windows API Implementation: (Find/Load)Resource

### ISSUE THREAD

**Issue by xwings** [qilingframework/qiling#163]
From: @0ssigeno 

Still having an error with sample DHL_FORMAT.
Another sample that I'm testing is 
[emotet_1.zip](https://github.com/qilingframework/qiling/files/4355919/emotet_1.zip), but having problem with a real implementation of (Find/Load)Resource.
Help is welcomed

**Comment by learn-more** [comment]
Most of the kernel32 resource functions are wrapper for the ntdll `Ldr*Resource*` functions,
and those mostly operate on mapped files (that should be available when running in qiling).

If the imports from kernel32->ntdll would be fixed, then the native functions would probably work most of the time.

What would be the preferred way?:
* Using the native kernel32/ntdll functions
* Writing a python implementation

**Comment by xwings** [comment]
We are thinking some way to fix the kernel dll issue. I guess this will be another issue.
