### ISSUE TITLE
Sample crash with PC = 0x0

### ISSUE THREAD

**Issue by 0ssigeno** [qilingframework/qiling#171]
This sample crashes with PC = 0. I'm not having luck to find the exact reason for that, so any help is appreaciated.
[gotkit2.zip](https://github.com/qilingframework/qiling/files/4374895/gotkit2.zip)
The sample was found on any.run.

**Comment by ucgJhe** [comment]
this sample try to call function from a decoded null function pointer, thats why you get a null pointer dereference after TlsGetValue

![image](https://user-images.githubusercontent.com/10076774/77525154-8955c880-6ec3-11ea-919c-ca0e3dfb2c8a.png)

**Comment by 0ssigeno** [comment]
But at the same time the sample works [any.run](https://app.any.run/tasks/c2c31ef1-45af-416c-aabe-51a0d48c5e43/) works. You think is an external problem?

**Comment by ucgJhe** [comment]
after debugging, I found the control flow of this sample is different from running on qiling. and its working in my windows box, may need more reversing work to tell what happend.

**Comment by xwings** [comment]
@ucgJhe thanks for the help. appreciate it. Looking forward for the answer !

**Comment by ucgJhe** [comment]
I would say put this off, maybe try another simpler malware for testing , since the gdbserver of qiling is not yet supported PE executable.

**Comment by xwings** [comment]
it should. have u tried ?

**Comment by ucgJhe** [comment]
I tried and it failed bcuz this
![image](https://user-images.githubusercontent.com/10076774/77626454-57ef0280-6f80-11ea-8c05-e70a00082939.png)

**Comment by xwings** [comment]
Should work now

**Comment by xwings** [comment]
I guess we solved this ?
