### ISSUE TITLE
ARM32 Big Endian Issue

### ISSUE THREAD

**Issue by xwings** [qilingframework/qiling#173]
We got the basic setup for ARM EB and somehow the ARM and THUMB switching is not working.

**Comment by xwings** [comment]
It seems like when we pass in ARM Big Endian ELF, with  
```
Uc(UC_ARCH_ARM, UC_MODE_ARM + UC_MODE_BIG_ENDIAN) 
```
it will screw up the ARM and Thumb mode

as of now i leave it to 
```
 Uc(UC_ARCH_ARM, UC_MODE_ARM)
```

We must check the Unicorn core now.

**Comment by elicn** [comment]
@xwings 
I guess this has something to do with unicorn-engine/unicorn#1542, which should have been fixed by now.
Can you confirm?
