### ISSUE TITLE
dprint usage and verbose

### ISSUE THREAD

**Issue by xwings** [qilingframework/qiling#174]
We had a chat in gitter and lets do some planning here.

- 0: not print anything, except exception
- 1: only nprint this will be pretty much strace in linux
- 2: disassemble output
- 3: ql.print with level 0

level will be defined during 
```
ql.dprint(0, "some msg %s %i"  % (str1, int2))
```

so, i added verbose option, by default verbose is 0 and verbose only can use with 
```
ql.output in (QL_OUT_DEBUG, QL_OUT_DUMP)
```

example, says we need to set verbose to 1
```
def stopatkillerswtich(ql):
    print("killerswtch found")
    ql.uc.emu_stop()

if __name__ == "__main__":
    ql = Qiling(["rootfs/x86_windows/bin/wannacry.bin"], "rootfs/x86_windows", output = "debug", verbose = 1)
    ql.hook_address(stopatkillerswtich, 0x40819a)
    ql.run()
```

any comments?

**Comment by 0ssigeno** [comment]
Agree on the verbosity, can be useful to separate jobs. Otherwise we will have the console full of output that is hard to decode.

**Comment by xwings** [comment]
the thing i am not sure is dprint or add a vprint

**Comment by xwings** [comment]
Pushed and its official now
