### ISSUE TITLE
Netgear R7000 emulation - Invalid memory read (UC_ERR_READ_UNMAPPED)

### ISSUE THREAD

**Issue by 0xd3xt3r** [qilingframework/qiling#175]
I have error running Netgear R7000 firmware 
binary /opt/rcagent/cgi_processor

you can download the firmware from here [link](https://drivers.softpedia.com/get/Router-Switch-Access-Point/NETGEAR/NETGEAR-R7000-Router-Firmware-1-0-10-90.shtml)

file : `ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-, stripped`

I am using latest code
I was able to run the same binary on qemu-arm and it was work properly.
I can help fixing the bug if get appropriate guidance
```
ioctl(0x0, 0x5401, 0xfff2da24) = 0
ioctl(0x1, 0x5401, 0xfff2da24) = 0
brk(0x0)
brk(0x94000)
getpid() = 1298
ugetrlimit(3, 0xfff2da70) = 0
setrlimit(3, 0xfff2da70) = 0
rt_sigaction(0x20, 0xfff2da34, = 0x0) = 0
rt_sigaction(0x21, 0xfff2da34, = 0x0) = 0
rt_sigaction(0x22, 0xfff2da34, = 0x0) = 0
rt_sigprocmask(0x0, 0xfff2da78, 0x0, 0x8) = 0
rt_sigprocmask(0x1, 0xfff2da78, 0x0, 0x8) = 0

[+] Start      End        Perm.  Path
[+] 00008000 - 00093000 - r-x    /netgear_r7000/_R7000-V1.0.10.90_10.2.90.chk.extracted/squashfs-root/opt/rcagent/cgi_processor
[+] f7be7000 - f7bef000 - rw-    [mapped]
[+] f7bef000 - f7bf4000 - rw-    /netgear_r7000/_R7000-V1.0.10.90_10.2.90.chk.extracted/squashfs-root/usr/lib/libnvram.so
[+] f7c0a000 - f7c11000 - rw-    [mapped]
[+] f7c11000 - f7c17000 - r--    /netgear_r7000/_R7000-V1.0.10.90_10.2.90.chk.extracted/squashfs-root/lib/libpthread.so.0
[+] f7c1b000 - f7c22000 - rw-    [mapped]
[+] f7cbe000 - f7cc6000 - rw-    [mapped]
[+] f7cc6000 - f7ccb000 - r--    /netgear_r7000/_R7000-V1.0.10.90_10.2.90.chk.extracted/squashfs-root/usr/lib/libstdc++.so.6
[+] f7ce1000 - f7ce9000 - rw-    [mapped]
[+] f7cf6000 - f7cfd000 - rw-    [mapped]
[+] f7d64000 - f7d6c000 - rw-    [mapped]
[+] f7d6c000 - f7d6e000 - r--    /netgear_r7000/_R7000-V1.0.10.90_10.2.90.chk.extracted/squashfs-root/lib/libc.so.0
[+] f7d6e000 - f7d73000 - rw-    [mapped]
[+] fb7d3000 - fb7e1000 - r--    /lib/ld-uClibc.so.0
[+] fff2dee0 - fff2e000 - rw-    [stack]
0xe3d8 0x8fffffff
Traceback (most recent call last):
  File "./qltool", line 236, in <module>
    ql.run()
  File "/home/d3xt3r/oss/qiling/qiling/core.py", line 245, in run
    runner(self)
  File "/home/d3xt3r/oss/qiling/qiling/os/linux/arm.py", line 291, in runner
    ql.uc.emu_start(ql.elf_entry, ql.until_addr, ql.timeout) 
  File "/home/d3xt3r/.pyenv/versions/3.6.9/lib/python3.6/site-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)
```

**Comment by xwings** [comment]
u can turn on debug and take a look. could me some mem map need to be changed. if this is the case, we need a better memory management tool.

**Comment by 0xd3xt3r** [comment]
I have attached the more verbose logs.

[debug.txt](https://github.com/qilingframework/qiling/files/4396670/debug.txt)

**Comment by xwings** [comment]
I guess we need a proper memory management.

**Comment by 0xd3xt3r** [comment]
any idea on what should be done. If you give me some direction I can start working on it. I didn't get what the bug is!!!

**Comment by xwings** [comment]
Need to test and find out what is the issue, but it seems like a mem issue. need to test it for sure.

**Comment by 0xd3xt3r** [comment]
ok i will try to work on it if have some spare time meanwhile if you find out what it is post it here.

**Comment by xwings** [comment]
Hi, 

I just replied in in issue #223  on it seems like netgear firmware left lots of non working link, you need to fix the link before able to make it work.

**Comment by xwings** [comment]
close due to no response after 30 days.
