### ISSUE TITLE
logging printout issue

### ISSUE THREAD

**Issue by xwings** [qilingframework/qiling#188]
Either:

```
from qiling import *

def run_sandbox(path, rootfs, output):
    ql = Qiling(path, rootfs, output = output)
    ql.log_console = False
    ql.run()


if __name__ == "__main__":
    run_sandbox(["rootfs/arm_linux/bin/arm_hello"], "rootfs/arm_linux", "debug")
```

or 

```
python3 ../qltool run  -f rootfs/x86_linux/bin/x86_multithreading --rootfs rootfs/x86_linux/ --console False
```

still print to console

**Comment by xwings** [comment]
@ucgJhe will you be able to help ?

**Comment by ucgJhe** [comment]
a bit confused here. by log_console means should be log console output to disk file ?

**Comment by xwings** [comment]
log_console means print in stdio. 

we can define log_console  = False, which print nothing to console but still print --debug --dump or anything to even normal nprint to file.

if you think log_console is a bad name, i feel free to change it

**Comment by xwings** [comment]
Hi @ucgJhe  got abit more issue so i renamed it to nprint and dprint issue

When i enabled dump seems like the print got no new lines. 

```
[+] Loading ./Windows/SysWOW64/kernel32.dll to 0x10000000[+] Done with loading ./Windows/SysWOW64/kernel32.dll[+] Loading ./Windows/SysWOW64/user32.dll to 0x100d4000[+] Done with loading ./Windows/SysWOW64/user32.dll[+] Loading ./Windows/SysWOW64/gdi32.dll to 0x1019d000[+] Done with loading ./Windows/SysWOW64/gdi32.dll[+] Loading ./Windows/SysWOW64/advapi32.dll to 0x101be000[+] Done with loading ./Windows/SysWOW64/advapi32.dll[+] Loading ./Windows/SysWOW64/shell32.dll to 0x1025f000[+] Done with loading ./Windows/SysWOW64/shell32.dll[+] Loading ./Windows/SysWOW64/ole32.dll to 0x107d9000[+] Done with loading ./Windows/SysWOW64/ole32.dll[+] Loading ./Windows/SysWOW64/mpr.dll to 0x10935000[+] Done with loading ./Windows/SysWOW64/mpr.dll[+] Loading ./Windows/SysWOW64/wininet.dll to 0x10947000[+] Done with loading ./Windows/SysWOW64/wininet.dll[+] Loading ./Windows/SysWOW64/rpcrt4.dll to 0x10a3c000[+] Done with loading ./Windows/SysWOW64/rpcrt4.dll[+] Done with loading bin/GandCrab502.bin[+] Tracing basic block at 0x4062f8
```

**Comment by xwings** [comment]
It really seems like, the print machnism is not right, my idea was.  dprint should be checking verbose and everything should forward to nprint.

**Comment by xwings** [comment]
ok, i solved most of it. lets reopen if we have issue

**Comment by xwings** [comment]
Left one issue

```
python3 ../qltool run  -f rootfs/x8664_linux/bin/x8664_hello --rootfs rootfs/x8664_linux/ --console False --log_dir qlogs --debug
```

in this case, we should

1. no console printout
2. since we still have --log_dir qlogs --debug it still still write to qlogs

**Comment by ucgJhe** [comment]
let me get this straight no console printout but keeping syscall invocation like nprint, right ?

**Comment by xwings** [comment]
zero print. only log

**Comment by ucgJhe** [comment]
like output=off ?

**Comment by xwings** [comment]
yes sir

**Comment by ucgJhe** [comment]
check #189

**Comment by xwings** [comment]
thank you and problem solved. check my commit on how we do the logger and i add in print into endprint.
