### ISSUE TITLE
Question/Consult: Emulation of LOLBAS

### ISSUE THREAD

**Issue by dfirence** [qilingframework/qiling#203]
Greetings, I love your project and am researching it before I install it.

This is a question only:

Can qiling allow for emulation of the Windows Terminals/Consoles apps interactively?

Specifically - CMD.EXE, POWERSHELL.EXE

I want to learn how the programs work using Binee.

Other examples I need to run are networking utilities: PING.EXE, ROUTE.EXE

**Comment by xwings** [comment]
Hi,

You can always follow the guild to install and get all the required dll from [https://github.com/qilingframework/qiling/blob/master/docs/SETUP.md](url)

then u can run cmd.exe , powershell.exe, ping.exe and route.exe from qltool.

Very high chances some required API is missing, feel free to fill it in !

**Comment by xwings** [comment]
Close due to no response after 30 days.
