### ISSUE TITLE
Add AT_SECURE auxiliary vector for Android native binaries

### ISSUE THREAD

**Issue by justfoxing** [qilingframework/qiling#231]
I've been messing around with running Android native binaries in Qiling. I've had to tweak some syscalls a little, but thanks to your API that's been super easy to work with :D

However, I did run into one place where I needed to modify Qiling code - currently, as bionic libc initializes in an Android binary, it checks for the existence of AT_SECURE in the auxiliary vectors, and errors out if it's not present (https://cs.android.com/android/platform/superproject/+/master:bionic/libc/bionic/libc_init_common.cpp;bpv=1;bpt=1;l=303?q=AT_SECURE).

I managed to work around this by adding `elf_table += self.NEW_AUX_ENT(AT_SECURE, 0, ql)` immediately before `elf_table += self.NEW_AUX_ENT(AT_NULL, 0, ql)` in qiling/loader/elf.py. Any chance you could add this, or expose a flag to allow users to specify if they want AT_SECURE?

Cheers!

**Comment by xwings** [comment]
hi,

will you be able to make a pull request and we work it out from there ?

**Comment by justfoxing** [comment]
Sure, just added one.

**Comment by xwings** [comment]
thanks. will wait for your sample test and we are good to go
