### ISSUE TITLE
Usage of fcntl on windows

### ISSUE THREAD

**Issue by klks** [qilingframework/qiling#24]
Python does not have a fcntl equivalent on windows. This will prevent Qiling from running on Windows OS. qiling.os.posix.filestruct relies on fnctl for ioctl method in the ql_file, ql_socket, and ql_pipe classes.

**Comment by xwings** [comment]
Move issue #33 and #51  here.

As of now we can confirmed  Windows can run Qiling with PE only. That is for .travis.yml 
So we can use Travis-CI Windows DLL to test our Qiling's Windows code.

As for fcntl, no too sure yet, maybe we will leave this case open until we see hope.

**Comment by xwings** [comment]
Close for now. Issue is mention in #333
