### ISSUE TITLE
python os module got overrided

### ISSUE THREAD

**Issue by cq674350529** [qilingframework/qiling#241]
When running `qiling` framework in latest `dev` branch, it seems that the python os module got overrided by the `qiling.os` module.

``` python
In [1]: import os                                                                                                                                  

In [2]: from qiling import *                                                                                                                       

In [3]: os.path.exists("hello")                                                                                                                    
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-d7feed055d28> in <module>
----> 1 os.path.exists("hello")

AttributeError: module 'qiling.os' has no attribute 'path'
```
Of course, we can use `import os as pyos` or change the import order to avoid this. But maybe it's better to change it in `qiling` framework iterself. The `master` branch doesn't suffer from this issue.

**Comment by xwings** [comment]
Hi,

You are right. I guess when we do do the refactor we mess up some of the import.

should be fix by now. https://github.com/qilingframework/qiling/commit/151f6af2929f15bb3c2a856250af408949f57c96

**Comment by cq674350529** [comment]
Yeah, it works. Thanks!
