### ISSUE TITLE
Question) print instructions of target functions

### ISSUE THREAD

**Issue by joon5283** [qilingframework/qiling#252]
Hello.

Thank you for providing such a great tool! I am currently studying Qiling for fun.

I am trying to print out instructions of the target function. 

For example, I have a small program such as 'hello world' and I want to print out instructions that are only included in main function. For my understanding, there is only one basic block and small number of instructions in the main function. So, in this case, I want to print out those small number of instructions. Could you explain the way to do this?

Thanks for your help and for giving me advice.

**Comment by aquynh** [comment]
Actually you dont need to do much: just run "qtool.py", with output set to "disasm"

You can also find some similar examples under examples/, with similar "disasm" option.

**Comment by aquynh** [comment]
Alternatively, you can customize your callback with "hook_code" method. Find some examples in examples/

**Comment by joon5283** [comment]
Thanks for the quick reply. For "disasm" option, it looks like it prints out every executed instruction. Am I correct? Because when I execute 'hello world' program with disasm option, it prints out thousands of instructions. But, in my case, I want to print out only instructions included in main function. 
Hence, do I have to customize a callback function to implement such printing tools?

**Comment by aquynh** [comment]
Yes, it prints every instructions. So you should write your own callback, and use Capstone to decode.

**Comment by joon5283** [comment]
Got it! So, I have to study Capstone first.

Thanks for your advice!

**Comment by aquynh** [comment]
Have fun, and dont forget to star us ;-)
