### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by XVilka** [qilingframework/qiling#253]
Python is a poor choice for anything remotely complex, especially that affects the execution times like emulation. Projects like Angr and Miasm met a bottleneck of Python, it's slowness, GIL, memory hunger, and poor parallelism. On the other hand, reimplementing most of the code in Rust will still allow to provide Python interface, see [Rust-Python example](https://github.com/rochacbruno/rust-python-example).

**Comment by xwings** [comment]
Hi,

You are right. I am not too sure about Angr but we are definitely more complex then miasm. 

So, if someone can start to implement Rust-Python in QIling. We will be really happy.

**Comment by ttimasdf** [comment]
In fact @xwings has answered this [in a Podcast](https://infoseccampus.com/sectools-e19-kaijern/), basically

1. friendly for developers and new coming contributors
2. code base could be a good learning material (especially for students who want to learn OS internals)
3. just enough libraries to base on (unicorn engine, etc)

**Comment by XVilka** [comment]
Miasm folks are rewriting it in Rust too, by the way.

**Comment by xwings** [comment]
i am pretty sure is a good idea. but do we need it or not now will be the questions.

i am not familiar with MIASM. so, i cannot comment.

**Comment by gogo2464** [comment]
I like this idea. But it seems to requiere a lot of work.

@XVilka I read your link about Rust-Python. It is about to make rust libraries for python. It is nice for people who will need to import our project in python but can we import python in rust to avoid to recode everything?

**Comment by gogo2464** [comment]
@XVilka Your link https://github.com/rochacbruno/rust-python-example might be deprecated. See https://users.rust-lang.org/t/try-keyword-reservation-breaks-macro-try/23398 and https://github.com/rochacbruno/rust-python-example/issues/21

**Comment by gogo2464** [comment]
@xwings I do not understand why you closed this issue. We think rust is a good choice and all has not been replaced.

**Comment by ucgJhe** [comment]
i think re-write with unicorn rust binding will be a good idea, but it seems deprecated.

**Comment by 0xchase** [comment]
Has there been any progress on this issue? I'd like to contribute to this if possible. This is a big task though, and I don't think it will happen unless we can get a few core people to divide up the work and contribute consistently. Is anyone actively working on this? Or is anyone interested in working on this?

**Comment by gogo2464** [comment]
@0xchase I noticed that I could make a rust library and import it in python [see here](https://github.com/rochacbruno/rust-python-example#importing-from-python-and-comparing-the-results) because it is easier than import python in rust.


I did not do more yet.

**Comment by gogo2464** [comment]
Const is a rust keyword. I can not create a const crate instead of [this](https://github.com/qilingframework/qiling/blob/master/qiling/const.py). Do I open an issue to rename this file in order to replace it with a crate?

**Comment by xwings** [comment]
reopened.

**Comment by edsky** [comment]
I wrote a similar implementation in rust. **Only realized loading windows pe.**
Lack of gdtr implementation, tls implementation and api hook.
It used to be when a private project was implemented, and I saw people have similar ideas, so I will make it public here, and will continue to update.

https://github.com/edsky/muhe

**Comment by gogo2464** [comment]
I just found a tool to translate c code to rust https://c2rust.com/ I am looking for a similar program from python to rust. It does not do everything but could help a lot.

**Comment by gogo2464** [comment]
DONE! This tools may help very much : https://github.com/konchunas/pyrs !

**Comment by gogo2464** [comment]
Assign me to this issue immediately :)

**Comment by 0xchase** [comment]
@gogo2464 I can guarantee the automatic transpile will be more difficult than rewriting it from scratch and probably won't work at all

**Comment by xwings** [comment]
Yup. I agree.

**Comment by xwings** [comment]
Close for now. Did not see light at the end of tunnel.
