### ISSUE TITLE
Does the qltool support efi files? I saw a tweet saying it does but when I run it it doesn’t work. 

### ISSUE THREAD

**Issue by kocoman1** [qilingframework/qiling#270]

**Comment by xwings** [comment]
its in PR and waiting for @liba2k touchup and we are good !

**Comment by xwings** [comment]
we got EFI now !

**Comment by kocoman1** [comment]
I tried the latest git but still same error as before.  No idea whats wrong.  Need update unicorn? thanks

vv@iMac qiling % ./qltool run --rootfs /Users/vv/Desktop/shareubuntu/examples/rootfs/x8664_windows  -f /Users/vv/Desktop/shareubuntu/bdmesg.efi 
[+] Loading /Users/vv/Desktop/shareubuntu/bdmesg.efi to 0x0
[+] PE entry point at 0x2d92
[+] Initiate stack address at 0x7ffffffde000 
[+] TEB addr is 0x6030
[+] PEB addr is 0x60b8
Traceback (most recent call last):
  File "./qltool", line 314, in <module>
    ql.run()
  File "/Users/vv/Downloads/ql/qiling/qiling/core.py", line 184, in run
    self.loader.run()
  File "/Users/vv/Downloads/ql/qiling/qiling/loader/pe.py", line 303, in run
    self.load()
  File "/Users/vv/Downloads/ql/qiling/qiling/loader/pe.py", line 368, in load
    self.ql.mem.map(self.PE_IMAGE_BASE, self.PE_IMAGE_SIZE, info="[PE]")
  File "/Users/vv/Downloads/ql/qiling/qiling/os/memory.py", line 332, in map
    self.ql.uc.mem_map(addr, size, perms)
  File "/usr/local/lib/python3.7/site-packages/unicorn/unicorn.py", line 448, in mem_map
    raise UcError(status)
unicorn.unicorn.UcError: Invalid argument (UC_ERR_ARG)
vv@iMac qiling %

**Comment by liba2k** [comment]
Try the dev branch.

**Comment by kocoman1** [comment]
Can't run python setup.py install, errors, thanks

/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py:472: UserWarning: Normalizing '0.9.1-3' to '0.9.1.post3'
  normalized_version,
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - broken
CMake Error at /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /tmp/easy_install-DUYBjO/keystone-engine-0.9.1-3/src/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_efc58/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_efc58.dir/build.make CMakeFiles/cmTC_efc58.dir/build
    Building C object CMakeFiles/cmTC_efc58.dir/testCCompiler.c.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch i386 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk   -o CMakeFiles/cmTC_efc58.dir/testCCompiler.c.o   -c /tmp/easy_install-DUYBjO/keystone-engine-0.9.1-3/src/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_efc58
    /usr/local/Cellar/cmake/3.17.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_efc58.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch i386 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_efc58.dir/testCCompiler.c.o  -o cmTC_efc58 
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd
    ld: dynamic main executables must link with libSystem.dylib for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_efc58] Error 1
    make: *** [cmTC_efc58/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:5 (project)


-- Configuring incomplete, errors occurred!
See also "/tmp/easy_install-DUYBjO/keystone-engine-0.9.1-3/src/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/easy_install-DUYBjO/keystone-engine-0.9.1-3/src/build/CMakeFiles/CMakeError.log".
error: Setup script exited with error: SandboxViolation: mkdir('/Library/Python/2.7/site-packages/keystone', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

**Comment by xwings** [comment]
this is a keystone issue.

u can ignore keystone. it will still work.  

but if you want, there is a workaround. please read. https://github.com/qilingframework/qiling/blob/master/docs/SETUP.md

**Comment by xwings** [comment]
Any update?
