### ISSUE TITLE
It's able to read register? like rbp

### ISSUE THREAD

**Issue by aaaddress1** [qilingframework/qiling#280]
Hi there,

I try to hook syscall fork() and let $RAX = 123 on a mirai sample. the sample will store the return value into ds:[rbp+0x78] (like the following picture)

<img width="669" alt="image" src="https://user-images.githubusercontent.com/8559056/81494792-17eca080-92de-11ea-982b-67feb2dc49b9.png">

and I try to fetch ds:[rbp+0x78] by hooking on 0x412456, is it able to do it? :/

<img width="765" alt="image" src="https://user-images.githubusercontent.com/8559056/81494883-bed13c80-92de-11ea-88aa-08af2c7fa892.png">

**Comment by xwings** [comment]
Hi,

Are you on latest dev ? 

If yes, it should work. Please refer to https://qilingframework.readthedocs.io/en/latest/register/

**Comment by aaaddress1** [comment]
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/8559056/81495432-e3c7ae80-92e2-11ea-9345-f85a1e0dd34d.png">

yes I think so. I follow the[guide](https://github.com/qilingframework/qiling/blob/master/docs/SETUP.md), git clone Qiling and install.

**Comment by xwings** [comment]
Hi,

git clone https://github.com/qilingframework/qiling.git
git checkout dev

this should work for you.

try and let me know :)

**Comment by aaaddress1** [comment]
thanks! it works.
btw, write rax = 123 not work on stable version of Qiling. after update it works.
