### ISSUE TITLE
Is that possible make a snapshot of Qling memory?

### ISSUE THREAD

**Issue by aaaddress1** [qilingframework/qiling#281]
Hi there,

I try to implement syscall fork (57) by myself. I suppose the child process by os.fork() should have the same memory layout as parent process. However it fails like the following picture:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/8559056/81700314-161c0c00-949b-11ea-8183-b40c27841b5c.png">

Is that possible to store a snapshot of current status? I mean: execuable file get file-mapping in the same image base, function call traceback on the stack, and the values of registers.

Thanks!

```
# ref: github.com/qilingframework/qiling/blob/dc22aaa4110e113153d602a8c391ca85e49f54c5/qiling/os/posix/syscall/sched.py
def ql_syscall_fork(ql, *args, **kw):
    pid = os.fork()
    if pid != 0:
        regreturn = pid
        ql.nprint("fork() = %d" % (regreturn))
        ql.os.definesyscall_return(regreturn)
    else:
        ql.os.child_processes = True
        regreturn = 0
        ql.nprint("fork() = %d" % (regreturn))
        ql.os.definesyscall_return(regreturn)    
    signal.alarm(TIMEOUT)

    ql = Qiling([test_file], '/rootfs/x8664_linux', output='off')
    ql.console = False
    return ql


def main():  
        ql: Qiling = get_qiling_by_bin('xxxxxx/mirai_x8664')
        ql.root = False
        ql.multithread = True  
        ql.set_syscall(57, ql_syscall_fork) # fork 
        ql.add_fs_mapper('/proc', '/proc')
        ql.run()

if __name__ == "__main__":
    main()
```

**Comment by xwings** [comment]
there are few combination u can do

you can mem.read then mem.write for save and restore and also use ql.reg.store and ql,.reg.restore.

However, as far as i remember, there should not be any different between vfork and fork. We are a emulator and not a real os. technically we don't have to 100% emulate the actual syscall.

**Comment by aaaddress1** [comment]
oops, I guess so :<

I found that ql.uc.context_restore() thats's able to cache [unicorn: sample_x86.py](https://github.com/unicorn-engine/unicorn/blob/master/bindings/python/sample_x86.py) but it doesn't work as expected.

btw it that possible to check out allocated memory regions?
I'll try about mem.write and mem.read, thanks! 

<img width="654" alt="image" src="https://user-images.githubusercontent.com/8559056/81711970-bb88ad00-94a6-11ea-90ef-74a8e06b0e6e.png">

```
# ref: github.com/qilingframework/qiling/blob/dc22aaa4110e113153d602a8c391ca85e49f54c5/qiling/os/posix/syscall/sched.py
def ql_syscall_fork(ql, *args, **kw):
    pid = os.fork()
    if pid != 0:
        regreturn = pid
        ql.nprint("fork() = %d" % (regreturn))
        curr_state = ql.uc.context_save()
        pickle.dump(curr_state, open('snapshot.pickle', 'wb'))
        ql.os.definesyscall_return(regreturn)
    else:
        ql.uc = Uc(UC_ARCH_X86, UC_MODE_64)
        ql.uc.context_restore(pickle.load(open('snapshot.pickle', 'rb')))
        print(os.getpid())
        ql.os.child_processes = True
        regreturn = 0
        ql.nprint("fork() = %d" % (regreturn))
        ql.os.definesyscall_return(regreturn)
    signal.alarm(TIMEOUT)
```

**Comment by xwings** [comment]
Sure, please check out https://docs.qiling.io/en/latest/memory/ and also https://docs.qiling.io/en/latest/register/

**Comment by aaaddress1** [comment]
finally I took the suggestion you gave. that's better solution as an emulator, thanks!

**Comment by xwings** [comment]
Please make a pr if vfork works for fork. Add into mapping table accordingly will do!
