### ISSUE TITLE
anomaly for 32bit PE binaries

### ISSUE THREAD

**Issue by theguly** [qilingframework/qiling#283]
Hello,

I'm trying to use qiling with some 32 bit PE for win xp and I am experiencing problems such as UC_ERR_READ_MEM, UC_ERR_WRITE_MEM and FETCH. I've added some print()s in the code to see the addresses and I mostly see addresses such as 0x8fffffff passed as "until" parameter in emu_start and other addresses during the execution that seem to be greater than 32 bit int max.

for example, a binary dies at:
[+] ERROR: unmapped memory access at 0x46010006
after a ret at 0x46010006

CLI is like:
./qltool run -f pe32.exe --rootfs /path/to/rootfs/x86_windows/ --dump

how can i help tracing this issue?

thanks

**Comment by xwings** [comment]
Hi,

that is unicorm crash error, but you should be able to see things more or less like, API not implemented ?

Please check, maybe it will help.

https://docs.qiling.io/en/latest/faq/

**Comment by theguly** [comment]
the complete error i see is like:
```
Traceback (most recent call last):
  File "./qltool", line 314, in <module>
    ql.run()
  File "/qiling/qiling/core.py", line 199, in run
    self.os.run()
  File "/qiling/qiling/os/windows/windows.py", line 142, in run
    self.ql.emu_start(self.ql.loader.entry_point, self.ql.until_addr, self.ql.timeout)
  File "/qiling/qiling/core.py", line 244, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.6/site-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```
or same trace but a WRITE or READ:
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

looks like a unicorn bug to me, maybe related to 32bit binary over 64bit host/dlls?
i just tried some win7 32bit dlls just to align binary and "guest" and i'm smashed with the same error.
i'm not friend enough with emulators to dig more i think but i can try, meanwhile do you think i should fill an issue at unicorn too?

thanks

**Comment by aquynh** [comment]
This should not be Unicorn bug at all.

I suggest to turn on "disasm" mode, and compare the output with RE of your binary (for example in IDA) to see which memory cause the error. Then you will know what memory to map, or which API should be emulated.

**Comment by theguly** [comment]
> This should not be Unicorn bug at all.
> 
> I suggest to turn on "disasm" mode, and compare the output with RE of your binary (for example in IDA) to see which memory cause the error. Then you will know what memory to map, or which API should be emulated.

already saved a bunch of disasm and debug, and compared to a Xdbg session. i tried with 6/7 binaries, now i will focus on just one to avoid confusion.
given binary dies at a ret instruction (ret address is 0x540548) that should set EIP to a local sub (debugged program flows at 0x5414b0 for example) when running the same binary with qltool the ret sets EIP as 0x46010006 which is unmapped memory.

following the flow with Xdbg i see that stack address that holds ret address (0x0018ff7c on my system, very close to the bottom of the stack) is written by a CALL:
with EIP as 0x54147F i have ESP 0x0018FF80. the instruction is a CALL sub_53991C that sets 0x0018FF7C to next address, which is 0x541484

this doesn't make senso to me because qiling disasm output states:
[+] 0x54147f       e8 98 84 ff ff                call 0x53991c
that matches with my Xdbg address, who told this call to push 0x46010006 and not $EIP+4 ?

thanks

**Comment by xwings** [comment]
Hi,

You should see more error msg before the unicorn error. Can you copy and paste those here ?

**Comment by theguly** [comment]
before the unicorn error i just have a fine disasm:
```
[+] 0x540548       c3                            ret
Traceback (most recent call last):
  File "./qltool", line 250, in <module>
    ql.run(timeout=timeout)
  File "/root/wip/qiling/qiling/core.py", line 196, in run
    self.os.run()
  File "/root/wip/qiling/qiling/os/windows/windows.py", line 125, in run
    self.ql.emu_start(self.ql.loader.entry_point, self.exit_point, self.ql.timeout, self.ql.count)
  File "/root/wip/qiling/qiling/core.py", line 246, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.7/dist-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```

i'm attaching debug output as file, if you think also full disasm can help i can attach it too
[6.debug.txt](https://github.com/qilingframework/qiling/files/4635392/6.debug.txt)

**Comment by xwings** [comment]
We did not try with Windows XP. but the DLL are they from XP ?

**Comment by theguly** [comment]
> We did not try with Windows XP. but the DLL are they from XP ?

i mostly tested Win10, but to exclude Win10's dlls issue I also tested Win7 32bit (same error) and WinXP sp3 32bit (totally different error).

x86_windows holds dlls from a  recent Win10

**Comment by xwings** [comment]
there will be different result from winxp dll till win10 dll. 

you can either turn on output = "dump" or debug to find out more details. 

To be honest, we just completed maybe 30-40% kernel32 API and we still have long way to go. 

If you discover any issue and able to fix the bug. PR always welcome.

**Comment by xwings** [comment]
also have u tried the dev branch ? there are more API there.

**Comment by xwings** [comment]
Also, join our gitter. we got a WIndows spefic chatroom
