### ISSUE TITLE
incorrect description about stack_read and stack_write?

### ISSUE THREAD

**Issue by aaaddress1** [qilingframework/qiling#288]
![image](https://user-images.githubusercontent.com/8559056/82252094-f431f600-9980-11ea-8a72-4718782532ad.png)
I've read the code at [arm64.py](https://github.com/qilingframework/qiling/blob/dc22aaa4110e113153d602a8c391ca85e49f54c5/qiling/arch/arm64.py).

I guess the second argument should be "offset", not "address" right?

**Comment by xwings** [comment]
I guess the documents needs to be PR'ed too

**Comment by xwings** [comment]
should be updated now
