### ISSUE TITLE
Incorrect hook memory by address

### ISSUE THREAD

**Issue by 3vilWind** [qilingframework/qiling#289]
https://github.com/qilingframework/qiling/blob/350208f61641e7e394bf2feffc124a1be22b6f86/qiling/core_hooks.py#L160
Is it really designed to check boundaries for pc, not addr?

**Comment by w1tcher** [comment]
Yes, you are right, it has now been fixed.

https://github.com/qilingframework/qiling/commit/544f3960c882fc671818985067673b5cf59958f5
