### ISSUE TITLE
Disable / capture strace output from Python

### ISSUE THREAD

**Issue by trib0r3** [qilingframework/qiling#290]
Hello, how can I mute or capture the strace log from Python?
I tried to modify `ql.strace_filter`, but with no success :/

**Comment by ucgJhe** [comment]
Hi, @trib0r3 
make sure you are in the branch dev, so you can use the code below to achieve that.

```python
#!/usr/bin/env python3
from qiling import *

if __name__ == "__main__":
    ql = Qiling(["examples/rootfs/x86_linux/bin/x86_hello"], "examples/rootfs/x86_linux", log_dir="qlog")
    ql.filter = ["open"]
    ql.run()
```

**Comment by trib0r3** [comment]
Thank you :) 

I would like to see ~~more~~ any documentation about qiling, because right now for the most cases we are forced to read the source :/

**Comment by aquynh** [comment]
See https://docs.qiling.io. And you are welcome to contribute more docs.
