### ISSUE TITLE
Check for mapped address

### ISSUE THREAD

**Issue by 0xPhoeniX** [qilingframework/qiling#291]
https://github.com/qilingframework/qiling/blob/617bcee20c77c8940dcd9aaf867e9b27a4054812/qiling/os/posix/syscall/mman.py#L204

Hey, any reason for not using `if mmap2_addr != 0 and ql.mem.is_mapped(mmap2_addr, mmap2_length)` ?

**Comment by xwings** [comment]
could be just ql.mem.is_mapped comes way after the original mmap.

please trow in a PR, thanks !

**Comment by 0xPhoeniX** [comment]
I've added PR.

**Comment by xwings** [comment]
there are two same PR. both is yours ?

**Comment by 0xPhoeniX** [comment]
No.

**Comment by xwings** [comment]
its ok. i am blind
