### ISSUE TITLE
Error while trying Demo "Emulating ARM router firmware on Ubuntu X64 machine"

### ISSUE THREAD

**Issue by aj-00** [qilingframework/qiling#296]
Hi,
I tried exploring Qiling. Tried with the demo "Emulating ARM router firmware on Ubuntu X64 machine" as given on https://docs.qiling.io/en/latest/demo/#emulating-arm-router-firmware-on-ubuntu-x64-machine
I downloaded the tenda firmware version AC15 Firmware V15.03.1.16_EN from https://www.tendacn.com/en/download/detail-2600.html

And ran the same script as given in the Demo in the doc

```
from qiling import *
def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, stdin = sys.stdin, stdout = sys.stdout, stderr = sys.stderr)
    # Patch 0x00005930 from br0 to ens33
    ql.patch(0x00005930, b'ens33\x00', file_name = b'libChipApi.so')
    ql.root = False
    ql.run()


if __name__ == "__main__":
    my_sandbox(["rootfs/tendaac15/bin/httpd"], "rootfs/tendaac15")
```

I am getting Invalid memory write error  as in attached screenshot below
![Selection_164](https://user-images.githubusercontent.com/57127733/82664206-d8fc0a80-9c4e-11ea-9f07-7728e5072a6b.png)

I suppose there might be some mem_map error, but I don't know how to deal with it. Any supportive guidance would be helpful for me to explore it further.

Thanks
Asmita

**Comment by xwings** [comment]
for this router, every version patching address and interface might be different. you need to find out which interface u r in and patch the right address. or else it wont work

```
ql.patch(0x00005930, b'ens33\x00', file_name = b'libChipApi.so')
```

**Comment by AsmitaJha08** [comment]
Hi,
Thank you. Could you provide the exact firmware version that you used for this demo?

**Comment by xwings** [comment]
I dont remember which version. But this is what you can do.

- Look for libChipApi.so
- load it with IDA Pro or any debugger/disassemble you of your choice.
- Option 1: look for string br0 and replace with lo or the interface you like
- Option 2: copy the address and replace in the example
- you are good to go

**Comment by AsmitaJha08** [comment]
Hi,
Thank you. I tried as you mentioned in above response. Following is what I got :
I opened libChipApi.so with Ghidra. Found br0 string at address **0x000159f8** (screenshot attached below)
![Selection_186](https://user-images.githubusercontent.com/57127733/82727699-bd096f00-9d09-11ea-9b46-f57f14256250.png)

In the code I replaced the address as below -

```
from qiling import *
import sys
def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, stdin = sys.stdin, stdout = sys.stdout, stderr = sys.stderr)
    # Patch 0x000159f8 from br0 to l0
    ql.patch(0x000159f8, b'l0\x00', file_name = b'libChipApi.so')
    ql.root = False
    ql.run()

if __name__ == "__main__":
    my_sandbox(["rootfs/tendaac15/bin/httpd"], "rootfs/tendaac15")

```

I can see on output socket getting successfully created as attached in screenshot below.
![Selection_188](https://user-images.githubusercontent.com/57127733/82727785-32753f80-9d0a-11ea-91ce-2bfe64c85ae6.png)


But cannot find anything listening on 127.0.0.1:8080

Then, I set log_console=True , I found error as in screenshot below 

![Selection_189](https://user-images.githubusercontent.com/57127733/82727825-7ec07f80-9d0a-11ea-87bb-c8f2f0ab1dee.png)


Is there some mistake that I am doing here?

**Comment by xwings** [comment]
l0 or lo please check your interface

**Comment by xwings** [comment]
The address doesn't seem right to be. Should be a sting of br0 with a null byte terminate. Not a function.

**Comment by AsmitaJha08** [comment]
Hi,
Thanks. My bad it was lo interface. I found br0 as below, I am not sure if  this is what you have mentioned  in above reply.
![Selection_190](https://user-images.githubusercontent.com/57127733/82732056-85f68600-9d28-11ea-9c13-43a7bb3725ad.png)

network interface
![Selection_192](https://user-images.githubusercontent.com/57127733/82732185-3795b700-9d29-11ea-8fcd-106f1a244097.png)


And code change as :

```
from qiling import *
import sys
def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, stdin = sys.stdin, stdout = sys.stdout, stderr = sys.stderr,
                log_dir     = "qlog",
                log_console = True,)
    # Patch 0x000157c0 from br0 to lo
    ql.patch(0x000157c0, b'lo\x00', file_name = b'libChipApi.so')
    ql.root = False
    ql.run()
```

I tried this way, the issue remains as above. 

if __name__ == "__main__":
    my_sandbox(["rootfs/tendaac15/bin/httpd"], "rootfs/tendaac15")

**Comment by xwings** [comment]
very simple.

if it doesn't bind. then u r replacing the wrong thing.

**Comment by AsmitaJha08** [comment]
Yes true, and this is what i am unable to figure out.

**Comment by xwings** [comment]
you should be replacing br0\x00 with lo\x00 not eth0.1

**Comment by AsmitaJha08** [comment]
yes I have used address 0x000157c0 , this is address of br0 as shown in image in above query.

**Comment by xwings** [comment]
maybe a wrong br0. no idea. if the thing did not bind, very likely is a wrong interface. u can disasm to comfirm

**Comment by dozenmatter** [comment]
Hi, I am also currently facing the same issue when trying to emulate ARM router firmware and would like some help.

I am currently using **Ubuntu 18.04.4 LTS** to host Qiling and the router firmware that I'm using is **Tenda AC15 Firmware V15.03.1.17_EN**.

Here is my current code:
```
import sys
sys.path.append("..")
from qiling import *
def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, stdin = sys.stdin, stdout = sys.stdout, stderr = sys.stderr)
    # Patch 0x00005930 from br0 to ens33
    ql.patch(0x00005930, b'ens33\x00', file_name = b'libChipApi.so')
    #ql.root = False
    ql.run()


if __name__ == "__main__":
    my_sandbox(["rootfs/tenda-15.03.1.17/bin/httpd"], "rootfs/tenda-15.03.1.17")
```

To ensure that I am patching at the correct address, below is a screenshot of the hexdump command.
![image](https://user-images.githubusercontent.com/13595917/84011519-d4528880-a9a8-11ea-8638-72a1aa300b56.png)

Here are the network interfaces that I currently have and I am using ens33 as my preferred interface.
![image](https://user-images.githubusercontent.com/13595917/84011714-1aa7e780-a9a9-11ea-9ecd-6cbd6a83b46c.png)

However, I still get the same error message like above where **ql.patch()** was unable to patch "libChipApi.so" and there is an “Invalid memory write (UC_ERR_WRITE_UNMAPPED)” error.

![image](https://user-images.githubusercontent.com/13595917/84012082-999d2000-a9a9-11ea-8163-b8f5dcd1ae6f.png)

I've also tried using the other 2 network interfaces but it did not work too. Is there anything else I should look out for? Thank you.

**Comment by xwings** [comment]
Hi,

I made a new AC15 example and how you can just run it with the firmware

https://github.com/qilingframework/qiling/blob/dev/examples/tendaac15_httpd.py

**Comment by AsmitaJha08** [comment]
Hi, 
Thanks. I tried but I am getting error as in screenshot below. I checked even via dev branch.
![image](https://user-images.githubusercontent.com/57127733/84609620-537a1c00-aed5-11ea-8830-9afef2ee3598.png)

Then I tried by hardcoding the ql.loader.elf_entry value, I get error as below
![image](https://user-images.githubusercontent.com/57127733/84609791-e87d1500-aed5-11ea-972f-11d5d5ce711e.png)

Probably some installation error, I reistalled following everything on https://docs.qiling.io/en/latest/install/ and also checking out to dev branch.

**Comment by xwings** [comment]
from the screenshot, this is not dev for sure.

**Comment by AsmitaJha08** [comment]
Hi,
I re-checked git branch, it's dev.
![image](https://user-images.githubusercontent.com/57127733/84612703-0dc25100-aedf-11ea-818a-bd9e9e9ba320.png)

**Comment by xwings** [comment]
the code show mem.search is not there. mem.search only in dev for now

you are still running the old code. did u install the dev branch ?

**Comment by AsmitaJha08** [comment]
Thanks, I am now able to emulate tenda router firmware without any issue.
![image](https://user-images.githubusercontent.com/57127733/88680493-2e9cd980-d10e-11ea-9bb2-547208b3887f.png)

Had another query, when I am trying to run using gdb, by enabling `ql.debugger = True` as in image below
![image](https://user-images.githubusercontent.com/57127733/88680716-6b68d080-d10e-11ea-8b0f-503d4ecbe029.png)

I am getting error as:
 
After gdb connects at port 9999, I get output as , it waits here for few seconds, 
![image](https://user-images.githubusercontent.com/57127733/88681163-e631eb80-d10e-11ea-9a33-949ffa54e3a8.png)

Then error on gdb side as below
![image](https://user-images.githubusercontent.com/57127733/88680879-99e6ab80-d10e-11ea-9ce8-f420f19cf10e.png)

Then error on emulation side
![image](https://user-images.githubusercontent.com/57127733/88680974-b2ef5c80-d10e-11ea-85d5-4a332524dbfd.png)

**Comment by kabeor** [comment]
@aj-00 Hi, plz try to input 'set remotetimeout 100' in gdb and connect qiling&gdb again, it should be worked.

**Comment by xwings** [comment]
close for now
