### ISSUE TITLE
Remote debugging broken for Windows Executable

### ISSUE THREAD

**Issue by redmed666** [qilingframework/qiling#305]
***Describe the bug**
When trying to debug a Windows executable with radare2, radar2 segfaults.

**Sample Code**
```bash
./qltool run -f ./examples/rootfs/x8664_windows/bin/x8664_hello.exe --rootfs /mnt/hgfs/Downloads/rootfs/ --gdb 0.0.0.0:9998
r2 -d gdb://127.0.0.1:9998
```

**Expected behavior**
No segfault while debugging a Windows executable 

**Additional context**
radareorg/cutter#2194

**Comment by xwings** [comment]
any error msg from qiling ?

**Comment by redmed666** [comment]
No, nothing.

**Comment by xwings** [comment]
![image](https://user-images.githubusercontent.com/463553/82879080-0a3a4a80-9f6f-11ea-9815-266cc859e3f7.png)

**Comment by redmed666** [comment]
Hum, alright... Did you pull and reinstall radare2 before trying this one?

**Comment by xwings** [comment]
i am on latest dev.
u might wanna uninstall by running pip3 unintall qiling and reinstall from src, dev branch

i tried to use cutter and it seems like not working due to their gdb not working ?

**Comment by redmed666** [comment]
Yeah cutter is not responding either on my side...

**Comment by xwings** [comment]
we can go and back there and make noise there now.
