### ISSUE TITLE
having trouble when I was simulating a firmware

### ISSUE THREAD

**Issue by yifiHeaven** [qilingframework/qiling#32]
Firmware：Netgear R6220-V1.1.0.86.img
`import sys
from qiling import *

def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, output="debug", stdin = sys.stdin, stdout = sys.stdout, stderr = sys.stderr, log_file = 'logfile', separate_log_file = True, consolelog = True)
    ql.root = False
    ql.add_fs_mapper('/proc', '/proc')
    ql.run()

if __name__ == "__main__":
    my_sandbox(["rootfs/netgear_r6220/bin/mini_httpd","-d","/www","-r","NETGEAR R6220","-c","**.cgi","-t","300"], "rootfs/netgear_r6220")
`

![image](https://user-images.githubusercontent.com/20828117/68912567-7bfd3480-0793-11ea-830f-008dc4015a84.png)
![image](https://user-images.githubusercontent.com/20828117/68912598-8b7c7d80-0793-11ea-839e-539de81b1f78.png)

**Comment by xwings** [comment]
HI,

which os are you running on. can we have the complete full log?

**Comment by yifiHeaven** [comment]
> HI,
> 
> which os are you running on. can we have the complete full log?

I use qiling in docker  Dockerfile is 
```
FROM ubuntu:18.04

MAINTAINER "Kevin Foo <chbsd64@gmail.com>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get -y upgrade \
  && apt-get install -y python3-pip git cmake

WORKDIR /

RUN git clone https://github.com/qilingframework/qiling

RUN cd /qiling \
  && pip3 install -r requirements.txt \
  && python3 setup.py install

RUN apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#Fix keystone pip3 install of the lib in the wrong dir
RUN cp /usr/local/lib/python3.6/dist-packages/usr/lib/python3/dist-packages/keystone/libkeystone.so /usr/local/lib/python3.6/dist-packages/keystone/

ENV HOME /qiling

WORKDIR /qiling

CMD bash
```
then I use the following command

> docker run -it  -v /home/test/code/qiling/:/qiling/mnt/ charles/qiling:v2
![image](https://user-images.githubusercontent.com/20828117/69021633-72720780-09f3-11ea-9167-71eaa2da9cd8.png)
![image](https://user-images.githubusercontent.com/20828117/69021650-7ef66000-09f3-11ea-8b02-84f2a7dee823.png)
[logfile address](https://paste.ubuntu.com/p/q264T9RDsP/)

**Comment by xwings** [comment]
Personally i never try to run this in docker and never will. It will bind into a port, docker might not help in this case ?

**Comment by chfl4gs** [comment]
Do take a look at docker run -p option if you need to publish container port to host.

**Comment by ucgJhe** [comment]
just reproduced the same error in my ubuntu vm, and found if I lift mmap_start in elf.py it will be fine

**Comment by xwings** [comment]
We were having issue with the exception and did not return any error. 
After we fix the issue it show all our buggy code.

We are looking into it and see how can we fix it.

Personally i dont think lifting the mmap is a good idea, @w1tcher  can comment more.

**Comment by xwings** [comment]
> just reproduced the same error in my ubuntu vm, and found if I lift mmap_start in elf.py will fix this
> 
> does that mean there is some kinda mmap_size limit in qiling ?

Yes. I just update the example and core.py to enable users able to define their own mmap size. I guess we are good for now.

The example just able to make the firmware run, still still error need to be fixed tho.

**Comment by ucgJhe** [comment]
> > just reproduced the same error in my ubuntu vm, and found if I lift mmap_start in elf.py will fix this
> > does that mean there is some kinda mmap_size limit in qiling ?
> 
> Yes. I just update the example and core.py to enable users able to define their own mmap size. I guess we are good for now.
> 
> The example just able to make the firmware run, still still error need to be fixed tho.

I'm wondering by means of "make the firmware run" is it like [this](https://www.youtube.com/watch?v=Nxu742-SNvw) ?

**Comment by xwings** [comment]
the video you posted is a ARM based Tenda AC Router. This example is netgear.

**Comment by xwings** [comment]
btw, checkout examples/netgear example.
you can define mmap_start now.

Again, its still buggy and more syscall need to be fufilled. At the very minimum stage, it able run and show the webserver for now.

**Comment by xwings** [comment]
I will close this issue. Few updates been added in to netgear example and it run well now !
