### ISSUE TITLE
mmap implementation

### ISSUE THREAD

**Issue by jimartin361** [qilingframework/qiling#321]
The Qiling implementation of mmap does not allow the emulated code to specify the address in the first argument. When the emulated code does specify the address, the Qiling mmap will attempt to initialize memory at that location and cause Unicorn to write to unmapped memory.  This will result in a Unicorn error.

In "mman.py" the line:
if mmap2_addr != 0 and mmap2_addr < ql.loader.mmap_address:
        need_mmap = False

Prevents the map from occurring because the "mmap2_addr" is not zero, but rather the requested address.  "mmap2_addr" is also less than "ql.loader.mmap_address".   This will result in "need_mmap" being set to "False".

I would expect the emulated mmap to operate in a similar fashion to an actual mmap.

**Comment by jimartin361** [comment]
How about changing "if mmap2_addr != 0 and mmap2_addr < ql.loader.mmap_address:" in "mman.py" to "if mmap2_addr !=0 and ql.mem.is_mapped(mmap2_addr,mmap2_length):"?

**Comment by xwings** [comment]
would you able to do do a PR ?

**Comment by jimartin361** [comment]
Yes.  I think I just put it up.  Minor modification.  It got mmap working for me.
