### ISSUE TITLE
rewrite https://github.com/qilingframework/qiling/blob/master/qiling/arch/x86_const.py in rust

### ISSUE THREAD

**Issue by gogo2464** [qilingframework/qiling#327]
In aswer to the issue: https://github.com/qilingframework/qiling/issues/253 I want to rewrite https://github.com/qilingframework/qiling/blob/master/qiling/arch/x86_const.py in rust.

**Comment by xwings** [comment]
Hi,

Any code can be discuss using PR. 

I will close it for now.

**Comment by gogo2464** [comment]
@xwings the issue: https://github.com/qilingframework/qiling/issues/253 is very big. I think many people will rewrite some various parts of the code. I want to reserve my part. I have done like that for the issues for a documentation translation project. I believe it was same here.

**Comment by xwings** [comment]
Hi,

I agree its big. Like i mention, PR will be more appropriate place to discuss then issue ?
