### ISSUE TITLE
Ref to #296 "Error while trying Demo "Emulating ARM router firmware on Ubuntu X64 machine""

### ISSUE THREAD

**Issue by dozenmatter** [qilingframework/qiling#328]
Hi, I am also currently facing the same issue when trying to emulate ARM router firmware and would like some help.

I am currently using **Ubuntu 18.04.4 LTS** to host Qiling and the router firmware that I'm using is **Tenda AC15 Firmware V15.03.1.17_EN**.

Here is my current code:
```
import sys
sys.path.append("..")
from qiling import *
def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, stdin = sys.stdin, stdout = sys.stdout, stderr = sys.stderr)
    # Patch 0x00005930 from br0 to ens33
    ql.patch(0x00005930, b'ens33\x00', file_name = b'libChipApi.so')
    #ql.root = False
    ql.run()


if __name__ == "__main__":
    my_sandbox(["rootfs/tenda-15.03.1.17/bin/httpd"], "rootfs/tenda-15.03.1.17")
```

To ensure that I am patching at the correct address, below is a screenshot of the hexdump command.
![image](https://user-images.githubusercontent.com/13595917/84011519-d4528880-a9a8-11ea-8638-72a1aa300b56.png)

Here are the network interfaces that I currently have and I am using ens33 as my preferred interface.
![image](https://user-images.githubusercontent.com/13595917/84011714-1aa7e780-a9a9-11ea-9ecd-6cbd6a83b46c.png)

However, I still get the same error message like #296 . Firstly, it says that there is an Emulation Error.
![image](https://user-images.githubusercontent.com/13595917/84218933-10e5c780-ab02-11ea-9d36-7c440ad95679.png)

Followed by a syscall error where it failed to patch "libChipApi.so" and there is an “Invalid memory write (UC_ERR_WRITE_UNMAPPED)” error.

![image](https://user-images.githubusercontent.com/13595917/84012082-999d2000-a9a9-11ea-8163-b8f5dcd1ae6f.png)

Finally the program exits itself.
![image](https://user-images.githubusercontent.com/13595917/84219139-6a4df680-ab02-11ea-8610-bd3e29fd931c.png)

I've also tried using the other 2 network interfaces but it did not work too. Is there anything else I should look out for? I was also wondering if it could be due to a missing syscall? Thank you.

**Comment by xwings** [comment]
Hi,

I made a new AC15 example and how you can just run it with the firmware

https://github.com/qilingframework/qiling/blob/dev/examples/tendaac15_httpd.py

**Comment by dozenmatter** [comment]
Hi, I've tried using the script you've provided and executed it. But I still couldn't get the emulation running. Below is the output at the end:

![image](https://user-images.githubusercontent.com/13595917/84481365-91eebb80-acc8-11ea-9fdc-f45138c822a4.png)

By scrolling up a bit, I see an error message saying that a syscall is not implemented:
![image](https://user-images.githubusercontent.com/13595917/84481450-af238a00-acc8-11ea-80c7-2e2c60c64583.png)

Is there a need for me to try and patch the missing syscall or maybe make some minor adjustments to the script? Thanks!

**Comment by xwings** [comment]
do u have ur cfm_socket in the right palce ?

**Comment by dozenmatter** [comment]
Okay it wasn't in the correct place. Really sorry and thanks for that!

So far I am able to get it running and have it binded on port 8080. I executed the file using "_sudo python3 script.py_" command.

![image](https://user-images.githubusercontent.com/13595917/84488267-86a08d80-acd2-11ea-829a-0575feedf223.png)

Here is a screenshot of the netstat command:
![image](https://user-images.githubusercontent.com/13595917/84488414-b94a8600-acd2-11ea-956d-2aec8dd36ab0.png)

However when I try to access 127.0.0.1:8080 on Firefox, the program instantly crashes with the following error:

![image](https://user-images.githubusercontent.com/13595917/84488536-ebf47e80-acd2-11ea-90c8-25bbda75ec8c.png)

Whereas when I try to access 127.0.0.1, the Apache2 landing page is loaded:

![image](https://user-images.githubusercontent.com/13595917/84489863-eac45100-acd4-11ea-9922-97800da2cf3d.png)


Here is my code (I've only modified from 'lo' to 'ens33' and the relevant root directories):
```
#!/usr/bin/env python3

import os, socket, sys, threading
sys.path.append("..")
from qiling import *

def patcher(ql):
    br0_addr = ql.mem.search("br0".encode() + b'\x00')
    for addr in br0_addr:
        ql.mem.write(addr, b'ens33\x00')

def nvram_listener():
    server_address = 'rootfs/tenda-15.03.05.19/var/cfm_socket'
    data = ""
    
    try:  
        os.unlink(server_address)  
    except OSError:  
        if os.path.exists(server_address):  
            raise  

    # Create UDS socket  
    sock = socket.socket(socket.AF_UNIX,socket.SOCK_STREAM)  
    sock.bind(server_address)  
    sock.listen(1)  
  
    while True:  
        connection, client_address = sock.accept()  
        try:  
            while True:  
                data += str(connection.recv(1024))

                if "lan.webiplansslen" in data:  
                    connection.send('192.168.170.169'.encode())  
                elif "wan_ifname" in data:
                    connection.send('eth0'.encode())
                elif "wan_ifnames" in data:
                    connection.send('eth0'.encode())
                elif "wan0_ifname" in data:
                    connection.send('eth0'.encode())
                elif "wan0_ifnames" in data:
                    connection.send('eth0'.encode())
                elif "sys.workmode" in data:
                    connection.send('bridge'.encode())
                elif "wan1.ip" in data:
                    connection.send('1.1.1.1'.encode())
                else: 
                    break  
                data = ""
        finally:  
                connection.close() 

def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, output = "debug")
    ql.add_fs_mapper("/dev/urandom","/dev/urandom")
    ql.hook_address(patcher ,ql.loader.elf_entry)
    ql.run()


if __name__ == "__main__":
    nvram_listener_therad =  threading.Thread(target=nvram_listener, daemon=True)
    nvram_listener_therad.start()
    my_sandbox(["rootfs/tenda-15.03.05.19/bin/httpd"], "rootfs/tenda-15.03.05.19")

```

Do you have any idea what's wrong? Appreciate your help!

**Comment by kabeor** [comment]
> Okay it wasn't in the correct place. Really sorry and thanks for that!
> 
> So far I am able to get it running and have it binded on port 8080. I executed the file using "_sudo python3 script.py_" command.
> 
> ![image](https://user-images.githubusercontent.com/13595917/84488267-86a08d80-acd2-11ea-829a-0575feedf223.png)
> 
> Here is a screenshot of the netstat command:
> ![image](https://user-images.githubusercontent.com/13595917/84488414-b94a8600-acd2-11ea-956d-2aec8dd36ab0.png)
> 
> However when I try to access 127.0.0.1:8080 on Firefox, the program instantly crashes with the following error:
> 
> ![image](https://user-images.githubusercontent.com/13595917/84488536-ebf47e80-acd2-11ea-90c8-25bbda75ec8c.png)
> 
> Whereas when I try to access 127.0.0.1, the Apache2 landing page is loaded:
> 
> ![image](https://user-images.githubusercontent.com/13595917/84489863-eac45100-acd4-11ea-9922-97800da2cf3d.png)
> 
> Here is my code (I've only modified from 'lo' to 'ens33' and the relevant root directories):
> 
> ```
> #!/usr/bin/env python3
> 
> import os, socket, sys, threading
> sys.path.append("..")
> from qiling import *
> 
> def patcher(ql):
>     br0_addr = ql.mem.search("br0".encode() + b'\x00')
>     for addr in br0_addr:
>         ql.mem.write(addr, b'ens33\x00')
> 
> def nvram_listener():
>     server_address = 'rootfs/tenda-15.03.05.19/var/cfm_socket'
>     data = ""
>     
>     try:  
>         os.unlink(server_address)  
>     except OSError:  
>         if os.path.exists(server_address):  
>             raise  
> 
>     # Create UDS socket  
>     sock = socket.socket(socket.AF_UNIX,socket.SOCK_STREAM)  
>     sock.bind(server_address)  
>     sock.listen(1)  
>   
>     while True:  
>         connection, client_address = sock.accept()  
>         try:  
>             while True:  
>                 data += str(connection.recv(1024))
> 
>                 if "lan.webiplansslen" in data:  
>                     connection.send('192.168.170.169'.encode())  
>                 elif "wan_ifname" in data:
>                     connection.send('eth0'.encode())
>                 elif "wan_ifnames" in data:
>                     connection.send('eth0'.encode())
>                 elif "wan0_ifname" in data:
>                     connection.send('eth0'.encode())
>                 elif "wan0_ifnames" in data:
>                     connection.send('eth0'.encode())
>                 elif "sys.workmode" in data:
>                     connection.send('bridge'.encode())
>                 elif "wan1.ip" in data:
>                     connection.send('1.1.1.1'.encode())
>                 else: 
>                     break  
>                 data = ""
>         finally:  
>                 connection.close() 
> 
> def my_sandbox(path, rootfs):
>     ql = Qiling(path, rootfs, output = "debug")
>     ql.add_fs_mapper("/dev/urandom","/dev/urandom")
>     ql.hook_address(patcher ,ql.loader.elf_entry)
>     ql.run()
> 
> 
> if __name__ == "__main__":
>     nvram_listener_therad =  threading.Thread(target=nvram_listener, daemon=True)
>     nvram_listener_therad.start()
>     my_sandbox(["rootfs/tenda-15.03.05.19/bin/httpd"], "rootfs/tenda-15.03.05.19")
> ```
> 
> Do you have any idea what's wrong? Appreciate your help!

you should use port:8080 but not port:80, because you have bind qiling to 8080, not 80!

**Comment by dozenmatter** [comment]
Hi @kabeor, as I have stated above, I have tried to access **127.0.0.1:8080** on Firefox, but the program instantly crashes. Also, Qiling automatically binded itself to port 8080 when I executed my script.

**Comment by kabeor** [comment]
> Hi @kabeor, as I have stated above, I have tried to access **127.0.0.1:8080** on Firefox, but the program instantly crashes. Also, Qiling automatically binded itself to port 8080 when I executed my script.

well, I think xwings will answer you better about this, I'm more clear about the debugger part.

**Comment by xwings** [comment]
Are you on dev branch ? I just tested and its all fine on my side.

**Comment by xwings** [comment]
@dozenmatter the reason why 8080 is bind to port 80 you need root permissions.

**Comment by dozenmatter** [comment]
Hmm I executed my script using _**sudo**_ though, and just to be sure I've also tried executing the script as _**root**_ user but it still binds to port 8080. 

I think I am currently on master branch as I followed the installation guide from https://docs.qiling.io/en/latest/install/. I will try cloning dev branch and get back to you soon.

**Comment by xwings** [comment]
you need to enable ql.root=True and so for port 80. Qiling emulate everything in userland, i dont see why you want to bind to port 80

check out https://docs.qiling.io/en/latest/faq/ how to clone dev

**Comment by dozenmatter** [comment]
Hi, I've tried using dev branch, but it still did not work for me. The error message produced is the same as above. My script is also the same except for an additional "_ql.root = True_" line.

![image](https://user-images.githubusercontent.com/13595917/84585824-2fbbc500-ae46-11ea-80b6-3816b8b57984.png)

Here is my connection status:

![image](https://user-images.githubusercontent.com/13595917/84585838-43ffc200-ae46-11ea-9236-56e14a3c5bfd.png)
![image](https://user-images.githubusercontent.com/13595917/84585848-6396ea80-ae46-11ea-8ffa-1189c8641a05.png)

**Comment by xwings** [comment]
if you are using the example script, it should be 127.0.0.1 , will you be able to debug and check what is the issue ?

**Comment by xwings** [comment]
You change to ens33. now i see.

But, did u read the example carefully ? rename the webroot_ro to webroot ?

**Comment by xwings** [comment]
https://github.com/qilingframework/qiling/blob/dev/examples/tendaac1518_httpd.py

read the comment and do the changes accordingly

**Comment by dozenmatter** [comment]
Yup I have followed whatever that was listed inside the comments. I have also tried using the "lo" interface too. 

I will do my best to see if I can debug this. Thanks!

**Comment by xwings** [comment]
your issue seems like a file not found to me.

i tested ac15 few version and ac18 few version and all went well.

**Comment by dozenmatter** [comment]
Hi @xwings, I have managed to get my router running. Here is what I did:

Following the error message, I went to modify the following lines in _**ql_syscall_send()**_ located in "/usr/local/lib/python3.6/dist-packages/qiling-1.1a1-py3.6.egg/qiling/os/posix/syscall/socket.py" file.

ql.dprint(**D_INFO**, ql.os.file_des[send_sockfd]) --> ql.dprint(**D_CTNT**, ql.os.file_des[send_sockfd])

Is it safe to make these changes to the file?

**Comment by xwings** [comment]
maybe i should just delete that line

D_CTNT and D_INFO is is the same just on different. 

I will push a quick fix to avoid this

**Comment by klks** [comment]
@xwings 
seems to be a bug in socket.py

change
ql.dprint(D_INFO, ql.os.file_des[send_sockfd])
to
ql.dprint(D_INFO, str(ql.os.file_des[send_sockfd]) )

**Comment by xwings** [comment]
i saw that,

done and testing now. and it should be CTNT too

**Comment by xwings** [comment]
@dozenmatter there are tons of bugs in this router. enjoy !

**Comment by xwings** [comment]
pushed and close.

**Comment by dozenmatter** [comment]
Sorry @xwings just one more question from me!
If I am interested in trying to emulate other ARM router firmware, do I need to rewrite the entire script that you've posted?
If so, what are the binary/config files I should look out for to be able to emulate another firmware?
Really appreciate your advice!

**Comment by xwings** [comment]
Some firmeware are similar and some are very different. 

It all very depends. You need to figure this out.

Please remember this is a framework not a firmware emulation tools. So, there will never be a one button "Emulate Everything" function.
