### ISSUE TITLE
Error while Running Qiling in window

### ISSUE THREAD

**Issue by neoz** [qilingframework/qiling#33]
> $ python hello_x86_linux.py
> Traceback (most recent call last):
>   File "hello_x86_linux.py", line 14, in <module>
>     from qiling import *
>   File "..\qiling\__init__.py", line 1, in <module>
>     from .core import *
>   File "..\qiling\core.py", line 17, in <module>
>     from qiling.os.posix.filestruct import *
>   File "..\qiling\os\posix\filestruct.py", line 14, in <module>
>     import fcntl
> ModuleNotFoundError: No module named 'fcntl'

**Comment by xwings** [comment]
hi,

i dont think we have fcntl in windows. u can try to run it in WSL. please do taka note WSL2 might work better.

**Comment by 0x1shyboy1** [comment]
https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows

**Comment by xwings** [comment]
as @0x1shyboy1 mention. yes, Windows does not comes with fcntl

**Comment by xwings** [comment]
Well, 

being said, we need to find a way to work around it. Any suggestion?

**Comment by 0x1shyboy1** [comment]
Windows : Create fcntl.py in the Lib directory of Python.
##fcntl.py
def fcntl(fd, op, arg=0):
    return 0
 
def ioctl(fd, op, arg=0, mutable_flag=True):
    if mutable_flag:
        return 0
    else:
        return ""
 
def flock(fd, op):
    return
 
def lockf(fd, operation, length=0, start=0, whence=0):
    return
******************
It work for me !!
however,if i run the example of linux,i will get 
Traceback (most recent call last):
  File "hello_x8664_linux.py", line 18, in <module>
    ql = Qiling(["rootfs/x8664_linux/bin/x8664_hello"], "rootfs/x8664_linux")
  File "C:\ProgramData\Anaconda3\lib\site-packages\qiling-0.9-py3.7.egg\qiling\core.py", line 176, in __init__
    self.run_exec()
  File "C:\ProgramData\Anaconda3\lib\site-packages\qiling-0.9-py3.7.egg\qiling\core.py", line 184, in run_exec
    loader_file = self.build_os_execution("loader_file")
  File "C:\ProgramData\Anaconda3\lib\site-packages\qiling-0.9-py3.7.egg\qiling\core.py", line 179, in build_os_execution
    self.runtype = ql_get_os_module_function(self.ostype, self.arch, "runner")
  File "C:\ProgramData\Anaconda3\lib\site-packages\qiling-0.9-py3.7.egg\qiling\utils.py", line 31, in ql_get_os_module_function
    return ql_get_module_function(module_name, function_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\qiling-0.9-py3.7.egg\qiling\utils.py", line 60, in ql_get_module_function
    raise QlErrorModuleNotFound(f"Unable to import module {module_name}")
qiling.exception.QlErrorModuleNotFound: Unable to import module qiling.os.linux.x8664

any example running on Ubuntu is normal.

**Comment by xwings** [comment]
Hi,

If you able to solve it. PR is appriciated

**Comment by xwings** [comment]
Just a note

This issue is related to issue #24

**Comment by xwings** [comment]
closed and conversation moved to issue #24
