### ISSUE TITLE
Examples don't work with installation instructions

### ISSUE THREAD

**Issue by 0x80O0oOverfl0w** [qilingframework/qiling#335]
Installation instructions should include a note about switching to dev branch, or examples need to be updated to indicate which examples only work with dev branch.
As is, the "On enter interceptor with ql.set_api()" example https://docs.qiling.io/en/latest/hijack/#on-enter-interceptor-with-qlset_api does not work (QL_INTERCEPT not defined error) when using latest installation instructions https://docs.qiling.io/en/latest/install/

**Comment by xwings** [comment]
Thanks for comment. We do mention that in FAQ. 

Please bare with us, working on the code and maintaining good documents is hard. Especially no one paying us.

So, does it work now?

**Comment by 0x80O0oOverfl0w** [comment]
No problem, I should have checked the FAQ first. I got some help on twitter and was told I should submit it here. I Yes, after I checked out dev branch, the example works perfectly.

**Comment by xwings** [comment]
cool, that was me on twitter. :)

I updates the installation documents and just remind new comer to always check dev branch.
