### ISSUE TITLE
qiling.exception.QlErrorFileNotFound: [!] Target binary not found

### ISSUE THREAD

**Issue by fa1conn** [qilingframework/qiling#340]
when I run the r6220 code,it showed some error
```
Traceback (most recent call last):
  File "r6220.py", line 36, in <module>
    "rootfs/r6220")
  File "r6220.py", line 19, in my_netgear
    profile     = "./netgear_6220.ql"
  File "/usr/local/lib/python3.7/site-packages/qiling-1.1a1-py3.7.egg/qiling/core.py", line 108, in __init__
    raise QlErrorFileNotFound("[!] Target binary not found")
qiling.exception.QlErrorFileNotFound: [!] Target binary not found
```
I haved put netgear_6220.ql in the **profile** floder and python script current floder，but it can‘t work.Could you tell me the right place?

**Comment by fa1conn** [comment]
I found I make a mistakes，the route don’t have mini_httpd

**Comment by xwings** [comment]
Hey,

You are start No. 1024. I guess this lucky No 1024 should allow me to mail you some Qiling sticker ?

**Comment by fa1conn** [comment]
Yes，of course，are you Chinese？I live in China.I will return to Xidian University on June 30,If you live in China,you could send the sticker&nbsp;a few days in advance.
Address:South Campus of Xidian University，Chang'an District, Xi'an City, Shanxi Province（陕西省西安市长安区西安电子科技大学南校区）
phone number:15339148570
Recipient's name：Yifei Cai（蔡奕飞）


THX very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kj.xwings.l"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 晚上6:01
收件人:&nbsp;"qilingframework/qiling"<qiling@noreply.github.com&gt;;
抄送:&nbsp;"句"<874355815@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [qilingframework/qiling] qiling.exception.QlErrorFileNotFound: [!] Target binary not found (#340)





 
Hey,
 
You are start No. 1024. I guess this lucky No 1024 should allow me to mail you some Qiling sticker ?

**Comment by xwings** [comment]
I think Uni will not reopen so soon.
