### ISSUE TITLE
Syscall hook

### ISSUE THREAD

**Issue by neepl** [qilingframework/qiling#36]
Hi! Is there a proper way to add syscall without patching library? Or I should patch corresponding files to implement required functionality?

**Comment by xwings** [comment]
HI,

We are emulating syscall and did not patch any library.

If you want to implement a new syscall, its all in the qiling/os/posix/syscall.py file

**Comment by neepl** [comment]
Sorry, under 'library' I meant Qiling framework. Maybe it is worth to add some interface to do from user scripts?
Right now I implemented it like that for Linux:
`
from qiling.os.linux.arm_syscall import ARM_LINUX_SYSCALL
def add_linux_syscall(no, handler):
    script_name = os.path.splitext(os.path.basename(os.path.realpath(__file__)))[0]
    handler_name = handler.__name__
    ARM_LINUX_SYSCALL.append([no, f"__import__('{script_name}').{handler_name}"])
`

**Comment by xwings** [comment]
hi,

you can either choose to overwrite the syscall or addig your own.
But it will really cool if you can PR the new syscall. We need more !

**Comment by xwings** [comment]
Hi,

We just added ql.set_syscall and ql.set_winapi

Is that what you looking for?

**Comment by xwings** [comment]
Close this case for now.

We added a customized syscall and windows API

**Comment by neepl** [comment]
> Hi,
> 
> We just added ql.set_syscall and ql.set_winapi
> 
> Is that what you looking for?

I think yes. Thanks!

**Comment by xwings** [comment]
try and let us know if u like it , or not
