### ISSUE TITLE
emulate a Windows EXE on a Linux machine - Unable to import module

### ISSUE THREAD

**Issue by packmad** [qilingframework/qiling#381]
**Describe the bug**
`qiling.exception.QlErrorModuleNotFound: [!] Unable to import module qiling.os.windows.windows`

**Sample Code**
```python
from qiling import *
from os.path import isdir, isfile, join

def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs)
    ql.run()

if __name__ == "__main__":
    # execute Windows EXE under our rootfs
    rootfs = "examples/rootfs/x86_windows/"
    assert isdir(rootfs)
    sample = join(rootfs, "bin", "hello.exe")
    assert isfile(sample)
    my_sandbox([sample], rootfs)
```

**Expected behavior**
It should run `hello.exe` (the executable works on Windows)

**Additional context**
I've created the `examples/rootfs/x86_windows/Windows` using your script `dllscollector.bat`

**Comment by chfl4gs** [comment]
Read the documentation and check your installation. This is not an issue.

```bash
~/Work/test/qiling/examples:$ uname -a
```
Linux coeusasus 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux

```bash
~/Work/test/qiling/examples:$ ls rootfs/x86_windows/Windows/SysWOW64/
```
advapi32.dll                             comctl32.dll  kernel32.dll    msvcrt.dll    psapi.dll     urlmon.dll        version.dll  wsock32.dll
api-ms-win-core-fibers-l1-1-1.dll        comdlg32.dll  KernelBase.dll  netapi32.dll  rpcrt4.dll    user32.dll        winhttp.dll
api-ms-win-core-localization-l1-2-1.dll  crypt32.dll   mpr.dll         ntdll.dll     setupapi.dll  userenv.dll       wininet.dll
api-ms-win-core-synch-l1-2-0.dll         gdi32.dll     msvcp60.dll     ole32.dll     shell32.dll   uxtheme.dll       winmm.dll
api-ms-win-core-sysinfo-l1-2-1.dll       IPHLPAPI.DLL  msvcr110.dll    oleaut32.dll  shlwapi.dll   vcruntime140.dll  ws2_32.dll

```bash
~/Work/test/qiling/examples:$ python test.hello.py 
[+] Loading rootfs/x86_windows/bin/x86_hello.exe to 0x400000
[+] PE entry point at 0x401280
[+] Initiate stack address at 0xfffdd000 
[+] TEB addr is 0x6000
[+] PEB addr is 0x6044
[+] Loading rootfs/x86_windows/Windows/SysWOW64/kernel32.dll to 0x10000000
[+] Done with loading rootfs/x86_windows/Windows/SysWOW64/kernel32.dll
[+] Loading rootfs/x86_windows/Windows/SysWOW64/msvcrt.dll to 0x100c5000
[+] Done with loading rootfs/x86_windows/Windows/SysWOW64/msvcrt.dll
[+] Done with loading rootfs/x86_windows/bin/x86_hello.exe
__set_app_type(at = 0x1)
SetUnhandledExceptionFilter(lpTopLevelExceptionFilter = 0x401110) = 0x0
__getmainargs(_Argc = 0x405004, _Argv = 0x405000, _Env = 0xffffcfcc, _DoWildCard = 0xffffffff, _StartInfo = 0xffffcfd0) = 0x0
__p__fmode() = 0x501dc14
atexit(func = 0x401340) = 0x0
atexit(func = 0x401880) = 0x0
__p__environ() = 0x501dc18
Hello world!
puts(str = "Hello world!") = 0xd
_cexit()
ExitProcess(uExitCode = 0x0)
```
