### ISSUE TITLE
Issues trying to debug with IDA Pro

### ISSUE THREAD

**Issue by alexander-pick** [qilingframework/qiling#385]
Trying to attach IDA Pro to the debug stub will instantly trigger the process to continue. Before IDA can attach and load the binary. Attachment from IDA is not possible that way. 

I tried it with and without an existing IDB. It seems like the wait at entrypoint is removed before the debugger is attached and can place the configured wait. If there is anything I can do to help debugging this let me know.

I used the exact settings as described here:

https://docs.qiling.io/en/latest/debugger/#debug-with-ida

Target is an aarch64 binary. I am using IDA Pro 7.5 SP1 on Linux with qiling running on the same machine.

Maybe this output from IDA might be interesting:
GDB: qSupported packet failed
Command "ProcessAttach" failed
GDB: qSupported packet failed
Command "ProcessAttach" failed

**Comment by alexander-pick** [comment]
Tried it with simply using GDB:

(gdb) target remote localhost:9999
Remote debugging using localhost:9999
Ignoring packet error, continuing...
warning: unrecognized item "timeout" in "qSupported" response
Ignoring packet error, continuing...
Remote replied unexpectedly to 'vMustReplyEmpty': timeout
(gdb)

**Comment by xwings** [comment]
I need more information
Does IDA Crash ?

**Comment by alexander-pick** [comment]
IDA throws and error, but gdb does the same so I believe it is not an IDA problem. 

As soon as I attach the debugger the qiling window shows some activity, IDA shows an attach to PID dialog and if I choose 0, I get this error:

![Image of error](http://pwn.su/img/github/error_ida.png)

The qSupported error message shows up in GDB and IDA.

**Comment by xwings** [comment]
my ida pro 7.5sp1 seems to be working fine. not too sure what is the issue. maybe @kabeor can help to check

**Comment by kabeor** [comment]
@alexander-pick Hello! Can you try example/gdb.py with IDA first? Make sure you're doing everything right.
Modify the code like this:
```
#!/usr/bin/env python3
# 
# Cross Platform and Multi Architecture Advanced Binary Emulation Framework
# Built on top of Unicorn emulator (www.unicorn-engine.org) 

# This sample code enables GDB server at localhost:9999 (default settings)

import sys
sys.path.append("..")
from qiling import *


def test_gdb(path, rootfs):
    ql = Qiling(path, rootfs, output="off")

    # Enable debugger to listen at localhost address, default port 9999
    ql.debugger = True

    ql.debugger = "idapro:0.0.0.0:9999"  # IDApro server listens to 127.0.0.1:9999

    # Emulate
    ql.run()  

if __name__ == "__main__":
    test_gdb(["rootfs/arm64_linux/bin/arm64_hello"], "rootfs/arm64_linux")
```


By the way, if you want to debug AARCH64 with gdb, please use **gdb-multiarch** , and `set architecture aarch64`

**Comment by alexander-pick** [comment]
I will give it a try and let you know about the results.

**Comment by xwings** [comment]
This is the issue, u just need  without the ida pro.

```
ql.debugger = "0.0.0.0:9999"  
```
