### ISSUE TITLE
how to fuzz programs that took inputs from command line and environment variables?

### ISSUE THREAD

**Issue by leeeddin** [qilingframework/qiling#387]
**Is your feature request related to a problem? Please describe.**
only provided a example that took inputs from stdin

**Describe the solution you'd like**
how to fuzz programs that took inputs from command line and environment variables?

**Comment by xwings** [comment]
hi, 

you can use ENV to set it. We will make and release an example this weekend at HITBLOCKDOWN 002

**Comment by xwings** [comment]
Example uploaded.

Checkout our dev branch, example folder.
