### ISSUE TITLE
qltool run error

### ISSUE THREAD

**Issue by newthis** [qilingframework/qiling#393]
***Describe the bug**
Qltool Running Error

**Sample Code**
```
commandLine invocation
python3 qltool run --disasm -c wannacry-trace.cov -f  /home/lzz/examples/rootfs/x86_windows/bin/wannacry.bin --rootfs /home/lzz/examples/rootfs/x86_windows/ 
```
**Error Output**
qiling.exception.QlErrorFileNotFound: error:registry files not found in /home/lzz/examples/rootfs/x86_windows/

**Comment by xwings** [comment]
Hi,

please checkout how to collect registry

https://docs.qiling.io/en/latest/install/

**Comment by newthis** [comment]
thks for your answer!
