### ISSUE TITLE
MacOS can not install

### ISSUE THREAD

**Issue by fr0zenrain** [qilingframework/qiling#40]
on macos, the win32 script was called, so install failed

...
Processing dependencies for qiling==0.9
Searching for unicorn>=1.0.2rc1
Reading https://pypi.org/simple/unicorn/
Downloading https://files.pythonhosted.org/packages/c5/7c/503af471bb35d5ac29df57af2d4f65bd2eafed15bcadfb3766ac65c59eb6/unicorn-1.0.2rc1.tar.gz#sha256=6bda96ee35217fff50af55ba95cb76a601f927f056d9502e61510d4bc29a209d
Best match: unicorn 1.0.2rc1
Processing unicorn-1.0.2rc1.tar.gz
Writing /tmp/easy_install-Q8QFQm/unicorn-1.0.2rc1/setup.cfg
Running unicorn-1.0.2rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Q8QFQm/unicorn-1.0.2rc1/egg-dist-tmp-0OuVVs
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '1.0.2.rc1' to '1.0.2rc1'
  normalized_version,
Microsoft (R) Build Engine version 16.1.85+gad9c9926a7 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Syntax:              MSBuild.exe [options] [project file | directory]
...

**Comment by xwings** [comment]
What is the error msg ?

**Comment by fr0zenrain** [comment]
i'm sorry, last test is python2, today i have the same issue with python 3.7.4
the error message is too long and same as before. so can't put in here.

.....

Processing qiling-0.9-py3.7.egg
Removing /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiling-0.9-py3.7.egg
Copying qiling-0.9-py3.7.egg to /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
qiling 0.9 is already the active version in easy-install.pth

Installed /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiling-0.9-py3.7.egg
Processing dependencies for qiling==0.9
Searching for unicorn>=1.0.1
Reading https://pypi.org/simple/unicorn/
Downloading https://files.pythonhosted.org/packages/c5/7c/503af471bb35d5ac29df57af2d4f65bd2eafed15bcadfb3766ac65c59eb6/unicorn-1.0.2rc1.tar.gz#sha256=6bda96ee35217fff50af55ba95cb76a601f927f056d9502e61510d4bc29a209d
Best match: unicorn 1.0.2rc1
Processing unicorn-1.0.2rc1.tar.gz
Writing /tmp/easy_install-ssorv3jy/unicorn-1.0.2rc1/setup.cfg
Running unicorn-1.0.2rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ssorv3jy/unicorn-1.0.2rc1/egg-dist-tmp-fdn7pmfj
/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/dist.py:474: UserWarning: Normalizing '1.0.2.rc1' to '1.0.2rc1'
  normalized_version,
Microsoft (R) Build Engine version 16.1.85+gad9c9926a7 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Syntax:              MSBuild.exe [options] [project file | directory]

Description:         Builds the specified targets in the project file. If
                     a project file is not specified, MSBuild searches the
                     current working directory for a file that has a file
                     extension that ends in "proj" and uses that file.  If
                     a directory is specified, MSBuild searches that
                     directory for a project file.

Switches:            Note that you can specify switches using both
                     "-switch" and "/switch".

**Comment by chfl4gs** [comment]
You need gcc or cmake to compile unicorn-engine. Please see unicorn-engine doc [compile-nix](https://github.com/unicorn-engine/unicorn/blob/master/docs/COMPILE-NIX.md) for more details.

**Comment by xwings** [comment]
No response users and answer provided. case close.
