### ISSUE TITLE
ModuleNotFoundError: No module named 'resource' on Windows10 python3.7

### ISSUE THREAD

**Issue by newthis** [qilingframework/qiling#400]
***Describe the bug**
The qiling framework works well on ubuntu python3.7, while on windows 10 python3.7,
it throws exception: 
ModuleNotFoundError: No module named 'resource', 
and python-resources packae（0.3） has been installed on windows.

**Sample Code**
from qiling import *
if __name__ == "__main__":
    ql = Qiling(["arm_test/arm64_linux/bin/arm64_hello"], "arm_test/arm64_linux")
    ql.run()

**Screenshots**
<img width="646" alt="捕获" src="https://user-images.githubusercontent.com/9391505/88496396-8ee92980-cfef-11ea-91f6-44838b84f4ad.PNG">
<img width="257" alt="捕获2" src="https://user-images.githubusercontent.com/9391505/88496403-96a8ce00-cfef-11ea-9e53-51d8ea40e022.PNG">

**Comment by xwings** [comment]
issue fix in PR https://github.com/qilingframework/qiling/pull/403
