### ISSUE TITLE
Error after enabling debugger in qiling(tenda router demo)

### ISSUE THREAD

**Issue by aj-00** [qilingframework/qiling#406]
Hello,
I am able to emulate tenda router firmware without any issue.
![image](https://user-images.githubusercontent.com/57127733/88680493-2e9cd980-d10e-11ea-9bb2-547208b3887f.png)

Had another query, when I am trying to run using gdb, by enabling `ql.debugger = True` as in image below
![image](https://user-images.githubusercontent.com/57127733/88680716-6b68d080-d10e-11ea-8b0f-503d4ecbe029.png)

I am getting error as:
 
After gdb connects at port 9999, I get output as , it waits here for few seconds, 
![image](https://user-images.githubusercontent.com/57127733/88681163-e631eb80-d10e-11ea-9a33-949ffa54e3a8.png)

Then error on gdb side as below
![image](https://user-images.githubusercontent.com/57127733/88680879-99e6ab80-d10e-11ea-9ce8-f420f19cf10e.png)

Then error on emulation side
![image](https://user-images.githubusercontent.com/57127733/88680974-b2ef5c80-d10e-11ea-85d5-4a332524dbfd.png)

_Originally posted by @AsmitaJha08 in https://github.com/qilingframework/qiling/issues/296#issuecomment-665084244_

**Comment by xwings** [comment]
could be issue with fork(), which we are not supporting yet

**Comment by aj-00** [comment]
Thanks, 
I am a bit confused here, does this fork thing come into picture only when the debugger is enabled? Because if I disabled the debugger, it gets emulated without any flaw.

**Comment by xwings** [comment]
the debugger cannot attach the  tenda vfork() i do hope the community can fix it.

**Comment by aj-00** [comment]
Hi,
As mentioned in [this answer by @kabeor ](https://github.com/qilingframework/qiling/issues/415#issuecomment-668974375),
Set timeout in GDB resolves the issue, it works.
Once set up and forked it gets exit. How can I debug the forked process? I tried using `set follow-fork mode child` but didn't work.
![image](https://user-images.githubusercontent.com/57127733/89543312-63034a80-d81e-11ea-9e05-4b14e64ee348.png)

Any suggestions would be helpful.
Thanks

**Comment by cq674350529** [comment]
@aj-00  A quick ugly trick is to set the return value of `fork()` to 0, then you can debug the forked process.

**Comment by xwings** [comment]
i just updated tenda example with gdb now.

**Comment by xwings** [comment]
close for now
