### ISSUE TITLE
GetStringTypeA is not implemented

### ISSUE THREAD

**Issue by r1git** [qilingframework/qiling#41]
Hello,

Testing the example Easy_CrackMe.exe:
`~/tools/qiling/examples$ python crackme_x86_windows_unpatch.py`
Gives a:
`GetStringTypeA is not implemented`.

I had to copy the GetStringTypeExA function and rename it to GetStringTypeA  in qiling/qiling/os/windows/dlls/kernel32.py to make it work. 
I was wondering if there was an easiest way that I may have missed.

commit e54bc5e93f23e9090d9077c2025c72ac932ba482
Author: chfl4gs <55137784+chfl4gs@users.noreply.github.com>
Date:   Thu Nov 28 20:28:55 2019 +0800
```
$ uname -a
Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Great tool though.
Cheers.

**Comment by xwings** [comment]
Which DLLs are you using? The one from Windows or the one with the repo.

**Comment by r1git** [comment]
I copied user32 and kernel32 from an XP image. The /examples/rootfs/x86_windows/dlls/ directory of the repo was empty...

**Comment by xwings** [comment]
Hi,

Our 32bits DLLs are based on WIndows 7 and 64bit are on Windows 10

More info here: https://github.com/qilingframework/qiling/blob/master/docs/DLLX86.txt

Can you try it and see the result still the same ?

**Comment by r1git** [comment]
Hi,

It works like a charm with dlls from Win7 (not the same dll versions and hashes but still).

Thanks a lot.
