### ISSUE TITLE
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)

### ISSUE THREAD

**Issue by jukeboxfr** [qilingframework/qiling#42]
Hi all, I get this trouble when I try the example provided in the documentation; I do not understand what is fair :)
```py

#!/usr/bin/python3
from unicorn import *
from capstone import *
from qiling import *
 
import sys
 
md = Cs(CS_ARCH_X86, CS_MODE_64)
 
def hook_code(mu, address, size, user_data):
 	print('>>> Tracing instruction at {}, instruction size = {}'.format(hex(address), size))
 
 if __name__ == '__main__':
 	ql = Qiling(["./a.out"], "/")
 	ql.show_map_info()
 	ql.uc.hook_add(UC_HOOK_CODE, hook_code)
 	ql.run()
```

> +] 555555554000 - 555555756000      /mnt/c/Users/jukebox/Desktop/Whitebox/lab1/a.out
> [+] 7ffff7dd5000 - 7ffff7ffb000      /lib64/ld-linux-x86-64.so.2
> brk(0x0)
> uname(0x7fffffffe9d0) = 0
> access(/etc/ld.so.nohwcap, 0x0) = -1
> access(/etc/ld.so.preload, 0x4) = -1
> open(/etc/ld.so.cache, 0x80000, 0x1) = 3
> fstat(3, 0x7fffffffe3b0) = 0
> SYSCALL:  ql_syscall_mmap2
> [!] SYSCALL: ql_syscall_mmap2
> close(3) = 0
> Invalid memory read (UC_ERR_READ_UNMAPPED)
> [!] Invalid memory read (UC_ERR_READ_UNMAPPED)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/qiling-0.9-py3.5.egg/qiling/os/linux/x8664.py", line 115, in runner
>   File "/usr/local/lib/python3.5/dist-packages/unicorn/unicorn.py", line 288, in emu_start
>     raise UcError(status)
> unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./primus.py", line 17, in <module>
>     ql.run()
>   File "/usr/local/lib/python3.5/dist-packages/qiling-0.9-py3.5.egg/qiling/core.py", line 192, in run
>   File "/usr/local/lib/python3.5/dist-packages/qiling-0.9-py3.5.egg/qiling/os/linux/x8664.py", line 126, in runner
> qiling.exception.QlErrorExecutionStop: [!] Emulation Stopped

**Comment by xwings** [comment]
can you run without 

 	ql.show_map_info()
 	ql.uc.hook_add(UC_HOOK_CODE, hook_code)

and see what is the outcome.

**Comment by jukeboxfr** [comment]
I get exactly the same error

**Comment by xwings** [comment]
Is this WSL?

**Comment by xwings** [comment]
Ok, looks like you are in WSL. 
We just discover there are some issue with WSL, but i guess we will only fix it on WSL2.

**Comment by bambu** [comment]
I get the same error emulating a linux x86_64 binary from macOS. I'm using the latest master versions of Qiling, Keystone, and Unicorn
