### ISSUE TITLE
hook_TlsFree implementation inconsistant/not working

### ISSUE THREAD

**Issue by mitp0sh** [qilingframework/qiling#422]
***Describe the bug**
In qiling/os/windows/dlls/kernel32.py there are two TLS related functions emulated. TlsAlloc and TlsFree, while TlsAlloc is incrementing the index, my understand of the implementation would be TlsFree should decrement the index variable. That is not happening. Moreover I believe the whole logic is broken, because if TlsFree is executed on an index in the middle of the array, there will be gap. The gap should be closed and all indices above the removed one should be decremented by 1.

I might be completely wrong here, but to me it seems the implementation is kind of buggy an will cause problems in more complex samples.

I am currently working on my own implementation that supports TLS callbacks that are call pre EP on windows. I might issue an fix together with my implementation if I have time and create a pull request.

**Sample Code**
```python
ql.thread_manager.current_thread.tls_index -= 1
```

**Expected behavior**
No issues, TLS working correctly

**Screenshots**
n/a

**Additional context**
n/a

**Comment by xwings** [comment]
cool, looking forward for your PR !

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2020. Feel free to open a new issue if you have any similar problem.
