### ISSUE TITLE
Duplicated messages from ql.nprint when using the library with absl-py

### ISSUE THREAD

**Issue by kqyang** [qilingframework/qiling#425]
See https://github.com/abseil/abseil-py/issues/148 for details.

Here is a sample output:

```
uname(0x800000fddb90) = 0
I0806 16:03:04.784489 139707194705728 core_utils.py:73] uname(0x800000fddb90) = 0

brk(0x0)
I0806 16:03:04.786140 139707194705728 core_utils.py:73] brk(0x0)

brk(0x1198200)
I0806 16:03:04.786884 139707194705728 core_utils.py:73] brk(0x1198200)

arch_prctl(0x11978c0) = 0
I0806 16:03:04.788332 139707194705728 core_utils.py:73] arch_prctl(0x11978c0) = 0

...
```

One workaround suggested by the developer of absl-py is to set propagate to False by default. I can create a PR for the change if you are ok with it.

**Comment by xwings** [comment]
I dont understand. So you want to create a PR for absl-py ?

**Comment by kqyang** [comment]
@xwings Sorry for not making it clear. I'd like to set up the logger so it does not propagate to the root logger by default to avoid double printing, i.e.

```diff
diff --git i/qiling/utils.py w/qiling/utils.py
index 14373376..4b71c450 100644
--- i/qiling/utils.py
+++ w/qiling/utils.py
@@ -166,6 +166,7 @@ def ql_setup_logger(logger_name=None):
         logger_name = 'qiling_%s' % _counter

     logger = logging.getLogger(logger_name)
+    logger.propagate = False
     logger.setLevel(logging.DEBUG)
     return logger
```

**Comment by xwings** [comment]
@ucgJhe what do you think

**Comment by ucgJhe** [comment]
since we don't use propagation mechanism in qiling for now, disable it should be fine.

**Comment by xwings** [comment]
@kqyang a PR maybe ?

**Comment by kqyang** [comment]
Done: https://github.com/qilingframework/qiling/pull/442.
