### ISSUE TITLE
load library dependencies

### ISSUE THREAD

**Issue by aj3423** [qilingframework/qiling#451]
Some article says Qiling supports loading shared library dependencies automatically, but I did some test, seems not work.

To reproduce the problem, write a shared library *libso.so*, which depends on *libc*.
1. create a shared library with c code:
```
#include <stdio.h>

extern "C"
void test_print() {// offset: 0x1105
	puts("ok");
}
```
2.  python script:
```
from qiling import *

ql = Qiling(["/e/c/2/kali/libso.so"], "/e/c/2/kali", 
            output='debug',
            )

LIB_BASE = ql.loader.load_address

ql.run(
    begin = LIB_BASE + 0x1105, #0x1105 is function 'test_print'
    end = LIB_BASE+0x1117) #end of function 'test_print'
```
3. view the dependency of libso.so:
`objdump -x libso.so` shows:

    Dynamic Section:
      NEEDED               libc.so.6
      SONAME               libso.so
      .........
4. make sure the dependency directory and file exists:
   */e/c/2/kali/lib/libc.so.6*   which is linking to *libc-2.30.so*, make sure they both exists

5. run  the code, libc is not loaded, and crashes at function *puts*

Do I miss something?

**Comment by xwings** [comment]
you did partial execution.  but u dont have a snapshot information ?

**Comment by aj3423** [comment]
@xwings What do you mean by 'partial execution',  and 'snapshot' ...

**Comment by xwings** [comment]
https://docs.qiling.io/en/latest/snapshot/

**Comment by aj3423** [comment]
@xwings Thanks. The 'partial execution' example shows how to run from middle of a function, which requries the snapshot of previous state. But my example runs from beginning of a function, no 'previous state', isn't it ?

**Comment by aj3423** [comment]
@xwings Thanks. The 'partial execution' example shows how to run from middle of a function, which requries the snapshot of previous state. But my example runs from beginning of a function, no 'previous state', isn't it ?

**Comment by xwings** [comment]
i am not too sure. it seems u added begin and end. So, i assume u are forcing it run from some part of the binary

**Comment by aj3423** [comment]
@xwings  Yes, it's part of the binary, but the offsets are the begining and end of the function `test_print`. My purpose is loading a shared library and call some export function.

**Comment by aj3423** [comment]
Seems only executable loads dependencies automatically. As from the source code, QiLing will load interpreter like "ld-linux*.so.*" 
 if there is one, and the "ld-linux.so" will load all dependencies. But only executables have interpreter, that's why .so not loading any dependency.
Is that correct? If so, any plan to support it?

**Comment by xwings** [comment]
i still don't understand what are you trying to.

The design is rather simple, as long as its a elf, we will read the file according to how ELF should be loaded.

Check https://linux-audit.com/elf-binaries-on-linux-understanding-and-analysis/ or google how elf being loaded might help ?

**Comment by cuserdzy** [comment]
他大概问的是，模拟执行so中的部分代码时，为什么没有主动加载so文件的依赖。
但是看起来模拟可执行文件时会主动加载相关的依赖。
似乎在解析PT_DYNAMIC段时，对DT_NEEDED并没有做处理。

**Comment by aj3423** [comment]
@xwings For example, *my.so* depends on *libc.so*,  when I load *my.so* in qiling, I expect *libc.so* will be loaded automatically,  and function will be imported and filled in the .plt.  But it's not, so, error happens when *my.so* access these function, because the function address is still 0 in the .plt table.

**Comment by xwings** [comment]
what can u do is print out the disasm and see why it crash ?

**Comment by aj3423** [comment]
> what can u do is print out the disasm and see why it crash ?
It crashes because the code calls `puts()`, which is from *libc.so*, but *libc.so* is not loaded.

Here's the screenshot of using param `output='debug'` and `output='disasm'`: 
![2](https://user-images.githubusercontent.com/4710875/106032099-03219880-610b-11eb-9a0a-3c2c14e7de56.png)
![1](https://user-images.githubusercontent.com/4710875/106032113-07e64c80-610b-11eb-8cf5-706d0416066a.png)

**Comment by cq674350529** [comment]
@aj3423 According to your python scripts provided, you did partial execution. In your case, the shared library dependencies won't be loaded automatically. 
You can try to run full execution, and hijack the control flow in the entry point of `libso.so`. I came across a similar case: https://github.com/qilingframework/qiling/issues/593 .

**Comment by aj3423** [comment]
> @aj3423 According to your python scripts provided, you did partial execution. In your case, the shared library dependencies won't be loaded automatically.
> You can try to run full execution, and hijack the control flow at the entry point of `libso.so`. I came across a similar case: #593 .
> 
> That is, the recommend way to do partial execution is: run full execution first, then hijack the control flow at the entry point.

Thanks, got it .
