### ISSUE TITLE
example tendaac1518_httpd error

### ISSUE THREAD

**Issue by newthis** [qilingframework/qiling#453]
***Describe the bug**
I followed the instruction in the program tendaac1518_httpd.py and extract the firmware content.
However, when running , the below error appears:

Traceback (most recent call last):
  File "/home/test/PycharmProjects/pythonProject/TendaTest.py", line 79, in <module>
    my_sandbox(["rootfs/bin/httpd"], "rootfs")
  File "/home/test/PycharmProjects/pythonProject/TendaTest.py", line 73, in my_sandbox
    ql.run()
  File "/usr/local/lib/python3.7/dist-packages/qiling/core.py", line 198, in run
    self.os.run()
  File "/usr/local/lib/python3.7/dist-packages/qiling/os/linux/linux.py", line 123, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/usr/local/lib/python3.7/dist-packages/qiling/core.py", line 257, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.7/dist-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write 

the python version is 3.7.8 and the os is ubuntu 16.04， and qiling version is 1.1.post1

**Sample Code**
```python
    nvram_listener_therad = threading.Thread(target=nvram_listener, daemon=True)
    nvram_listener_therad.start()
    my_sandbox(["rootfs/bin/httpd"], "rootfs")
```

**Screenshots**
![a](https://user-images.githubusercontent.com/9391505/90462394-585c8580-e13b-11ea-8a24-d03aba18adca.PNG)

![b](https://user-images.githubusercontent.com/9391505/90462403-5db9d000-e13b-11ea-9822-c8ab864b0d2a.PNG)

**Comment by xwings** [comment]
are u on dev ?

**Comment by newthis** [comment]
u mean add_fs_mapper in the code for /dev path ?

**Comment by newthis** [comment]
The add_fs_mapper action has been added in the code:
ql.add_fs_mapper("/dev", "/dev"),
but the error still occurs.

**Comment by newthis** [comment]
![pic](https://user-images.githubusercontent.com/9391505/90581502-fe70c400-e1fd-11ea-9c63-16d73c49d012.PNG)

this is the detailed problem log

**Comment by xwings** [comment]
i mean did you checkout dev branch ?

**Comment by newthis** [comment]
no, it is not the dev branch.

**Comment by xwings** [comment]
checkout the dev branch ?

**Comment by xwings** [comment]
I found the issue and fixed it. It was an error in __newselect.
