### ISSUE TITLE
gdb-multiarch + gef bug with addition of qdb in dev branch

### ISSUE THREAD

**Issue by thelumberjhack** [qilingframework/qiling#460]
**Describe the bug**
Since the addition of qdb to the dev branch, gdb remote target fails to work properly. My intent was not to use qdb in the first place, since gdbserver + gdb/gef was working fine for me before those changes have been included in the code base.

**Sample Code**
```python
import sys
import argparse

from qiling import *

def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, output="none")
    ql.add_fs_mapper("/dev/urandom", "/dev/urandom")
    ql.add_fs_mapper("/tmp", "/var/tmp")
    ql.add_fs_mapper("/proc", "/proc")
    ql.debugger = True
    ql.run()


def main():
    parser = argparse.ArgumentParser(
        "encimg",
        description="Emulate firmware decryption from D-Link routers.",
        add_help=False
    )

    parser.add_argument(
        "-i", "--image", required=True, help="Firmware filename."
    )
    parser.add_argument(
        "-s", "--signature", required=True, help="Firmware signature."
    )

    parser.add_argument(
        "-r", "--rootfs", required=True, help="Root FS path"
    )

    try:
        args = parser.parse_args()

        path = [
            f"{args.rootfs}/usr/sbin/encimg",
            "-d",
            "-i", f"{args.image}",
            "-s", f"{args.signature}"
        ]

        my_sandbox(path, args.rootfs)

    except argparse.ArgumentError as err:
        print(f"[-] {err}")
        return -1


if __name__ == "__main__":
    main()
```

**Expected behavior**
GDB+GEF should work as in the screenshot below:
![Success](https://i.imgur.com/mGGIbqz.png)

Now it seems like ARM arch is not recognized and I get the following:

![gdbserver](https://i.imgur.com/sDTO6f8.png)

![gdb-multiarch](https://i.imgur.com/qo793rA.png)

**Comment by xwings** [comment]
Is the xml file there ?

**Comment by xwings** [comment]
i just tested seems like ok

![image](https://user-images.githubusercontent.com/463553/90713869-e6ba3e00-e2d8-11ea-935f-7992d34a167c.png)

**Comment by xwings** [comment]
the xml comes with the installer. should be always there

**Comment by thelumberjhack** [comment]
I installed qiling dev branch using the following command: `sudo -H python setup.py install` and it did not copy the files over.
I even try to uninstall and reinstall qiling and it was the same.

**Comment by xwings** [comment]
erm... @chfl4gs  any idea ?

**Comment by thelumberjhack** [comment]
Thanks for the fix @chfl4gs :)
