### ISSUE TITLE
Arguments not being passed on x64 windows binaries.

### ISSUE THREAD

**Issue by analyst321** [qilingframework/qiling#461]
**Describe the bug**
Arguments not being passed on x64 windows binary.

Reference sample: https://www.virustotal.com/gui/file/6e9617ebe9eba6e38f4b8559546dec381213c477736060029fd1376ce2b22840/detection

**Sample Code**
```python
from qiling import *

def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, profile="windows.ql")
    ql.run()

if __name__ == "__main__":
    my_sandbox(["/path/vv_max.exe", "FLARE2019", "cHCyrAHSXmEKpyqoCByGGuhFyCmy86Ee"], "/path/winrootfs/x8664_windows/")
```

**Expected behavior**
Argc/Argv should reflect and point to the passed arguments within the binary. However, argc in this case is 1 and argv does not contain the passed arguments.

**Comment by xwings** [comment]
Hi,

will you be able to debug and sent in a PR? It should work unless we mess it up. again.

**Comment by xwings** [comment]
close.
