### ISSUE TITLE
Difficulties to run the NetGear firmware in Qiling.io (syscall not implemented or AttributeError: 'NoneType' object has no attribute 'cur_thread')

### ISSUE THREAD

**Issue by YannQ404** [qilingframework/qiling#462]
Hello, 

after several test, I didn't succeed to run any Netgear Router firmware in Qiling. I tried several version of R6220 firmware (V1.1.0.31_1.0.1 , V1.0.0.14_1.0.1_FW and the last one 1.1.0.100). None of them have been succeeded to be launch in Qiling. 

**My .py script is** 
import sys
from qiling import *

def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, output="debug", profile = 'netgear_6220lastversion.ql', log_dir='qlog')
    ql.add_fs_mapper('/proc', '/proc')
    ql.run()

if __name__ == "__main__":
    my_sandbox(["rootfs/netgear_r6220/bin/mini_httpd","-d","/www","-r","NETGEAR R6220","-c","**.cgi","-t","300"], "rootfs/netgear_r6220")

My Profile .ql file contains the entry point of the Firmware I found with Binwalk and for those tested version it seems to be :  mmap_address = 0x8000F500 according to the abstracted result of binwalk below 

**Binwalk dump**
2097152       0x200000        uImage header, header size: 64 bytes, header CRC: 0xB7549F6B, created: 2014-09-17 08:50:27, image size: 2420721 bytes, Data Address: 0x80001000, **### Entry Point: 0x8000F500**, data CRC: 0xB59BD3D5, OS: Linux, CPU: MIPS, image type: OS Kernel Image, compression type: lzma, image name: "Linux Kernel Image"
2097216       0x200040        LZMA compressed data, properties: 0x5D, dictionary size: 33554432 bytes, uncompressed size: 7175104 bytes

HOWEVER, when I run the Python script to launch the emulation,  I received the following errors (different error for different firmware version) 

**1st error for older version is  :** 
setsockopt bind(3,127.0.0.1:8080,16) = 0
[+] syscall bind host: 127.0.0.1 and port: 8080 sin_family: 2
listen(3, 1024) = 0
[!] 0x775149d4: syscall ql_syscall_fork number = 0xfa2(4002) not implemented
exit(0) = 0

**2nd error for the newest version of the firmware is :** 
setsockopt
bind(4,127.0.0.1:8080,16) = 0
[+] syscall bind host: 127.0.0.1 and port: 8080 sin_family: 2
listen(4, 1024) = 0
[!] SYSCALL ERROR: ql_syscall_clone
[-] 'NoneType' object has no attribute 'cur_thread'
...
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/os/posix/syscall.py", line 2005, in ql_syscall_clone
    f_th = ql.thread_management.cur_thread    
AttributeError: 'NoneType' object has no attribute 'cur_thread'

Any idea how to overcome this issue? Could you tell me what is the R6220 firmware version you use during the demos? (It may helps me to reproduce it) 

Thanks 
Yann

**Comment by xwings** [comment]
you need to add ql.multithread = True

please refer to

https://docs.qiling.io/en/latest/faq/#syscall-not-implemented-or-attributeerror-nonetype-object-has-no-attribute-cur_thread-error

**Comment by YannQ404** [comment]
Great . It works.. I only have some classical "file not found" issue to correct now ... I continue my adventure to netgear emulation thanks to qiling.io :-)

Last errors to correct : bind(4,127.0.0.1:8080,16) = 0
[+] syscall bind host: 127.0.0.1 and port: 8080 sin_family: 2
listen(4, 1024) = 0
clone(new_stack = 0, flags = 1200012, tls = 0, ptidptr = 0, ctidptr = 77835068) = 3602
[+] Currently running pid is: 3597; tid is: 2000 
exit_group(0)
clone(new_stack = 0, flags = 1200012, tls = 0, ptidptr = 0, ctidptr = 77835068) = 0
[+] Currently running pid is: 3602; tid is: 3602 
setsid() = 3602
time() = 1597925331
open(/etc/TZ, 0x0, 0o0) = -2
[+] open(/etc/TZ, O_RDONLY, 0o0) = -2
[!] File Not Found /home/yann/qiling/examples/rootfs/netgear_r6220/etc/TZ
open(/etc/localtime, 0x0, 0o0) = -2
[+] open(/etc/localtime, O_RDONLY, 0o0) = -2
[!] File Not Found /home/yann/qiling/examples/rootfs/netgear_r6220/etc/localtime
getuid(1000)
chdir(/www) = -1 : Not Found
exit_group(1)

thanks a lot 
Yann
