### ISSUE TITLE
[Windows x64] Runtime library + call relative to RIP  

### ISSUE THREAD

**Issue by nongiach** [qilingframework/qiling#474]
Hello guys,

I hope you are doing well!

***Describe the bug**
I'm on a case where there is an "[!] Emulation Error" because PC/RIP is not at the correct value.
Bellow the steps to reproduce it:
Target: windows x64
Version: lastest version of this morning
host system: Linux pc 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux
Command: ./qltool  run -f examples/rootfs/x8664_windows/bin/target.exe --rootfs examples/rootfs/x8664_windows/ --disasm

**target.exe** is loading a **library.dll** with the **LoadLibrary** function at runtime.
So good so far, no problem to call a function in **library.dll** from **target.exe**.
The problem exists when we jump(call RDI in screenshot) in **library.dll** and perform a relative call from **libary.dll** to **library.dll** :
call qword ptr [rip + 0x2777a]
![qiling_error](https://user-images.githubusercontent.com/5711608/90977758-0d31e080-e548-11ea-86d5-89e8f25c2070.png)
 The debug output shows that RIP/PC is set to 0x37b3a which is not in library.dll at 0x7ffff02ce000

***Expected Behavior***
RIP should be => RIP = RIP+0x11b6 = 0x7ffff02d7138+0x11b6 = 0x7ffff02d82ee
And RIP should not be => RIP = 0x37b3a

Note: the expected target page is correctly mapped.

From my current understanding this might be an emulation error related calls to page loaded by LoadLibrary emulation.
How can I troubleshoot this?
I can privately package you the input and output files over twitter if you whish to reproduce the error.

Thank you.

@chaignc

**Comment by xwings** [comment]
Hi, can you trace which API is trowing out this erro ?
