### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by lucroida** [qilingframework/qiling#479]
**Probelm**
Its not clear how to contribute to Qiling. There seems to be pieces explaining how to contribute sitting around in commits and docs (e.g. [adding syscall and OS API](https://docs.qiling.io/en/latest/syscall_api/) but I don't see a single place for contribution guidelines.

**Proposed Solution**
Create a `CONTRIBUTORS.md` detailing the process of contributing to Qiling.

**Comment by xwings** [comment]
Your PR is perfect! 

Thanks you.
