### ISSUE TITLE
chdir syscall seens to break open syscall paths

### ISSUE THREAD

**Issue by racerxdl** [qilingframework/qiling#484]
**Describe the bug**
It seems that changing directory breaks the path. If I dont call `chdir` the `fopen` calls return a handler and can read the file correctly. After changing the directory the `fopen` call returns 0. Maybe its always trying to load relative?

**Sample Code**
```python
from qiling import *

def my_sandbox(path, rootfs):
    # setup Qiling engine
    ql = Qiling(path, rootfs, env={
      "PWD": "/hooks",
      "SHELL": "/bin/bash",
      "HOME": "/root",
    }, archtype="x86", ostype="linux", profile="linux.ql")
    ql.run()

if __name__ == "__main__":
  my_sandbox(["./env/testprog"], "env")
```
```c
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>

int main() {
	chdir("/mnt/hd/");
	char data[4096];
	FILE *f = fopen("/SAVE/PRI/mnt", "r");
	printf("FILE: %p\n", f);
	fread(data, 4096, 1, f);
	fclose(f);
	printf("Data: %s\n", data);
	return 0;
}
```

`/SAVE/PRI/mnt` file content:
```
hddd /mnt/hd
```

C Code compiled with:
```bash
gcc -m32 testprog.c -o testprog
```

**Expected behavior**
A absolute path `fopen` to works regardless of the directory I'm in.

**Screenshots**

If remove the `chdir` call from the C code and run, the program works as expected:
```
munmap(0x774bf000, 0xd000) = 0
brk(0x0)
brk(0x5657b000)
brk(0x5657c000)
openat(-100, /SAVE/PRI/mnt, 0x0, 0o0) = 3
fstat64(1, 0x89f0b7cc) = 0
write(1,5655a2c0,17) = 0
FILE: 0x5655a160
fstat64(3, 0x89f0bcec) = 0
read(3, 0x89f0be3c, 0x1000) = 14
read(3, 0x89f0be4a, 0xc00) = 0
close(3) = 0
brk(0x5657b000)
write(1,5655a2c0,20) = 0
Data: hddd /mnt/hd 
write(1,5655a2c0,1) = 0

exit_group(0)
```

But if its there (changing the current folder), the open call for the absolute path fails.

```
chdir(/mnt/hd/game) = 0
brk(0x0)
brk(0x5657b000)
brk(0x5657c000)
openat(-100, /SAVE/PRI/mnt, 0x0, 0o0) = -1
fstat64(1, 0x89f0b7cc) = 0
write(1,5655a2c0,8) = 0
FILE: 0
[!] Emulation Error
```

**Additional context**

If I copy the file to `/mnt/hd/SAVE/PRI/mnt` the program works as expected, indicating openat is not respecting the absolute paths.

`env` is a 32 bit linux folder chroot environment (created with debootstrap)

**Comment by xwings** [comment]
I dont understand your script.

I did not see rootfs in your script ? and you turn rootfs into env ?

**Comment by racerxdl** [comment]
Hi @xwings, sorry I think I wasn't clear about the folder structure.

The `env` is a folder containing a linux32 envinronment (a complete chroot env):
![image](https://user-images.githubusercontent.com/578310/91641211-3d222d80-e9f9-11ea-9a52-38d12c028a42.png)

So in my computer I have a folder with the python script, the `env` folder. Inside env folder I have the `/mnt/hd` folder (which is the one I chdir to) and I also have `/SAVE/PRI/mnt`.

So for my host computer, thats the folders:

`env/mnt/hd`
`env/SAVE/PRI`

So the testprog (which is in C) is running inside the rootfs `env`. If it access `/SAVE/PRI/mnt` it is expected that it will access `env/SAVE/PRI/mnt`, which does happen if I dont call `chdir` before acessing it.

If a leading `/` is on `fopen`, it is expected to be a **absolute** path and not relative, so it should always load `env/SAVE/PRI/mnt` regardless of the folder sandbox is in. Because the `/` is expected to point to `rootfs` (in that case is `env` folder)

**Comment by xwings** [comment]
@wtdcode maybe can u take a look at the real_path transformation again. I guess after chdir we got things screwed up ?

**Comment by wtdcode** [comment]
Below is the current implementation of `chdir`, which is a complete mess.

```python
def ql_syscall_chdir(ql, path_name, *args, **kw):
    regreturn = 0
    pathname = ql.mem.string(path_name)

    real_path = ql.os.transform_to_real_path(pathname)
    relative_path = ql.os.transform_to_relative_path(pathname)

    if os.path.exists(real_path) and os.path.isdir(real_path):
        if ql.os.thread_management != None:
            pass
        else:
            ql.os.current_path = relative_path + '/'
        ql.nprint("chdir(%s) = %d"% (relative_path, regreturn))
    else:
        regreturn = -1
        ql.nprint("chdir(%s) = %d : Not Found" % (relative_path, regreturn))
    ql.os.definesyscall_return(regreturn)
```

Obviously, the thing goes wrong since it uses `relative_path`. Besides,`ql.os.current_path` is supposed to start with a `/`, but `relative_path + '/'` won't meet that requirement. The fix should be pretty simple with pathlib.

But I'm considering a new function to concatenate `cwd` and another path. Also, we need to check if there are some other codes concatenate `cwd` directly and some tests should be made. I will draft a PR these days.

**Comment by xwings** [comment]
@racerxdl i guess its good for us to build this into our test.

would you be able to,

1.  upload the src to example/src/linux
2. put the binary in rootfs/x8664_linux/bin 
3. create a test in tests/test_elf.py

while waiting for @wtdcode to clean ip the messy code

**Comment by xwings** [comment]
@racerxdl will you be able to give a quick test ?

**Comment by racerxdl** [comment]
Hi @xwings / @wtdcode sorry just saw the messages now. I just tested and now its working as expected :D

```
brk(0x0)
uname(0x89f0caa2) = 0
access(/etc/ld.so.nohwcap, 0x0) = -1 
access(/etc/ld.so.preload, 0x4) = -1 
openat(-100, /etc/ld.so.cache, 0x80000, 0o0) = 3
fstat64(3, 0x89f0c6e8) = 0
mmap2(0x0, 0xc99a, 0x1, 0x2, 3, 0) = 0x774bf000
close(3) = 0
access(/etc/ld.so.nohwcap, 0x0) = -1 
openat(-100, /lib/i386-linux-gnu/libc.so.6, 0x80000, 0o0) = 3
read(3, 0x89f0c818, 0x200) = 512
fstat64(3, 0x89f0c748) = 0
mmap2(0x0, 0x2000, 0x3, 0x22, -1, 0) = 0x774cc000
mmap2(0x0, 0x1dba1c, 0x5, 0x802, 3, 0) = 0x774ce000
mmap2(0x776a4000, 0x3000, 0x3, 0x812, 3, 1921024) = 0x776a4000
mmap2(0x776a7000, 0x2a1c, 0x3, 0x32, -1, 0) = 0x776a7000
close(3) = 0
set_thread_area(u_info_addr= 0x89f0cc28)
munmap(0x774bf000, 0xd000) = 0
chdir(/mnt/hd) = 0
brk(0x0)
brk(0x5657b000)
brk(0x5657c000)
openat(-100, /SAVE/PRI/mnt, 0x0, 0o0) = 3
fstat64(1, 0x89f0b7cc) = 0
write(1,5655a2c0,17) = 0
FILE: 0x5655a160
fstat64(3, 0x89f0bcec) = 0
read(3, 0x89f0be3c, 0x1000) = 14
read(3, 0x89f0be4a, 0xc00) = 0
close(3) = 0
brk(0x5657b000)
write(1,5655a2c0,20) = 0
Data: hddd /mnt/hd 
write(1,5655a2c0,1) = 0

exit_group(0)
```
