### ISSUE TITLE
The simulation of MIPS file error,  qiling. Exception. QlErrorCoreHook: _hook_intr_cb: catched == False

### ISSUE THREAD

**Issue by ttoon123001** [qilingframework/qiling#491]
***Describe the bug**
I notice that MIPS defines the call number as 17, while hook_intr_cb's intno gives 26

Relevant logs are as follows：
[+] load 0x400000 - 0x40f000
[+] load 0x410000 - 0x411000
[+] load 0x411000 - 0x472000
[+] mem_start: 0x400000 mem_end: 0x472000
[+] mmap_address is : 0xf7764000
open(/proc/self/exe, 0x0, 0o0) = 3
[+] open(/proc/self/exe, O_RDONLY, 0o0) = 3
[+] File Found: /proc/self/exe
[+] log mmap - mmap(0x0, 0xe7f8, 0x3, 0x802, 2146684688, 2146684692)
[+] log mmap - mmap(0x0, 0xe7f8, PROT_READ | PROT_WRITE, MAP_PRIVATE | 2048, 2146684688, 2146684692)
[+] log mmap - return addr : 0xf7764000
[+] log mmap - addr range  : 0xf7764000 - 0xf7773000
[+] log mmap - mapping needed
[+] mmap_base 0xf7764000  length 0xf000
[+] Start      End        Perm.  Path
[+] 00400000 - 0040f000 - r-x    /root/Desktop/mips32_upx
[+] 00410000 - 00411000 - rw-    /root/Desktop/mips32_upx
[+] 00411000 - 00472000 - rwx    /root/Desktop/mips32_upx
[+] 00472000 - 00474000 - rwx    hook mem
[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[+] f7764000 - f7773000 - rwx    [mapped]
mmap(0x0, 0xe7f8, 0x3, 0x802, -1, 0) = 0xf7764000
[+] mmap_base is 0xf7764000
[+] log mmap - mmap(0xf7764000, 0xe471, 0x3, 0x12, 2146684688, 2146684692)
[+] log mmap - mmap(0xf7764000, 0xe471, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FIXED, 2146684688, 2146684692)
[+] mmap_addr 0xf7764000 < ql.loader.mmap_address 0xf7773000
[+] log mmap - return addr : 0xf7764000
[+] log mmap - addr range  : 0xf7764000 - 0xf7773000
[+] mmap_base 0xf7764000  length 0xf000
[+] Start      End        Perm.  Path
[+] 00400000 - 0040f000 - r-x    /root/Desktop/mips32_upx
[+] 00410000 - 00411000 - rw-    /root/Desktop/mips32_upx
[+] 00411000 - 00472000 - rwx    /root/Desktop/mips32_upx
[+] 00472000 - 00474000 - rwx    hook mem
[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[+] f7764000 - f7773000 - rwx    [mapped]
[+] log mem wirte : 0xf000
[+] log mem mmap  : ../mips32_upx
mmap(0xf7764000, 0xe471, 0x3, 0x12, 3, 0) = 0xf7764000
[+] mmap_base is 0xf7764000
Traceback (most recent call last):
  File "/root/Desktop/qiling-master/qiling/utils.py", line 19, in wrapper
python-BaseException
    return func(*args, **kw)
  File "/root/Desktop/qiling-master/qiling/core_hooks.py", line 122, in _hook_intr_cb
    raise QlErrorCoreHook("_hook_intr_cb : catched == False")
qiling.exception.QlErrorCoreHook: _hook_intr_cb : catched == False

Disassembly error location：
[+] 0x40dc88       04 11 00 29                   bal 0x40dd30
[+] 0x40dc8c       00 a0 88 21                   move $s1, $a1
[+] 0x40dd30       24 09 00 00                   addiu $t1, $zero, 0
[+] 0x40dd34       24 06 00 03                   addiu $a2, $zero, 3
[+] 0x40dd38       27 bd ff e0                   addiu $sp, $sp, -0x20
[+] 0x40dd3c       af a8 00 10                   sw $t0, 0x10($sp)
[+] 0x40dd40       af a9 00 14                   sw $t1, 0x14($sp)
[+] 0x40dd44       24 02 0f fa                   addiu $v0, $zero, 0xffa
[+] 0x40dd48       00 00 00 0c                   syscall 
[+] Start      End        Perm.  Path
[+] 00400000 - 0040f000 - r-x    /root/Desktop/mips32_upx
[+] 00410000 - 00411000 - rw-    /root/Desktop/mips32_upx
[+] 00411000 - 00472000 - rwx    /root/Desktop/mips32_upx
[+] 00472000 - 00474000 - rwx    hook mem
[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[+] f7764000 - f7773000 - rwx    [mapped]
mmap(0x0, 0xe7f8, 0x3, 0x802, -1, 0) = 0xf7764000
[+] 0x40dd4c       14 e0 00 03                   bnez $a3, 0x40dd5c
[+] 0x40dd50       00 00 00 00                   nop 
[+] 0x40dd54       03 e0 00 08                   jr $ra
[+] 0x40dd58       27 bd 00 20                   addiu $sp, $sp, 0x20
[+] 0x40dc90       af a2 00 18                   sw $v0, 0x18($sp)
[+] 0x40dc94       8e 82 00 04                   lw $v0, 4($s4)
[+] 0x40dc98       02 33 28 22                   sub $a1, $s1, $s3
[+] 0x40dc9c       8f a8 00 14                   lw $t0, 0x14($sp)
[+] 0x40dca0       24 07 00 12                   addiu $a3, $zero, 0x12
[+] 0x40dca4       00 a2 28 20                   add $a1, $a1, $v0
[+] 0x40dca8       04 11 00 21                   bal 0x40dd30
[+] 0x40dcac       8f a4 00 18                   lw $a0, 0x18($sp)
[+] 0x40dd30       24 09 00 00                   addiu $t1, $zero, 0
[+] 0x40dd34       24 06 00 03                   addiu $a2, $zero, 3
[+] 0x40dd38       27 bd ff e0                   addiu $sp, $sp, -0x20
[+] 0x40dd3c       af a8 00 10                   sw $t0, 0x10($sp)
[+] 0x40dd40       af a9 00 14                   sw $t1, 0x14($sp)
[+] 0x40dd44       24 02 0f fa                   addiu $v0, $zero, 0xffa
[+] 0x40dd48       00 00 00 0c                   syscall 
[+] Start      End        Perm.  Path
[+] 00400000 - 0040f000 - r-x    /root/Desktop/mips32_upx
[+] 00410000 - 00411000 - rw-    /root/Desktop/mips32_upx
[+] 00411000 - 00472000 - rwx    /root/Desktop/mips32_upx
[+] 00472000 - 00474000 - rwx    hook mem
[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[+] f7764000 - f7773000 - rwx    [mapped]
mmap(0xf7764000, 0xe471, 0x3, 0x12, 3, 0) = 0xf7764000
[+] 0x40dd4c       14 e0 00 03                   bnez $a3, 0x40dd5c
[+] 0x40dd50       00 00 00 00                   nop 
[+] 0x40dd54       03 e0 00 08                   jr $ra
[+] 0x40dd58       27 bd 00 20                   addiu $sp, $sp, 0x20
[+] 0x40dcb0       00 55 90 22                   sub $s2, $v0, $s5
[+] 0x40dcb4       03 c0 f8 21                   move $ra, $fp
[+] 0x40dcb8       03 d2 f0 20                   add $fp, $fp, $s2
[+] 0x40dcbc       8e 90 ff fc                   lw $s0, -4($s4)
[+] 0x40dcc0       26 84 00 0c                   addiu $a0, $s4, 0xc
[+] 0x40dcc4       02 92 a0 20                   add $s4, $s4, $s2
[+] 0x40dcc8       02 93 48 20                   add $t1, $s4, $s3
[+] 0x40dccc       03 dc 40 24                   and $t0, $fp, $gp
[+] 0x40dcd0       af a8 00 08                   sw $t0, 8($sp)
[+] 0x40dcd4       01 28 48 22                   sub $t1, $t1, $t0
[+] 0x40dcd8       af a9 00 0c                   sw $t1, 0xc($sp)
[+] 0x40dcdc       82 88 00 08                   lb $t0, 8($s4)
Traceback (most recent call last):
  File "/root/Desktop/qiling-master/qiling/utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "/root/Desktop/qiling-master/qiling/core_hooks.py", line 122, in _hook_intr_cb
    raise QlErrorCoreHook("_hook_intr_cb : catched == False")
qiling.exception.QlErrorCoreHook: _hook_intr_cb : catched == False
python-BaseException

Process finished with exit code 1

**Comment by xwings** [comment]
We need to test more. 

Is this mips MSB or something ?

**Comment by ttoon123001** [comment]
It's mips MSB, but it has UPX. 

I am making it possible to perform UPX mips, but the above issues arise

**Comment by ttoon123001** [comment]
> We need to test more.
> 
> Is this mips MSB or something ?

It's mips MSB, but it has UPX.

I am making it possible to perform UPX mips, but the above issues arise

**Comment by ucgJhe** [comment]
packed binary sometimes use odd syscall for memory mapping , can you provide the sample ?

**Comment by xwings** [comment]
I am not too sure will MSB mps + upx will "create" this issue. like @ucgJhe  if there is a sample we can test

**Comment by xwings** [comment]
same issue with #521 i guess we need more test with MSB

**Comment by xwings** [comment]
This should be solved with the latest version of Qiling.
