### ISSUE TITLE
ELF aarch64 loader doesn't support .init_array segment

### ISSUE THREAD

**Issue by stevemk14ebr** [qilingframework/qiling#502]
***Describe the bug**
A C++ binary with an empty DLL main but global C++ object constructors within the .init_array segment crashes. It appears the ELF loader doesn't execute the function pointer table to call the C++ constructors in the .init_array section.

**Sample Code**
```python
from qiling import *

def my_sandbox(path, rootfs):
    # setup Qiling engine
    ql = Qiling(path, rootfs)
    ql.run()

if __name__ == "__main__":
    # execute Windows EXE under our rootfs
    my_sandbox(["C:\\users\\User\\bad_elf"], "C:\\users\\User\\bad_elf\\analysis")
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6619205/92534077-e50dd700-f201-11ea-96e6-d908cf42df2e.png)

![image](https://user-images.githubusercontent.com/6619205/92534220-403fc980-f202-11ea-8ebd-4a47167e3b99.png)

![image](https://user-images.githubusercontent.com/6619205/92534267-58afe400-f202-11ea-9b27-15d8a8817cd8.png)

![image](https://user-images.githubusercontent.com/6619205/92534342-809f4780-f202-11ea-8764-abd8d1fcd3e6.png)

**Additional context**
The sample is private unfortunately, but i will share later if possible.  It's an aarch64 .so with dynamic libc linking.

**Comment by xwings** [comment]
looks like the loader did not plan for this,  my bad.

will you be able to do a PR to fix this ?

**Comment by stevemk14ebr** [comment]
I will not be able to PR, I am just getting started with Qiling I am not yet familiar enough with it. Be aware there are other .init/.fini type segments which need handling too.

**Comment by xwings** [comment]
we already merge in pyelftools. it should not be hard to call in  .init/.fini

But what is the error msg ?
