### ISSUE TITLE
异常: 无法运行例子

### ISSUE THREAD

**Issue by cryzlasm** [qilingframework/qiling#51]
![image](https://user-images.githubusercontent.com/20424580/70771204-2c952e80-1d68-11ea-8af3-55c72b6a0e79.png)
![image](https://user-images.githubusercontent.com/20424580/70771216-35860000-1d68-11ea-94f8-baa95afe6c30.png)
![image](https://user-images.githubusercontent.com/20424580/70771251-5189a180-1d68-11ea-9c31-ae0f6001bab1.png)

**Comment by cryzlasm** [comment]
keystone 已手动安装  
![image](https://user-images.githubusercontent.com/20424580/70771309-8b5aa800-1d68-11ea-82ff-91fb9d2bc4e5.png)

**Comment by xwings** [comment]
As of now, we still have not figure out who should we make Qiling Framework fully. As mention in issue #24  

We can run PE files emulation in Windows without an issue, you can check how we make the installation in .travis file

**Comment by xwings** [comment]
Please look at the example on how to run Qiling

**Comment by cryzlasm** [comment]
这个是在虚拟机里边, 我在外边没出现这个问题

![image](https://user-images.githubusercontent.com/20424580/70773040-3588fe80-1d6e-11ea-9ee5-7c2bfbbb3146.png)

**Comment by xwings** [comment]
> 这个是在虚拟机里边, 我在外边没出现这个问题
> 
> ![image](https://user-images.githubusercontent.com/20424580/70773040-3588fe80-1d6e-11ea-9ee5-7c2bfbbb3146.png)

Windows 的安装方式在 .travis.yml 有详细的步骤

**Comment by cryzlasm** [comment]
python  安装 setup的问题
![image](https://user-images.githubusercontent.com/20424580/70773493-864d2700-1d6f-11ea-991e-667d1f1723b4.png)

外边生成的egg 拉进去 可以用了,  啥时候官方出一个EGG这玩意吧
[qiling-0.9-py3.7.egg.zip](https://github.com/qilingframework/qiling/files/3959270/qiling-0.9-py3.7.egg.zip)

**Comment by xwings** [comment]
Due to we are still in very active development. No point we we need to make a deployment package. Once we think we are good for release 1.0, pip should do the magic

By the way. have you tried to run python setup.py ?

**Comment by cryzlasm** [comment]
是的  使用命令  python setup.py install
