### ISSUE TITLE
Problem with qiling

### ISSUE THREAD

**Issue by bigger777** [qilingframework/qiling#52]
Hello, could you help me? I have some error when i try to run a crackme and i don't know what is it means
Out text:
WARNING: Registry files format error['  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/os/windows/registry.py", line 71, in __init__\n    self.hklm[\'SAM\'] = Registry.Registry(os.path.join(self.hive, \'SAM\'))\n']
[+] Loading /home/bigger777/any/qiling/examples/rootfs/x86_windows/bin/ch15.exe to 0x400000
[+] PE entry point at 0x4014e0
[+] Initiate stack address at 0xfffdd000
[+] TEB addr is 0x6000
[+] PEB addr is 0x6044
[+] Loading /home/bigger777/any/qiling/examples/rootfs/x86_windows/dlls/kernel32.dll to 0x10000000
[+] Done with loading /home/bigger777/any/qiling/examples/rootfs/x86_windows/dlls/kernel32.dll
[+] Loading /home/bigger777/any/qiling/examples/rootfs/x86_windows/dlls/msvcrt.dll to 0x100d5000
[+] Done with loading /home/bigger777/any/qiling/examples/rootfs/x86_windows/dlls/msvcrt.dll
[+] Done with loading /home/bigger777/any/qiling/examples/rootfs/x86_windows/bin/ch15.exe
WARNING: Registry files format error['  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/os/windows/registry.py", line 71, in __init__\n    self.hklm[\'SAM\'] = Registry.Registry(os.path.join(self.hive, \'SAM\'))\n']
0x10015e60: GetSystemTimeAsFileTime(lpSystemTimeAsFileTime = 0xffffcfcc)
0x10023c00: GetCurrentProcessId() = 0x3e8
0x10011a60: GetCurrentThreadId() = 0x0
0x10023130: GetTickCount() = 0x30d40
0x10017f40: QueryPerformanceCounter(lpPerformanceCount = 0xffffcfc4) = 0x0
0x1013b4c0: _initterm(pfbegin = 0x40700c, pfend = 0x407018)
0x1013b4c0: _initterm(pfbegin = 0x407000, pfend = 0x407008)
0x10019ca0: SetUnhandledExceptionFilter(lpTopLevelExceptionFilter = 0x401520) = 0x4
0x10018f60: GetModuleHandleA(lpModuleName = "msvcrt.dll") = 0x100d5000
[!] 'hook_GetProcAddress' is not implemented

**Comment by xwings** [comment]
Windows API GetProcAddress is not implemented. It will be great if you able to implement it.

**Comment by bigger777** [comment]
How can I do it?

**Comment by xwings** [comment]
We implemented tons of Windows API and still long way to go. Community is helping.

Information about GetProcAddress is here.
https://docs.microsoft.com/en-us/cpp/build/getprocaddress?view=vs-2019
