### ISSUE TITLE
set_api not working on MIPS MSB ELF binary

### ISSUE THREAD

**Issue by nezza** [qilingframework/qiling#522]
**Describe the bug**
Trying to call set_api('realpath'..) on the attached binary fails (does nothing).

Attached is the target binary: 
[uhttpd.zip](https://github.com/qilingframework/qiling/files/5249869/uhttpd.zip)

**Sample Code**
```python
def my_realpath(ql):
    # Never reached
    ql.nprint("realpath hook")

ql = Qiling(["rootfs/usr/sbin/uhttpd", "-h", "/www", "-p", "8080", "-f"], "rootfs/", output = "dump")
ql.set_api('realpath', my_realpath)
ql.run()
```

**Expected behavior**
`my_realpath` should be executed.

**Additional context**
In experimentation I found that in `add_function_hook_mips` the `symidx in range...` loop is not working as intended, for example, replacing:

```
for symidx in range(self.mips_gotsym, self.mips_symtabno):
```
with
```
for symidx in range(0, self.mips_symtabno):
```
allows it to actually find the symbol, though the hook is still not called.

**Comment by xwings** [comment]
will chose this seems its a related issue with #521

**Comment by nezza** [comment]
Thanks for the quick response, I think the only similarity is that both are MIPS MSB? Should I create a tracking ticket for MIPS MSB issues? Cheers!

**Comment by xwings** [comment]
I guess we leave 521 there. These two are both MSB related and i suspect once fix. we will fix all the similarity issue.
