### ISSUE TITLE
ELF loader doesn't handle relocations

### ISSUE THREAD

**Issue by kttyb0f** [qilingframework/qiling#523]
***Describe the bug**
to load an ELF properly at all, relocations must be applied. qiling does not, other than printing glob_dat/jmp_slot out in function_hook.py (please refactor relocation parsing into the loader, whoever does a PR)

particularly on aarch64, you are not going to emulate anything properly without relocations applied. 

here is an example of what needs to be implemented: https://android.googlesource.com/platform/bionic/+/refs/tags/android-8.1.0_r1/linker/linker.cpp#2621

just a tracking issue. maybe someone knows of an existing python ELF linker implementation that can be leveraged, it can be annoying translating from r_offset to VA-mapped-offset.

**Comment by xwings** [comment]
"particularly on aarch64, you are not going to emulate anything properly without relocations applied."

I do remember we tested some aarch64 IoT based smart speakers and it will works.

So, the only thing we can suspect now is, this is a very Android related issue. Another team is working on the Android implementation (Android is not too similar with linux of coz) and i dont have a date for release but i do hope it come in soon.

**Comment by kttyb0f** [comment]
test with more than hello world, do your test targets have an empty relocation table??? R_X86_64_64 is a thing. it's not android-specific, it's a matter of having any proper linker implementation at all...

**Comment by xwings** [comment]
Buddy,

Things are simple here. We are only few of us and spend our free time to make this thing free for community.

As of now, we have like 50+ contributors. These are the people that think our projects is sucks in some way and spend time to pull request. All of us have a daily job that pays the bill.

Like what you can see from the commits and do some simple maths. We used up all our time for this. Features update are pretty much often. In the process and add /remove code we break or delete code is pretty much normal, as our build test is really not complete.

I do appreciate any form of pull request or any help in the project. I do appreciate the suggest, if possible will be may more better if you able to help to contribute code. You know, talk is always cheap. 

Really to hope to see a proper pull request from you. Not any bullshit like amazon jungle. Unless you are Starlink tester, testing their network connection and fishing Peacock Bass at the same time.

**Comment by xwings** [comment]
Again, please provide a test binary so @w1tcher might be able to take a look

**Comment by w1tcher** [comment]
The relocation work is done by ld.so and has nothing to do with loader. If there is no ld.so, we will go back to do relocation, but in the case of ld.so, the relocation can be completely handed over to ld.so To deal with.

**Comment by kttyb0f** [comment]
> The relocation work is done by ld.so and has nothing to do with loader. If there is no ld.so, we will go back to do relocation

where is the code that finds+drops into ld.so at emulation start for process init? very interesting project layout.

**Comment by w1tcher** [comment]
You can see the code you want to see here.
https://github.com/qilingframework/qiling/blob/master/qiling/loader/elf.py#L212
