### ISSUE TITLE
ld-linux.so.3 with syscall_map got  struct.error: argument out of range

### ISSUE THREAD

**Issue by alan717** [qilingframework/qiling#525]
***Describe the bug**
I aim try to emulate a embed binary execute with Qiling, i copy the embed device (arm Linux) ld-linux.so.3 and the binary needed library , with this ld-linux.so.3 i got the syscall_map  error message beblow. It was a struct  argument out of range error.
please  help me figure out  what the problem was,i will fix it  with  my hand. thank a lot!

**Sample Code**
```python
ql = Qiling(["rootfs/arm_linux/bin/control_bin"], "rootfs/arm_linux")
ql.run()
```

**Expected behavior**
success log the binary and get the main loop run. 

**Screenshots**
 here is my rootfs layout pic.
![sss](https://user-images.githubusercontent.com/8288681/93837385-77a97e00-fcb8-11ea-8473-36bc20c4d748.png)

**Additional context**
  here is the error log.
 
[clear log is here ](https://gist.github.com/alan717/17343e710a6d53fcaeb3f914bf794422)

**Comment by xwings** [comment]
This is a know issue of base platform is Windows. Maybe u can try under wsl2 for now ?

**Comment by alan717** [comment]
> This is a know issue of base platform is Windows. Maybe u can try under wsl2 for now ?

Thanks .I would try it.

**Comment by alan717** [comment]
> This is a know issue of base platform is Windows. Maybe u can try under wsl2 for now ?

It's works,Qiling is a great project!
