### ISSUE TITLE
TypeError: string argument expected, got 'bytearray'

### ISSUE THREAD

**Issue by zbx911** [qilingframework/qiling#535]
Testing started at 8:27 ...
D:\Anaconda3_x64_2020_7\python.exe "C:\PyCharm 2020.2.1\plugins\python\helpers\pydev\pydevd.py" --multiproc --save-signatures --qt-support=auto --client 127.0.0.1 --port 52849 --file "C:\PyCharm 2020.2.1\plugins\python\helpers\pycharm\_jb_unittest_runner.py" --path M:/qiling/qiling-learn/tests/test_android.py
pydev debugger: process 11500 is connecting

Connected to pydev debugger (build 202.6948.78)
Launching unittests with arguments python -m unittest M:/qiling/qiling-learn/tests/test_android.py in M:\qiling\qiling-learn\tests

[+] load 0x555555554000 - 0x555555555000
[+] load 0x555555555000 - 0x555555557000
[+] mem_start: 0x0 mem_end: 0x3000
[+] interp is : ../examples/rootfs/arm64_android/system/bin/linker64
[+] interp_mem_size is : 0x15d000
[+] interp_address is : 0x7ffff7dd5000
[+] mmap_address is : 0x7fffb7dd6000
[+] rel name b'__register_atfork'
[+] rel name b'puts'
[+] rel name b'__libc_init'
[+] rel name b'__cxa_atexit'
[+] log mmap - mmap(0x0, 0x5000, 0x0, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x5000, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7dd6000
[+] log mmap - addr range  : 0x7fffb7dd6000 - 0x7fffb7ddb000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dd6000  length 0x5000
mmap(0x0, 0x5000, 0x0, 0x22, 4294967295, 0) = 0x7fffb7dd6000
[+] mmap_base is 0x7fffb7dd6000
prctl() = 0
mprotect(0x7fffb7dd7000, 0x3000, 0x3) = 0
[+] mprotect(0x7fffb7dd7000, 0x3000, PROT_READ | PROT_WRITE) = 0
prctl() = 0
set_tid_address(7ffff7f2c9c0) = 11500
facccessat (4294967196, 0x7ffff7e93972, 0x4) = -1
[!] File Not Found or Skipped: /dev/urandom
futex(7ffff7f29268, 129, 2147483647) = 0
[+] log mmap - mmap(0x0, 0x5000, 0x3, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x5000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7ddb000
[+] log mmap - addr range  : 0x7fffb7ddb000 - 0x7fffb7de0000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7ddb000  length 0x5000
mmap(0x0, 0x5000, 0x3, 0x22, 4294967295, 0) = 0x7fffb7ddb000
[+] mmap_base is 0x7fffb7ddb000
mprotect(0x7fffb7ddb000, 0x1000, 0x0) = 0
[+] mprotect(0x7fffb7ddb000, 0x1000, PROT_NONE) = 0
[!] 0x7ffff7e854d8: syscall ql_syscall_sigaltstack number = 0x84(132) not implemented
prctl() = 0
prctl() = 0
mprotect(0x7ffff7eba000, 0x4000, 0x1) = 0
[+] mprotect(0x7ffff7eba000, 0x4000, PROT_READ) = 0
mprotect(0x7ffff7f2b000, 0x1000, 0x1) = 0
[+] mprotect(0x7ffff7f2b000, 0x1000, PROT_READ) = 0
mprotect(0x7ffff7f2b000, 0x1000, 0x3) = 0
[+] mprotect(0x7ffff7f2b000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7ffff7f2b000, 0x1000, 0x1) = 0
[+] mprotect(0x7ffff7f2b000, 0x1000, PROT_READ) = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7de0000
[+] log mmap - addr range  : 0x7fffb7de0000 - 0x7fffb7de1000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de0000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 4294967295, 0) = 0x7fffb7de0000
[+] mmap_base is 0x7fffb7de0000
prctl() = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
getrandom(0x80000000ca00, 0x28, 0x1) = 40
[+] log mmap - mmap(0x0, 0x450, 0x3, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x450, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7de1000
[+] log mmap - addr range  : 0x7fffb7de1000 - 0x7fffb7de2000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de1000  length 0x1000
mmap(0x0, 0x450, 0x3, 0x22, 4294967295, 0) = 0x7fffb7de1000
[+] mmap_base is 0x7fffb7de1000
prctl() = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de2000
[+] log mmap - addr range  : 0x7fffb7de2000 - 0x7fffb7de3000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de2000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7de2000
[+] mmap_base is 0x7fffb7de2000
prctl() = 0
[+] log mmap - mmap(0x0, 0x18, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x18, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de3000
[+] log mmap - addr range  : 0x7fffb7de3000 - 0x7fffb7de4000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de3000  length 0x1000
mmap(0x0, 0x18, 0x3, 0x22, 0, 0) = 0x7fffb7de3000
[+] mmap_base is 0x7fffb7de3000
prctl() = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de4000
[+] log mmap - addr range  : 0x7fffb7de4000 - 0x7fffb7de5000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de4000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7de4000
[+] mmap_base is 0x7fffb7de4000
prctl() = 0
[+] log mmap - mmap(0x0, 0x18, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x18, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de5000
[+] log mmap - addr range  : 0x7fffb7de5000 - 0x7fffb7de6000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de5000  length 0x1000
mmap(0x0, 0x18, 0x3, 0x22, 0, 0) = 0x7fffb7de5000
[+] mmap_base is 0x7fffb7de5000
prctl() = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de6000
[+] log mmap - addr range  : 0x7fffb7de6000 - 0x7fffb7de7000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de6000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7de6000
[+] mmap_base is 0x7fffb7de6000
prctl() = 0
mprotect(0x7fffb7de6000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de6000, 0x1000, PROT_READ | PROT_WRITE) = 0
fstatat64(0xffffff9c, \dev\__properties__) = -1
[!] Directory Not Found: \dev\__properties__
openat(4294967196, \dev\__properties__, 0x8000, 0o0) = -1
[+] openat(4294967196, \dev\__properties__, O_RDONLY | 32768, 0o0) = -1
[!] File Not Found M:\qiling\qiling-learn\tests\..\examples\rootfs\arm64_android\dev\__properties__
[+] log mmap - mmap(0x0, 0x3000, 0x0, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x3000, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7de7000
[+] log mmap - addr range  : 0x7fffb7de7000 - 0x7fffb7dea000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de7000  length 0x3000
mmap(0x0, 0x3000, 0x0, 0x22, 4294967295, 0) = 0x7fffb7de7000
[+] mmap_base is 0x7fffb7de7000
mprotect(0x7fffb7de8000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de8000, 0x1000, PROT_READ | PROT_WRITE) = 0
rt_sigaction(0x6, 0x80000000ca48, = 0x0) = 0
rt_sigaction(0x7, 0x80000000ca48, = 0x0) = 0
rt_sigaction(0x8, 0x80000000ca48, = 0x0) = 0
rt_sigaction(0x4, 0x80000000ca48, = 0x0) = 0
rt_sigaction(0xb, 0x80000000ca48, = 0x0) = 0
rt_sigaction(0x10, 0x80000000ca48, = 0x0) = 0
rt_sigaction(0x1f, 0x80000000ca48, = 0x0) = 0
rt_sigaction(0x5, 0x80000000ca48, = 0x0) = 0
rt_sigaction(0x23, 0x80000000ca48, = 0x0) = 0
prctl() = 0
fstatat64(0xffffff9c, \proc\self\exe) = 0
[+] Directory Found: \proc\self\exe
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
futex(7ffff7f29268, 129, 2147483647) = 0
readlinkat(0xffffff9c, 0x7ffff7e8cd2a, 0x80000000cde0, 0x1000) = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7dea000
[+] log mmap - addr range  : 0x7fffb7dea000 - 0x7fffb7deb000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dea000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7dea000
[+] mmap_base is 0x7fffb7dea000
prctl() = 0
openat(4294967196, \system\etc\ld.config.txt, 0x8000, 0o0) = -1
[+] openat(4294967196, \system\etc\ld.config.txt, O_RDONLY | 32768, 0o0) = -1
[!] File Not Found M:\qiling\qiling-learn\tests\..\examples\rootfs\arm64_android\system\etc\ld.config.txt
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7deb000
[+] log mmap - addr range  : 0x7fffb7deb000 - 0x7fffb7dec000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7deb000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7deb000
[+] mmap_base is 0x7fffb7deb000
prctl() = 0
[+] log mmap - mmap(0x0, 0x18, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x18, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7dec000
[+] log mmap - addr range  : 0x7fffb7dec000 - 0x7fffb7ded000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dec000  length 0x1000
mmap(0x0, 0x18, 0x3, 0x22, 0, 0) = 0x7fffb7dec000
[+] mmap_base is 0x7fffb7dec000
prctl() = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7ded000
[+] log mmap - addr range  : 0x7fffb7ded000 - 0x7fffb7dee000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7ded000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7ded000
[+] mmap_base is 0x7fffb7ded000
prctl() = 0
[+] log mmap - mmap(0x0, 0x18, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x18, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7dee000
[+] log mmap - addr range  : 0x7fffb7dee000 - 0x7fffb7def000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dee000  length 0x1000
mmap(0x0, 0x18, 0x3, 0x22, 0, 0) = 0x7fffb7dee000
[+] mmap_base is 0x7fffb7dee000
prctl() = 0
munmap(0x7fffb7deb000, 0x1000) = 0
socket(1, 526338, 0) = -1
[+] socket(AF_LOCAL, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0) = -1
writev(0x2, 0x80000000b3a8, 0x4)
write(2,7ffff7e8b490,17) = 0
write(2,7ffff7e8b490,17) = -1
[!] Syscall ERROR: ql_syscall_write DEBUG: string argument expected, got 'bytearray'
[!] Emulation Error

[-] x0	:	 0x2
[-] x1	:	 0x7ffff7e8b490
[-] x2	:	 0x11
[-] x3	:	 0x64657474696d
[-] x4	:	 0x30
[-] x5	:	 0xa0
[-] x6	:	 0xfeff63647373686c
[-] x7	:	 0x7f7f7f7f7f7f7f7f
[-] x8	:	 0x40
[-] x9	:	 0x0
[-] x10	:	 0x0
[-] x11	:	 0x7ffff7e8b490
[-] x12	:	 0x80000000b958
[-] x13	:	 0x80000000ba20
[-] x14	:	 0xffff7fffffff466f
[-] x15	:	 0x80000000b993
[-] x16	:	 0xffffffd0
[-] x17	:	 0x5c032fd5
[-] x18	:	 0xf1d6ccf9
[-] x19	:	 0x7ffff7e8b490
[-] x20	:	 0x80000000b980
[-] x21	:	 0x11
[-] x22	:	 0xffffffd0
[-] x23	:	 0x7ffff7ebf430
[-] x24	:	 0xa
[-] x25	:	 0x7ffff7e9414c
[-] x26	:	 0x7ffff7ebf860
[-] x27	:	 0x80000000ba20
[-] x28	:	 0x0
[-] x29	:	 0x80000000b830
[-] x30	:	 0x7ffff7dfc130
[-] sp	:	 0x80000000b810
[-] pc	:	 0x7ffff7e75550
[-] cpacr_el1	:	 0x300000
[-] tpidr_el0	:	 0x7ffff7f2ca48

[+] PC = 0x7ffff7e75550

[+] Start      End        Perm.  Path
[+] 555555554000 - 555555555000 - r-x    M:\qiling\qiling-learn\examples\rootfs\arm64_android\bin\arm64_android_hello (M:\qiling\qiling-learn\examples\rootfs\arm64_android\bin\arm64_android_hello)
[+] 555555555000 - 555555557000 - rw-    M:\qiling\qiling-learn\examples\rootfs\arm64_android\bin\arm64_android_hello (M:\qiling\qiling-learn\examples\rootfs\arm64_android\bin\arm64_android_hello)
[+] 555555557000 - 555555559000 - rwx    [hook_mem] (M:\qiling\qiling-learn\examples\rootfs\arm64_android\bin\arm64_android_hello)
[+] 7fffb7dd6000 - 7fffb7ddb000 - rwx    [syscall_mmap]
[+] 7fffb7ddb000 - 7fffb7de0000 - rwx    [syscall_mmap]
[+] 7fffb7de0000 - 7fffb7de1000 - rwx    [syscall_mmap]
[+] 7fffb7de1000 - 7fffb7de2000 - rwx    [syscall_mmap]
[+] 7fffb7de2000 - 7fffb7de3000 - rwx    [syscall_mmap]
[+] 7fffb7de3000 - 7fffb7de4000 - rwx    [syscall_mmap]
[+] 7fffb7de4000 - 7fffb7de5000 - rwx    [syscall_mmap]
[+] 7fffb7de5000 - 7fffb7de6000 - rwx    [syscall_mmap]
[+] 7fffb7de6000 - 7fffb7de7000 - rwx    [syscall_mmap]
[+] 7fffb7de7000 - 7fffb7dea000 - rwx    [syscall_mmap]
[+] 7fffb7dea000 - 7fffb7deb000 - rwx    [syscall_mmap]
[+] 7fffb7dec000 - 7fffb7ded000 - rwx    [syscall_mmap]
[+] 7fffb7ded000 - 7fffb7dee000 - rwx    [syscall_mmap]
[+] 7fffb7dee000 - 7fffb7def000 - rwx    [syscall_mmap]
[+] 7ffff7dd5000 - 7ffff7f32000 - rwx    M:\qiling\qiling-learn\examples\rootfs\arm64_android\system\bin\linker64
[+] 7ffffffde000 - 80000000e000 - rwx    [stack]
[+] ['0x1f', '0x4', '0x40', '0xb1', '0x0', '0x94', '0x80', '0xda']

[+] 0x7ffff7e75550     1f 04 40 b1 00 94 80 da 48 84 f9 54 c0 03 5f d6 f6 57 bd a9 f4 4f 01 a9 fd 7b 02 a9 fd 83 00 91 d6 05 00 90 d3 62 42 f9 f4 03 00 aa f4 01 00 b4 e0 03 14 aa 13 c0 ff 97 c8 05 00 90 08 c9 44 b9 cmn x0, #1, lsl #12
cneg x0, x0, hi
b.hi #0x7ffff7e685e0
ret 
stp x22, x21, [sp, #-0x30]!
stp x20, x19, [sp, #0x10]
stp x29, x30, [sp, #0x20]
add x29, sp, #0x20
adrp x22, #0x7ffff7f2d000
ldr x19, [x22, #0x4c0]
mov x20, x0
cbz x20, #0x7ffff7e755b8
mov x0, x20
bl #0x7ffff7e655d0
adrp x8, #0x7ffff7f2d000
ldr w8, [x8, #0x4c8]

Error
Traceback (most recent call last):
  File "D:\Anaconda3_x64_2020_7\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "D:\Anaconda3_x64_2020_7\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "D:\Anaconda3_x64_2020_7\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "M:\qiling\qiling-learn\tests\test_android.py", line 77, in test_android_arm64
    ql.run()
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\core.py", line 193, in run
    self.os.run()
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\linux\linux.py", line 121, in run
    self.ql.emu_start(self.ql.loader.entry_point, self.ql.loader.elf_entry, self.ql.timeout)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\core.py", line 255, in emu_start
    raise self.internal_exception
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\core_hooks.py", line 121, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\core_hooks.py", line 36, in call
    return self.callback(ql, *args)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\linux\linux.py", line 66, in hook_syscall
    return self.load_syscall(intno)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\posix.py", line 178, in load_syscall
    raise e
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\posix.py", line 169, in load_syscall
    self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\syscall\unistd.py", line 275, in ql_syscall_write
    ql.os.fd[write_fd].write(buf)
  File "C:\PyCharm 2020.2.1\plugins\python\helpers\pycharm\teamcity\common.py", line 47, in write
    super(FlushingStringIO, self).write(str)
TypeError: string argument expected, got 'bytearray'

断言失败

Ran 1 test in 4.574s

FAILED (errors=1)

Process finished with exit code 1

断言失败

断言失败

**Comment by xwings** [comment]
WSL2. again?
