### ISSUE TITLE
好多例子在windows10下无法运行

### ISSUE THREAD

**Issue by zbx911** [qilingframework/qiling#537]
D:\Anaconda3_x64_2020_7\python.exe "C:\PyCharm 2020.2.1\plugins\python\helpers\pydev\pydevd.py" --multiproc --save-signatures --qt-support=auto --client 127.0.0.1 --port 53580 --file M:/qiling/qiling-learn/examples/simple_efi_x8664.py
pydev debugger: process 3680 is connecting

Connected to pydev debugger (build 202.6948.78)
[+] Initiate stack address at 0x7ffffffde000
[+] Loading rootfs/x8664_efi/bin/TcgPlatformSetupPolicy to 0x10000
[+] PE entry point at 0x102f0
[+] Done with loading rootfs/x8664_efi/bin/TcgPlatformSetupPolicy
[+] Running from 0x102f0 of rootfs/x8664_efi/bin/TcgPlatformSetupPolicy
AllocatePool(PoolType = 0x4, Size = 0x28, Buffer = 0x10e48) = 0x0
GetVariable(VariableName = "InternalDisallowTpmFlag", Attributes = 0x80000001bf70, DataSize = 0x80000001bf90, Data = 0x80000001cfe0) = 0x800000000000000e
GetVariable(VariableName = "TcgInternalSyncFlag", Attributes = 0x80000001bf70, DataSize = 0x80000001bf90, Data = 0x80000001cfe8) = 0x0
GetVariable(VariableName = "Setup", Attributes = 0x80000001bf70, DataSize = 0x80000001bf88, Data = 0x80000001bfa0) = 0x0
hook_InstallMultipleProtocolInterfaces 10000
	 bb6cbeff-e072-40d2-a6eb-bab75bde87e7, 500100060
InstallMultipleProtocolInterfaces(Handle = 0x80000001cfd0) = 0x0
CreateEvent(Type = 0x200, NotifyTpl = 0x8, NotifyFunction = 0x106e0, NotifyContext = 0x0, Event = 0x80000001bf98) = 0x0
RegisterProtocolNotify(Protocol = "dbc9fd21-fad8-45b0-9e78-27158867cc93", Event = 0x0, Registration = 0x10e20) = 0x0
[+] No more modules to run

Process finished with exit code 0

**Comment by xwings** [comment]
This example runs fine. what is the issue.
For Windows 10, please run in WSL2

**Comment by zbx911** [comment]
> This example runs fine. what is the issue.
> For Windows 10, please run in WSL2

好像有些跟 WSL2 无关，是因为windows下stdin,stdout少一些符号信息

**Comment by xwings** [comment]
你这个执行是没问题的
