### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by alan717** [qilingframework/qiling#546]
***Describe the bug**
In Ubuntu20.04 lts ,i emulate a embedd linux binary,but got `IndexError: list index out of range`,Could you help me figure out 
 what the problem point is ? I wanna to fix it with my hand. 
Thanks.

**Sample Code**
```python
def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, output="debug")
    ql.multithread = True
    #ql.set_syscall(0x04, my_syscall_write)

    ql.run()


if __name__ == "__main__":
    my_sandbox(["rootfs/arm_linux/bin/control_bin"], "rootfs/arm_linux")
```

**Expected behavior**
Succes run !
**Screenshots**
clear full log is [here](https://gist.github.com/alan717/1c2ff8f0b1dfc25360968f7a5b436905)

**Additional context**
No others.

**Comment by xwings** [comment]
I think there is a mistake here

In file unistd.py line 567 

```
    real_path = ql.os.fd[ftrunc_fd].name
    st_size = Stat(real_path).st_size
```

try change it to

```
    path= ql.os.fd[ftrunc_fd].name
    real_path = ql.os.transform_to_real_path(path)
    st_size = Stat(real_path).st_size
```


lets see if that works, it it doesn't then you u need to print out ql.os.fd  and see what is the issue

Also there are 3 missing syscall

```
[!] 0x7763eed6: syscall ql_syscall_sched_getaffinity number = 0xf2(242) not implemented
[!] 0x7763eed6: syscall ql_syscall_sched_setaffinity number = 0xf1(241) not implemented
[!] 0x776ab20c: syscall ql_syscall_statfs number = 0x63(99) not implemented
```

that might be the issue

**Comment by alan717** [comment]
> I think there is a mistake here
> 
> In file unistd.py line 567
> 
> ```
>     real_path = ql.os.fd[ftrunc_fd].name
>     st_size = Stat(real_path).st_size
> ```
> 
> try change it to
> 
> ```
>     path= ql.os.fd[ftrunc_fd].name
>     real_path = ql.os.transform_to_real_path(path)
>     st_size = Stat(real_path).st_size
> ```
> 
> lets see if that works, it it doesn't then you u need to print out ql.os.fd and see what is the issue
> 
> Also there are 3 missing syscall
> 
> ```
> [!] 0x7763eed6: syscall ql_syscall_sched_getaffinity number = 0xf2(242) not implemented
> [!] 0x7763eed6: syscall ql_syscall_sched_setaffinity number = 0xf1(241) not implemented
> [!] 0x776ab20c: syscall ql_syscall_statfs number = 0x63(99) not implemented
> ```
> 
> that might be the issue

Thanks ,i'll try it now!

**Comment by xwings** [comment]
will wait for your PR
