### ISSUE TITLE
How to resolve functions in another kernel module?

### ISSUE THREAD

**Issue by cq674350529** [qilingframework/qiling#549]
Recently, I notice that the demigod has been merged into the qiling. Cool and appreciate !

When trying to emulate a linux kernel module, if some functions in another module are called by current module, it will fail. Currently, it seems only one module is loaded and mapped into memory totally. So is is possible to load dependent modules at the same time?  I'm not familiar with kernel module.

By the way, it's possible to hook the "missing" functions (in another module but not in current module) manually. But it might be a little bit tedious.

Any advice would be appreciated! Thanks in advance.

**Comment by aquynh** [comment]
Currently loading more than 1 module is not supported. Contribution is
welcome.

**Comment by cq674350529** [comment]
Thanks, I'll have a look and try.
