### ISSUE TITLE
iotcls syscall - IndexError

### ISSUE THREAD

**Issue by zi0Black** [qilingframework/qiling#565]
**Describe the bug**
During emulation of a mipsbe binary it makes a call to the system function "iotcl", the parameters to the call are as follows:

`iotcl(2147483647,21517,2146683832)`

This calls generates an emulation error:
```bash
  File "/usr/local/lib/python3.8/dist-packages/qiling-1.2.dev0-py3.8.egg/qiling/os/posix/syscall/ioctl.py", line 81, in ql_syscall_ioctl
    if isinstance(ql.os.fd[ioctl_fd], ql_socket) and (ioctl_cmd == SIOCGIFADDR or ioctl_cmd == SIOCGIFNETMASK):
  File "/usr/local/lib/python3.8/dist-packages/qiling-1.2.dev0-py3.8.egg/qiling/core_utils.py", line 341, in __getitem__
    return self.__fds[idx]
IndexError: list index out of range
```
https://pastebin.com/2FCzfKyn

**Sample Code**
```python
[not-provided]
```

**Expected behavior**
A successful execution.

**Additional context**
I tried to search in the code where the array "fd" using in the if-statment (`ql.os.fd[ioctl_fd]`) was instantiated and after finding it (or so I think) I saw that it has a size of 256 elements. 

```python
self.fd = QlFileDes([0] * 256)
```

So I tried to hook the syscall "iotcl" and return `0` (from Linux kernel documentation) when the descriptor file was more than 256, but without success because although it does not fail qiling the binary ends with `exit(1)`.

**Comment by xwings** [comment]
I guess you need to debug more to find out what is the issue. might be a bug or something else. I cannot see the issue from the log.

**Comment by zi0Black** [comment]
I spent some time reading the function that actually calls `iotcl` and seems that the register `$a0` is not set inside the function and have a previous value `[-] a0  :   0x7fffffff`. 

I will spend more time on it this week.

**Comment by zi0Black** [comment]
I never closed it, also if managed to run the binary simply avoiding the system call for the specific case (I think that in the real OS everything is handled as a bad call from the system).

Code:
```python
def my_ql_syscall_ioctl(ql, ioctl_fd, ioctl_cmd, ioctl_arg, *args, **kw):
    if(ioctl_fd != 2147483647):
        syscall.ql_syscall_ioctl(ql, ioctl_fd, ioctl_cmd, ioctl_arg, *args)
    else:
        syscall.ql_syscall_ioctl(ql, 0, ioctl_cmd, ioctl_arg, *args)
```
