### ISSUE TITLE
regdemo_x86_windows.py Value key HKEY_CURRENT_USER\Software not present

### ISSUE THREAD

**Issue by SwordFaith** [qilingframework/qiling#567]
***Describe the bug**
After execute examples/scripts/dllscollecter.bat, I encounter Create Key Error0x10356160: exit(status = 0x0).

**Sample Code**
```python
#!/usr/bin/env python3
# 
# Cross Platform and Multi Architecture Advanced Binary Emulation Framework
# Built on top of Unicorn emulator (www.unicorn-engine.org) 
import sys
sys.path.append("..")
from qiling import *

def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, output = "debug")
    ql.run()


if __name__ == "__main__":
    my_sandbox(["rootfs/x86_windows/bin/RegDemo.exe"], "rootfs/x86_windows")
```

**Expected behavior**
like youtube demo https://www.youtube.com/watch?reload=9&v=4nk8KNgbNzw

**Screenshots**

**Additional context**
[+] Windows Registry PATH: rootfs/x86_windows/Windows/registry
[+] Initiate stack address at 0xfffdd000 
[+] Loading rootfs/x86_windows/bin/RegDemo.exe to 0x400000
[+] PE entry point at 0x401381
[+] TEB addr is 0x6000
[+] PEB addr is 0x6044
[+] Loading rootfs/x86_windows/Windows/SysWOW64/ntdll.dll to 0x10000000
[+] Done with loading rootfs/x86_windows/Windows/SysWOW64/ntdll.dll
[+] Loading rootfs/x86_windows/Windows/SysWOW64/kernel32.dll to 0x101a3000
[+] Done with loading rootfs/x86_windows/Windows/SysWOW64/kernel32.dll
[+] Loading rootfs/x86_windows/Windows/SysWOW64/advapi32.dll to 0x10288000
[+] Done with loading rootfs/x86_windows/Windows/SysWOW64/advapi32.dll
[+] Loading rootfs/x86_windows/Windows/SysWOW64/msvcr110.dll to 0x10302000
[+] Done with loading rootfs/x86_windows/Windows/SysWOW64/msvcr110.dll
[+] Done with loading rootfs/x86_windows/bin/RegDemo.exe
0x101c2390: GetSystemTimeAsFileTime(lpSystemTimeAsFileTime = 0xffffcfec)
0x101c0f10: GetCurrentThreadId() = 0x0
0x101c5e90: GetCurrentProcessId() = 0x7cc
0x101c0f40: QueryPerformanceCounter(lpPerformanceCount = 0xffffcfe4) = 0x0
0x10355f90: _initterm_e(pfbegin = 0x4020b8, pfend = 0x4020c8) = 0x0
0x10355f30: _initterm(pfbegin = 0x4020ac, pfend = 0x4020b4)
[+] Key 2147483649 Software
[!] Value key HKEY_CURRENT_USER\Software not present
0x102a6520: RegOpenKeyW(hKey = 0x80000001, lpSubKey = "Software", phkResult = 0xffffcfb4) = 0x2
printf(format = 'Create Key Error') = 0x10
Create Key Error0x10356160: exit(status = 0x0)

**Comment by xwings** [comment]
Can you make sure they Registry file is there ?

**Comment by xwings** [comment]
https://docs.qiling.io/en/latest/install/#important-note-on-windows-dlls-and-registry
