### ISSUE TITLE
partial execution example on docs/snapshot doesn't work as expected

### ISSUE THREAD

**Issue by c2hpxq** [qilingframework/qiling#568]
@xwings 
***Describe the bug**
Direct emulation of examples/rootfs/x8664_linux/bin/sleep_hello works fine.
Copy code on snapshot chapter & run -- original program output such as "Hello, World!" is lost.

**Sample Code**
```python
from qiling import *

def dump(ql, *args, **kw):
    ql.save(reg=False, cpu_context=True, snapshot="/tmp/snapshot.bin")
    ql.emu_stop()

ql = Qiling(["rootfs/x8664_linux/bin/sleep_hello"], "rootfs/x8664_linux", output= "default")
X64BASE = int(ql.profile.get("OS64", "load_address"), 16)
ql.hook_address(dump, X64BASE + 0x1094)
ql.run()

ql = Qiling(["rootfs/x8664_linux/bin/sleep_hello"], "rootfs/x8664_linux", output= "debug", verbose=4)
X64BASE = int(ql.profile.get("OS64", "load_address"), 16)
ql.restore(snapshot="/tmp/snapshot.bin")
begin_point = X64BASE + 0x109e
end_point = X64BASE + 0x10bc
# I don't see output for original program, i.e., sleep_hello
ql.run(begin = begin_point, end = end_point)

# works fine!
ql = Qiling(["rootfs/x8664_linux/bin/sleep_hello"], "rootfs/x8664_linux", output= "default")
ql.run()
```

**Expected behavior**
save&restore should give me output from sleep_hello as direct emulation does.

**Screenshots**
None

**Additional context**
None

**Comment by xwings** [comment]
Hi, 

what do u mean by this ?

This code is in the test and test did not fail

**Comment by c2hpxq** [comment]
Thanks for your time&comments.
Yes, the test doesn't fail, I run&confirm that.
But I expect the snapshot example to output **ORIGINAL PROGRAM OUTPUT**, as direct load&run does.
To be more specific, I want the snapshot example to output

> sleep 3600 seconds...
> wake up.
> Hello, World!

But I fail to see that...
How can I make it? I am new to qiling framework and just skim through all the docs, so it really helps if you can tell me how to modify the snapshot example in order to see the **OUTPUT OF ORIGINAL PROGRAM**.

I've seen your comments in other post in Chinese, so I will describe it in Chinese too.
--------------------------------------------------------------------------------------------------------------
我运行了snapshot章的这个例子（sleep_hello），确实没有出错。
问题是：直接加载运行（Qiling() & ql.run()）sleep_hello可以正常输出
> sleep 3600 seconds...
> wake up.
> Hello, World!
但snapshot的例子里，sleep_hello的输出不见了。而我期望的是snapshot save&restore仍能看到程序的正常输出。
请问是需要如何修改snapshot章example，才能让它输出正常的程序输出呢？
谢谢。

**Comment by cq674350529** [comment]
@c2hpxq I run your provided example, and it works as expected.
There are thee parts in your example. The first part is to save a snapshot and only output "sleep 3600 seconds...". The second part is to restore the snapshot and continue to run, so "wake up. \n Hello, World!" will be output. In other words, the first one only runs from `0x1080` to `0x1094`, and the second only runs from `0x109e` to `0x10bc`. However, the third one is to run fully, from `0x1080` to `0x10bc`.

**Comment by c2hpxq** [comment]
The script works fine on Ubuntu 18.04 but not on macOS10.15.
