### ISSUE TITLE
winsdk_dump doesnt work correctly

### ISSUE THREAD

**Issue by archercreat** [qilingframework/qiling#571]
reproduce:
download https://github.com/ohjeongwook/windows_sdk_data.git
run:
```bash
./winsdk_dump.py
Traceback (most recent call last):
  File "./winsdk_dump.py", line 89, in <module>
    parse_winsdk(filename)
  File "./winsdk_dump.py", line 42, in parse_winsdk
    for func in winsdk[entry]:     # read function dict
TypeError: list indices must be integers or slices, not str
```

**Comment by xwings** [comment]
I dont understand. can you please elaborate more ?

**Comment by archercreat** [comment]
Hi, so I wanted to generate psapi.dll json file since you don't have one in main repo, but ran into an error while executing winsdk_dump.py which is located here "qiling/extensions/windows_sdk/winsdk_dump.py"

**Comment by xwings** [comment]
ok, maybe @kabeor can help

**Comment by kabeor** [comment]
@archercreat  I will check it. Maybe just need a small patch.
