### ISSUE TITLE
ql_syscall_open didn't act on flags on mipsel

### ISSUE THREAD

**Issue by ucgJhe** [qilingframework/qiling#58]
ql_syscall_open didn't act on flags like create files or something else.

**Comment by ucgJhe** [comment]
turns out flags on mipsel is different from linux, will PR to fix this

**Comment by xwings** [comment]
Ok, Thanks !

**Comment by xwings** [comment]
you can always add,

if (ql.arch == QL_MIPS32EL):

**Comment by ucgJhe** [comment]
should be fixed in https://github.com/qilingframework/qiling/pull/56/commits/502ffe06068befbde0e9f86f0c0efb9bcdc108f1

**Comment by ucgJhe** [comment]
close since its merged
