### ISSUE TITLE
Problem: why interp_mem_size computation need to sum all p_vaddr when load interpreter into memory

### ISSUE THREAD

**Issue by newthis** [qilingframework/qiling#589]
I read the code in loader/elf.py file, when loading interpreter file in elf file, why need to add **p_vaddr** when traversing 
the segments in the interpreter file. This leads to map more memory than needed.

            **interp_mem_size** = -1
            for i in interp.parse_segments():
                i = dict(i.header)
                if i['p_type'] == 'PT_LOAD':
                    if interp_mem_size < i['p_vaddr'] + i['p_memsz'] or interp_mem_size == -1:
                        interp_mem_size = i[**'p_vaddr**'] + i['p_memsz']

            interp_mem_size = (interp_mem_size // 0x1000 + 1) * 0x1000
            self.ql.dprint(D_INFO, "[+] interp_mem_size is : 0x%x" % int(interp_mem_size))

            if self.ql.archbit == 64:
                self.interp_address = int(self.ql.os.profile.get("OS64", "interp_address"), 16)
            elif self.ql.archbit == 32:
                self.interp_address = int(self.ql.os.profile.get("OS32", "interp_address"), 16)

            self.ql.dprint(D_INFO, "[+] interp_address is : 0x%x" % (self.interp_address))
            self.ql.mem.map(self.interp_address, int(interp_mem_size),
                            info=os.path.abspath(self.ql.rootfs + interp_path))

**Comment by xwings** [comment]
it should be 

```
((size+0xfff)//0x1000)*0x1000
```

maybe you can push a PR ?

**Comment by xwings** [comment]
close due to no response
