### ISSUE TITLE
ida导入插件,pyqt5找不到模块但是外部vscode运行py是可以使用的

### ISSUE THREAD

**Issue by Invincible-World** [qilingframework/qiling#602]
![image](https://user-images.githubusercontent.com/54766551/102313142-002f7600-3fab-11eb-9178-6b4fe8be1bbd.png)
windows10   ida7.5   python3.9

**Comment by wtdcode** [comment]
https://www.hex-rays.com/blog/python-3-9-support-for-ida-7-5/

比预想中的还快。
