### ISSUE TITLE
Qiling tries to load ntoskrnl.exe for usermode processes

### ISSUE THREAD

**Issue by learn-more** [qilingframework/qiling#605]
***Describe the bug**
In windows, drivers can import from `ntoskrnl.exe`, but usermode applications / dlls cannot.

**Expected behavior**
When starting a 'normal' application, or loading a dll that is not going to run as service, ntoskrnl.exe should not be loaded.

**Comment by learn-more** [comment]
#606 aims to fix this.

**Comment by xwings** [comment]
Merge PR #606  and close.
