### ISSUE TITLE
Please move the petya dos mbr into a zip archive

### ISSUE THREAD

**Issue by learn-more** [qilingframework/qiling#621]
The file `petya.DOS_MBR` is firing on Windows Defender, so it would be nice if this file could be moved into a zip archive, like the other malware.

**Comment by xwings** [comment]
request granted.

**Comment by learn-more** [comment]
Thanks!

**Comment by readermall** [comment]
@xwings petya.DOS_MBR.zip 压缩包的密码是什么？

**Comment by readermall** [comment]
已解决，非常感谢，还有一个问题，通过邮件发您的，帮忙看下，急等！！！
再次感谢。




菟纸先森
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qilingframework/qiling"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月6日(星期三) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qilingframework/qiling] Please move the petya dos mbr into a zip archive (#621)





 
infected
