### ISSUE TITLE
pe.py libcache contains too much symbols

### ISSUE THREAD

**Issue by learn-more** [qilingframework/qiling#641]
When storing a file for the libcache, not only the symbols for that file are stored, but also all symbols loaded until then.

```python
    with open(fcache, "rb") as fcache_file:
        data, cmdlines, import_symbols, import_address_table = pickle.load(fcache_file)
    print(fcache.name, 'import_address_table:', import_address_table.keys())
```
Prints something like:

```
wsock32.dll.10b4b000.cache import_address_table: dict_keys(['ntdll.dll', 'kernel32.dll', 'msvcrt.dll', 'user32.dll', 'advapi32.dll', 'gdi32.dll', 'ole32.dll', 'oleaut32.dll', 'wininet.dll', 'wsock32.dll'])
```
Because all those dll's were loaded in the target before wsock32.dll was loaded.

Same with the `import_symbols`, they also contain _all_ import symbols up to the point the cache is written.

**Comment by xwings** [comment]
Maybe we can take out the cache? and let user do their own cache

**Comment by learn-more** [comment]
> Maybe we can take out the cache? and let user do their own cache

I think we can rewrite it to work a bit better, I'll create a pr soon(ish)

**Comment by xwings** [comment]
Fixed!
