### ISSUE TITLE
Running windows crackme fails

### ISSUE THREAD

**Issue by Nader-Sl** [qilingframework/qiling#65]
when running via python3.7 in the examples directory I get
`qiling.exception.QlErrorFileNotFound: [!] Cannot find dll in rootfs/x86_windows\dlls\kernel32.dll`

**Comment by xwings** [comment]
Readme docs did mention you need to insert DLLs. 
We are not able to distribute due to license restriction

**Comment by Nader-Sl** [comment]
Ah i don't see that in the doc all good then, thanks

**Comment by xwings** [comment]
thanks and closed
