### ISSUE TITLE
Missing const.py in qiling/debugger/qdb

### ISSUE THREAD

**Issue by octy83** [qilingframework/qiling#661]
**Describe the bug**
Seems there is a missing file (from merge https://github.com/qilingframework/qiling/pull/660): const.py in debugger/qdb

**Sample Code**
Just run the provided sample 'hello_arm_linux_debug.py'

**Expected behavior**
Debug of the hello arm program.

**Screenshots**
Error returned:
'qiling/debugger/qdb/frontend.py", line 11, in <module>
    from .const import color
ModuleNotFoundError: No module named 'qiling.debugger.qdb.const'

**Comment by ucgJhe** [comment]
sorry, my bad . should be fixed after #662

**Comment by xwings** [comment]
fixed !
