### ISSUE TITLE
qdb examine command with byte format has wrong output

### ISSUE THREAD

**Issue by octy83** [qilingframework/qiling#672]
***Describe the bug**
qdb examine command (x shortcut) has invalid output for byte type 

**Sample Code**
Use provided example in repo
`python hello_arm_linux_debug.py`

**Expected behavior**
Dump any part of memory in words to have a reference and then in bytes to see the bytes version output is buggy.

**Screenshots**
Examine 4 words:
```
(Qdb) x/4wx 0x1030c
0x1030c:        0xe3a0b000      0xe3a0e000      0xe49d1004      0xe1a0200d
```
Examine same memory area but with byte output
```
(Qdb) x/16bx 0x1030c
0x1030c:        0x00    0xb0    0xa0    0xe3
0x1031c:        0xb0    0xa0    0xe3    0x00
0x1032c:        0xa0    0xe3    0x00    0xe0
0x1033c:        0xe3    0x00    0xe0    0xa0
```
Appart endianess representation (which reverse the data and is normal) you can see that 

- addresses are not correct (there is a jump of 0x10 between each lines)
- the byte dump is incorrect (first line is correct, but remaining one are not).

**Additional context**
No more context.

**Comment by ucgJhe** [comment]
roger that, on way to fix it

**Comment by xwings** [comment]
fixed
