### ISSUE TITLE
Posix: fstat and stat should be "merged"

### ISSUE THREAD

**Issue by PeterStolz** [qilingframework/qiling#674]
**Is your feature request related to a problem? Please describe.**
The syscalls `fstat` and `stat` are per definition only differnt in the arguments. fstat takes a file descriptor whereas stat takes a path. In posix/syscall/stat.py these syscalls behave differently, since the struct written to memory can be differnt, because  `fstat` has more cases depending on the architecture and os. `stat64` and `fstat64` have the same relationship. `fstat` uses `ql.os.fd[user_fileno].fstat()` whereas `stat` uses  `Stat(real_path)` to get information about the file. The calls to `.fstat()` return the same to my knowledge, since the `.fstat()` is defined in filestruct.py as    
>def fstat(self):      
        return Fstat(self.__fd)

As of python3.3 calls to os.fstat and os.stat are equivalent, which is invoked in Stat and Fstat.
If  `.fstat()` always returns `Fstat(self.__fd)`, the syscalls create different structs depending on the architecture, even though the structs should be equal. If you can confirm this I will create a PR. If this is not the case I believe something is fishy and I'm not sure how to fix it.

**Describe the solution you'd like**
The creation of the struct could be moved to a function used by both fstat and stat. Another function for fstat64 and stat64 would be useful as well.

**Comment by xwings** [comment]
Sure, please come out with a PR.

Appreciate it !

**Comment by PeterStolz** [comment]
#678
