### ISSUE TITLE
Posix syscalls setgid and setuid return wrong value

### ISSUE THREAD

**Issue by danielmoos** [qilingframework/qiling#702]
The syscalls setgid and setuid should return 0 on success according to [setgid(2)](https://man7.org/linux/man-pages/man2/setgid.2.html) and [setuid(2)](https://man7.org/linux/man-pages/man2/setuid.2.html), but the current implementation returns the actual IDs.

**Sample Code**
In os/posix/syscall/unistd.py we find
```
def ql_syscall_setgid(ql, *args, **kw):
    GID = ql.os.gid
    regreturn = GID
    return regreturn
```

**Expected behavior**
Something like
```
def ql_syscall_setgid(ql, *args, **kw):
    return 0
```

**Comment by aquynh** [comment]
Please pull req to fix it

**Comment by xwings** [comment]
thanks and fit in cf82cdf
