### ISSUE TITLE
ida plugin load failed

### ISSUE THREAD

**Issue by simhigo** [qilingframework/qiling#717]
IDAVersion : IDA Pro 7.5
OS: MacOS
Python : 3.8.3 

NameError: name 'logging' is not defined error 

qilingida.py insert "import logging"  after new error

self.ql.log.info('---------------------------------------------------------------------------------------')
AttributeError: 'NoneType' object has no attribute 'log'

Failed while executing plugin_t.term():
'NoneType' object has no attribute 'remove_ql'
  File "/Users/sim-yeongjin/tools/qiling/qiling/extensions/idaplugin/qilingida.py", line 1040, in term
    self.qlemu.remove_ql()

**Comment by wtdcode** [comment]
Got it. Will fix ASAP.

________________________________

**Comment by wtdcode** [comment]
Fixed in 5acc2102c3043a3e986b4e148c0d677a0e64caaf

**Comment by simhigo** [comment]
Thanks you 
It Works!
