### ISSUE TITLE
Any support for dynamic symbolic execution?

### ISSUE THREAD

**Issue by anaivebird** [qilingframework/qiling#724]
Any support for dynamic symbolic execution?

Things like https://github.com/JonathanSalwan/Triton  by Quarkslab.

**Comment by anaivebird** [comment]
I used triton for several months. I'm surprised that chinese domestic company also works on emulation framework for reverse engineering. That's great!

**Comment by wtdcode** [comment]
Dynamic symbolic execution support is on the way, shipped with Unicorn2.

________________________________

**Comment by anaivebird** [comment]
Nice job! Only suggestion to make something like https://github.com/QBDI/QBDI. Sync with frida so that qiling could get trace from android/ios without repackage apk is cool.

**Comment by wtdcode** [comment]
Thanks for your interest.

For QBDI, maybe you can have a try with Qdb.
