### ISSUE TITLE
IDA Plugin setup error

### ISSUE THREAD

**Issue by simhigo** [qilingframework/qiling#728]
self.ql = Qiling(argv=[self.path], rootfs=self.rootfs, output="debug", env=self.env, stdin=qlstdin, stdout=qlstdout, stderr=qlstderr, log_plain=True, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'argv'

i used  dev-branch last commit version.
![image](https://user-images.githubusercontent.com/1684328/111568758-a9714c80-87e4-11eb-9a02-7f9e606bee27.png)

**Comment by wtdcode** [comment]
Looks like your plugin file or qiling installation is outdated.

**Comment by simhigo** [comment]
i installed qiling dev-1.2.3

**Comment by wtdcode** [comment]
have you restarted your IDA after installing the qiling? btw, note that the python IDA uses may not the python your qiling is installed with.

**Comment by simhigo** [comment]
yes. i installed after IDA run. 
idapython and qiling are same python.

**Comment by wtdcode** [comment]
Could you please run the following code in your idapython console:

```python
import qiling
print(qiling)
print(qiling.__version__)
```

**Comment by simhigo** [comment]
qiling.version output
![image](https://user-images.githubusercontent.com/1684328/111577595-eeea4580-87f5-11eb-86f1-0fa94163b6de.png)

**Comment by wtdcode** [comment]
> qiling.version output
> ![image](https://user-images.githubusercontent.com/1684328/111577595-eeea4580-87f5-11eb-86f1-0fa94163b6de.png)

obviously, this is not the qiling you installed in your previous screenshot.

**Comment by simhigo** [comment]
sorry . i edited idapython env.
i fixed.
Thnaks you
