### ISSUE TITLE
Analyzing .so in android app using qiling

### ISSUE THREAD

**Issue by anaivebird** [qilingframework/qiling#735]
Analyzing .so in app may be challenging due to  mocking JNI functions behavior like FindClass(), GetMethodID(), RegisterNatives() is hard.

So any wordaround for qiling to overcome it?
May be we need dynamic instrument module to parallel running with qiling. When jniEnv->RegisterNatives() is called, transfer control to real machine code and transfer back when RegisterNatives() returns.

![image](https://user-images.githubusercontent.com/29398611/111868487-13405080-89b5-11eb-8d66-1130232c68a7.png)

![image](https://user-images.githubusercontent.com/29398611/111868542-834ed680-89b5-11eb-9f5e-ccf1db97b8a2.png)

**Comment by aquynh** [comment]
I can take a look, can you upload your binary & your code?

**Comment by anaivebird** [comment]
All android app with so native code need these methods(not specific to some app). Refers to https://blog.quarkslab.com/android-native-library-analysis-with-qbdi.html

This method solves problem of mocking complex system call or framework lib call like java jni or android framework. Without this method, it will be hard to analysis android native so code in emulator like qiling.

Will qiling consider to add support to this?

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
