### ISSUE TITLE
ql.mem.find_free_space return unmapped mem address

### ISSUE THREAD

**Issue by anaivebird** [qilingframework/qiling#741]
**Describe the bug**
ql.mem.find_free_space return unmapped mem address (0x10000) (actually is unmapped)
So lead to unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

[=]	GetStringUTFChars hooked
[=]	ql.mem.find_free_space returned 65536(0x10000)
[=]	[+] Start      End        Perm.  Path
[=]	[+] 00000000 - 00001000 - rwx    [mapped]
[=]	[+] 00030000 - 00031000 - rwx    [GDT]
[=]	[+] 56555000 - 56561000 - r-x    D:\libanti_spam.so (D:\libanti_spam.so)
[=]	[+] 56561000 - 56563000 - rw-    D:\libanti_spam.so (D:\libanti_spam.so)
[=]	[+] 56563000 - 56565000 - rwx    [hook_mem]
[=]	[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[+]	addresss write length: 11
[x]	addresss write error: 0x10000

**Sample Code**
```python
return_str = "absdfbbsdf"
address = ql.mem.find_free_space(len(return_str)+1)
ql.log.info(address)
ql.mem.string(address, return_str)
ql.reg.eax = address
```

**Expected behavior**
ql.mem.find_free_space should return free address for us to use

**Comment by wtdcode** [comment]
I guess you would like `ql.mem.map_anywhere`

**Comment by anaivebird** [comment]
Solved after changing ql.mem.find_free_space  to ql.mem.map_anywhere
