### ISSUE TITLE
AFL stucks when use unicorn+qiling to fuzz Android native library with a real world gdb context

### ISSUE THREAD

**Issue by D0nYu** [qilingframework/qiling#748]
Hello, 
I tried to use AFLplusplus+unicorn to fuzz an Android native jpg codec library  and use qiling to emulate the Android system runtime. The initial state is dumped from a physical device from a gdb connection (https://github.com/AFLplusplus/AFLplusplus/tree/stable/unicorn_mode/helper_scripts).
After adding some necessary hooks, the harness works. When I use AFL to fuzz it (https://github.com/qilingframework/qiling/tree/master/examples/fuzzing) , it also works well in the very first minutes.
But soon the AFL stucks and the exec speed becomes extremely slow.
![image](https://user-images.githubusercontent.com/26272372/112255586-796ef100-8c9d-11eb-8265-dc2ffe9ef235.png)

I wonder how could I solve this.
It seems that AFL hangs because the qiling/unicorn struggle to request memory. Maybe map all the memory context is too cumbersome, or I misuse some APIs of qiling or unicorn? 
I have uploaded the code and environment at https://github.com/D0nYu/JpegFuzzer . Run fuzzit.sh can start the fuzzing. If you use the seed in my input directory, the AFL would stuck after 1582 execs.

**Comment by aquynh** [comment]
Where is the src code of the loader?

**Comment by D0nYu** [comment]
The Jpegloader is just a dummy binary to satisfy the qiling initialization. Once it is initialized, I overwrite all the memory regions and registers with the dumped context. And the code I try to emulate is a snippet of a dynamic library, so I think the loader does not matter.

**Comment by xwings** [comment]
not too sure which part of this is having issue.
according to @wtdcode very likely is unicorn.

What you can do is to add a timeout in AFL++ and see does it help.

maybe @domenukk can give us some hint :) calling @domenukk

**Comment by wtdcode** [comment]
Could you post qiling log?

**Comment by D0nYu** [comment]
The log file has been attached.
[qlog.txt](https://github.com/qilingframework/qiling/files/6203336/qlog.txt)

The "Allocating" entries by the malloc hook and the "android_log_print" entries are recorded by the hooks of android logging functions.

BTW, the `log_file `option cannot work well with `console=True`, when it tries to record the colored log.

**Comment by wtdcode** [comment]
> The log file has been attached.
> [qlog.txt](https://github.com/qilingframework/qiling/files/6203336/qlog.txt)
> 
> The "Allocating" entries by the malloc hook and the "android_log_print" entries are recorded by the hooks of android logging functions.
> 
> BTW, the `log_file `option cannot work well with `console=True`, when it tries to record the colored log.

you could try `log_plain=True`

**Comment by wtdcode** [comment]
Seems that the big allocation may slow down the whole fuzzer. But the problem is that it should not make AFL hang. I will try to reproduce it later.

**Comment by xwings** [comment]
@D0nYu lets see how can we form a group and discuss about this ? my email is kj@qiling.io

**Comment by domenukk** [comment]
The AFL run is set to a timeout of `-t 50000`, so afl will hardly ever kill slow testcases. Hitting a single infinite loop will lead to very slow fuzzing (below 1 exec per sec).

https://github.com/D0nYu/JpegFuzzer/blob/10d672c16f23b56cd4c7eb52fd2570c4dbade318/fuzzit.sh#L1

Changing this timeout to a normal time, like `-t 1000` may just solve your issue here.
On top, for a full snapshot, the fuzzer may just have found another way out of the harness and spend all of its time (up to 50 seconds) in other parts of the snapshot.

**Comment by D0nYu** [comment]
> The AFL run is set to a timeout of `-t 50000`, so afl will hardly ever kill slow testcases. Hitting a single infinite loop will lead to very slow fuzzing (below 1 exec per sec).
> 
> https://github.com/D0nYu/JpegFuzzer/blob/10d672c16f23b56cd4c7eb52fd2570c4dbade318/fuzzit.sh#L1
> 
> Changing this timeout to a normal time, like `-t 1000` may just solve your issue here.
> On top, for a full snapshot, the fuzzer may just have found another way out of the harness and spend all of its time (up to 50 seconds) in other parts of the snapshot.

In fact, the fuzzer takes over 30s to boot up but performs well in the first few minutes (30-40 execs per sec) until it finds a new path.  I also tried to use AFL qemu mode to fuzz the same target and everything went well.  So I wonder why qiling takes so much time.  Is it because a large amount of memory allocation slows down the fuzzer?

**Comment by wtdcode** [comment]
![image](https://user-images.githubusercontent.com/30623163/112594654-39963e00-8e44-11eb-9651-8b772dce2ccf.png)

Did a perf and seems that it's memory operation which slows down the whole fuzzer.

Link to https://github.com/unicorn-engine/unicorn/issues/1217 for now.

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
