### ISSUE TITLE
api AreFileApisANSI is not implemented

### ISSUE THREAD

**Issue by MisakaRay2021** [qilingframework/qiling#751]
When I testing a PE file compile by VS 2019, qiling show this error, is that mean qiling cant emulate this api not yet, or something wrong when I configure the environment?
Code:
------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, const char** argv)
{
    printf("Hello, World!\n");

    return 0;
}
------------------------------------------------

**Comment by tkremeyer** [comment]
Hi, I'm currently trying out and playing around with Qiling and encountered the same issue with VS2019 binaries. I just compiled the same code (Windows 10 SDK 10.0.19041.0). The error seems to be "api AreFileApisANSI is not implemented", as already stated in the issue.

Here I attached the binary:
[binary.zip](https://github.com/qilingframework/qiling/files/6331408/binary.zip)

I'm happy to provide more information if needed!

**Comment by xwings** [comment]
Hi,

to be honest, there will be more and more these missing API case appear soon.

Please refer to https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-arefileapisansi

and implement and add it in https://github.com/qilingframework/qiling/blob/dev/qiling/os/windows/dlls/kernel32/fileapi.py

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
