### ISSUE TITLE
Disabling strace during emulation

### ISSUE THREAD

**Issue by NudistBeaaach** [qilingframework/qiling#752]
Hey, is it possible to avoid qiling to strace syscalls during ELF emulation (the logs beginning by the "[=]") because for some ELF the strace make it so slow... in older version of qiling it was turning fine but now there is those syscalls logs. 😓

**Comment by xwings** [comment]
verbose = 0

https://docs.qiling.io/en/latest/print/#verbose

**Comment by NudistBeaaach** [comment]
Yea i used to set the verbose to 0, the logs are not displayed but the time took to strace syscalls is still here, even with a small program the time is very slow.

**Comment by wtdcode** [comment]
What makes the program slow is the hooks overhead in unicorn and qiling emulation. Disabling logging won't help too much.

**Comment by NudistBeaaach** [comment]
Ok, so the strace is due to the unicorn engine?

**Comment by NudistBeaaach** [comment]
But in some older version of Qiling the program runned quick, is there any way to make this quick again without going back to an older version 🤔

**Comment by wtdcode** [comment]
> But in some older version of Qiling the program runned quick, is there any way to make this quick again without going back to an older version 🤔

Which version? Also paste the log in the two versions plz.

**Comment by NudistBeaaach** [comment]
I'm sorry but i don' remember which one precisely, that was the lastest one during september (the month of my first projects with qiling)

**Comment by NudistBeaaach** [comment]
[=]     mmap(addr = 0x7fffb81c3000, length = 0x3ae0, prot = 0x3, flags = 0x32, fd = 0xffffffff, pgoffset = 0x0)
[=]     close(fd = 0x3)
[=]     mmap(addr = 0x0, length = 0x2000, prot = 0x3, flags = 0x22, fd = 0xffffffff, pgoffset = 0x0)
[=]     arch_prctl(ARCHX = 0x1002, ARCH_SET_FS = 0x7fffb81c7f00)
Here is the syscalls logs, and after the arch_prctl is displayed, the program take a long time to move on (and the other syscalls are faster to be logged but still noticable)

**Comment by wtdcode** [comment]
We can't help too much if you couldn't provide a stable reproducer.

**Comment by NudistBeaaach** [comment]
> We can't help too much if you couldn't provide a stable reproducer.
Yes I understand i'm sorry, so there is no possibility to take off this delay at all in your opinion?

**Comment by wtdcode** [comment]
> > We can't help too much if you couldn't provide a stable reproducer.
> 
> Yes I understand i'm sorry, so there is no possibility to take off this delay at all in your opinion?

AFAIK, I don't know any big changes which may slow down the execution to such a big extent.

**Comment by NudistBeaaach** [comment]
Ok np thanks anyway ^^
