### ISSUE TITLE
Windows Exceptions (SEH stack x86 + section based x64)

### ISSUE THREAD

**Issue by sparkyparrot** [qilingframework/qiling#76]
**Relative to packers analysis where SEH and exceptions are used a lot to throw off analysis:**

Any current support for x86 SEH handlers registered on fs:[0] (TIB start) when an exception occurs in the code , or do we have to propagate call with hooks ? Also on Vectored registered exception , but its an api call so its kinda a mix. Note from Wiki about VEH vectored exception handling: 

> VEH does not replace Structured Exception Handling (SEH), rather VEH and SEH coexist, with VEH handlers having priority over SEH handlers.

Same question regarding .pdata section and exceptions mechanisms on x86-64.

x86:
[https://docs.microsoft.com/en-us/windows/win32/debug/structured-exception-handling](https://docs.microsoft.com/en-us/windows/win32/debug/structured-exception-handling)
[https://en.wikipedia.org/wiki/Win32_Thread_Information_Block](https://en.wikipedia.org/wiki/Win32_Thread_Information_Block)
[https://en.wikipedia.org/wiki/Microsoft-specific_exception_handling_mechanisms#SEH](https://en.wikipedia.org/wiki/Microsoft-specific_exception_handling_mechanisms#SEH)
[https://docs.microsoft.com/en-us/windows/win32/debug/structured-exception-handling](https://docs.microsoft.com/en-us/windows/win32/debug/structured-exception-handling)

x64:
[https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=vs-2019](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=vs-2019)

**Comment by xwings** [comment]
@Dliv3 maybe can answer this better.

**Comment by Dliv3** [comment]
we don't implement SEH right now. if you can implement it, PR is appriciated

**Comment by xwings** [comment]
Close for now.

We updated the codebase for Qiling and Unicorn since this issue being posted.

Feel free to try the latest version.
