### ISSUE TITLE
fuzzing with Tenda_AC15: AttributeError: 'int' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by kirito999** [qilingframework/qiling#784]
***Describe the bug**
I can not run fuzz_tendaac15_httpd.py in /qiling/examples/fuzzing/tenda_ac15

**Sample Code**
I use https://github.com/qilingframework/qiling/tree/master/examples/fuzzing/tenda_ac15 and https://kabeor.cn/IoT%E5%9B%BA%E4%BB%B6%E6%8F%90%E5%8F%96%E5%B9%B6%E4%BD%BF%E7%94%A8qiling%E8%BF%9B%E8%A1%8Cfuzz/#IoT-Fuzz

**Expected behavior**
qiling@ubuntu:~/projects/qiling/examples/fuzzing/tenda_ac15$ python3 fuzz_tendaac15_httpd.py afl_inputs/a

Traceback (most recent call last):
  File "/home/qiling/.local/lib/python3.6/site-packages/qiling/os/posix/posix.py", line 281, in load_syscall
    ret = syscall_hook(self.ql, *arg_values)
  File "/home/qiling/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/select.py", line 40, in ql_syscall__newselect
    tmp_r_fd, tmp_r_map = parse_fd_set(ql, _newselect_nfds, _newselect_readfds)
  File "/home/qiling/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/select.py", line 30, in parse_fd_set
    fd_list.append(ql.os.fd[idx].fileno())
AttributeError: 'int' object has no attribute 'fileno'
Ran once without AFL attached.

**Screenshots**

![image](https://user-images.githubusercontent.com/32220354/116097760-03ffa180-a6dd-11eb-9603-c1fa731ca9cb.png)

**Additional context**
I have get snapshot.bin

what should I do
thx

**Comment by xwings** [comment]
Can you follow the video ? its in #134

**Comment by kirito999** [comment]
我尝试了fuzzing目录下面的三个例子，都没有跑起来，我猜是不是我配置的环境不太对，假期后会重新弄一下。

在尝试linux_x8664时，出现了和https://github.com/qilingframework/qiling/issues/780同样的问题，不过替换了examples/crackme_x86_linux.py还是没有效果。

不过在配置过程中，有一个地方不一样。在/fuzzing/linux_x8664/fuzz_x8664_linux.py中，提到After building afl++, make sure you install `unicorn_mode/setup_unicorn.sh`，但是我在unicorn_mode中没有找到setup_unicorn.sh的文件。而且每个案例都提到 Make sure Qiling uses our patched unicorn instead of it's own，想知道qiling的patched unicorn在哪里找，是不是因为这个地方导致的问题。

**Comment by kirito999** [comment]
thx：），I think I should edit the .py to run -U mode.

**Comment by dark-lbp** [comment]
Is this issue solved?

**Comment by kirito999** [comment]
> Is this issue solved?

sry, I can't solve the issue. Because I am interested in fuzz but I am poor in RE.
