### ISSUE TITLE
在syscall 钩子中，可能存在一处 bug

### ISSUE THREAD

**Issue by rootkiter** [qilingframework/qiling#807]
在 qiling/os/posix/posix.py 的关于 syscall hook 处理代码中，当钩子类型为 QL_INTERCEPT.ENTER 时，其返回值的类型判断，貌似有问题。源代码如下图所示：

<img width="760" alt="image" src="https://user-images.githubusercontent.com/6734184/120186409-0e660b80-c246-11eb-95bf-b66fd3c413ec.png">

如果 自定义函数返回的 ret 不是 int 类型，那么它自然也无法和 QL_CALL_BLOCK 进行位比较。

我认为正确的代码可能应该是：

if type(ret) is int and (ret & QL_CALL_BLOCK) == 0:

**Comment by wtdcode** [comment]
看起来是的，你能提个PR吗？

________________________________
From: rootkiter ***@***.***>
Sent: Monday, May 31, 2021 7:38:03 PM
To: qilingframework/qiling ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [qilingframework/qiling] 在syscall 钩子中，可能存在一处 bug (#807)


在 qiling/os/posix/posix.py 的关于 syscall hook 处理代码中，当钩子类型为 QL_INTERCEPT.ENTER 时，其返回值的类型判断，貌似有问题。源代码如下图所示：

[image]<https://user-images.githubusercontent.com/6734184/120186409-0e660b80-c246-11eb-95bf-b66fd3c413ec.png>

如果 自定义函数返回的 ret 不是 int 类型，那么它自然也无法和 QL_CALL_BLOCK 进行位比较。

我认为正确的代码可能应该是：

if type(ret) is int and (ret & QL_CALL_BLOCK) == 0:

―

**Comment by rootkiter** [comment]
好的，那我先提一个 PR 过来，然后再看。
