### ISSUE TITLE
lstrcmpiW/lstrcmpiA wrongly implemented as case sensitive

### ISSUE THREAD

**Issue by DK99** [qilingframework/qiling#813]
I noticed the implementation for the lstrcmpiW is using a case-sensitive compare [here](https://github.com/qilingframework/qiling/blob/ab97c27159d7c19792bebf6a277b760bfb0dc695/qiling/os/windows/dlls/kernel32/winbase.py#L251).

The Microsoft [documentation](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lstrcmpiw) is referring to this function as not case-sensitive.

**Comment by xwings** [comment]
Cool. good catch.

Thanks.
