### ISSUE TITLE
ELF 文件模拟时，如何增加自定义堆数据结构

### ISSUE THREAD

**Issue by rootkiter** [qilingframework/qiling#815]
我有个需求，是在ELF 文件模拟一半时，申请一个新的 堆内存布置数据。

查阅代码后发现在 loader/pe.py 和 loader/macos.py 中有  os.heap 对象的初始化代码，似乎比较满足我的需求。

但是在  loader/elf.py 中却没有这个实例对象，所以我的问题是：

这是个还没有在 ELF 中实现的机制，还是说，有一个相对的其他机制来完成类似的工作？

**Comment by wtdcode** [comment]
可以尝试强行调用libc的malloc函数，这样就不用手动维护了。

________________________________
From: rootkiter ***@***.***>
Sent: Monday, June 7, 2021 6:04:30 PM
To: qilingframework/qiling ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [qilingframework/qiling] ELF 文件模拟时，如何增加自定义堆数据结构 (#815)


我有个需求，是在ELF 文件模拟一半时，申请一个新的 堆内存布置数据。

查阅代码后发现在 loader/pe.py 和 loader/macos.py 中有 os.heap 对象的初始化代码，似乎比较满足我的需求。

但是在 loader/elf.py 中却没有这个实例对象，所以我的问题是：

这是个还没有在 ELF 中实现的机制，还是说，有一个相对的其他机制来完成类似的工作？

―
