### ISSUE TITLE
ql.nprint issue

### ISSUE THREAD

**Issue by xwings** [qilingframework/qiling#82]
There is a bug running netgear firmware. 

This only exits when  
`
ql.multithread      = False
`
We need to fix it. @ucgJhe 

`  
File "../qiling/os/linux/mips32el.py", line 56, in hook_syscall
    LINUX_SYSCALL_FUNC(ql, param0, param1, param2, param3, param4, param5)
  File "../qiling/os/posix/syscall.py", line 1163, in ql_syscall_vfork
    ql.nprint("vfork() = %d" % regreturn)
  File "../qiling/core.py", line 222, in nprint
    fd.info(*args, **kw)
AttributeError: '_io.TextIOWrapper' object has no attribute 'info'
`

**Comment by xwings** [comment]
qiling/os/linux/thread.py line 238
and 
qiling/os/linux/syscall.py line 1153-1156 need to be fixed.

**Comment by ucgJhe** [comment]
how do you expect the consequence of configs in the netgear example
1. multithread=False means running in just one thread
2. log_split=True means split the log for separate thread
but didnt we have only one thread bcuz option 1 ?
I am just confused.

**Comment by xwings** [comment]
Hi,

There are two things here. 

multithread and fork 

so, if multithread=False. we still need to split the fork process into different log.

and multithread=False still buggie, i might want to make sure multithread always false.

**Comment by ucgJhe** [comment]
got it.  pls check #86
