### ISSUE TITLE
getting errors while recreating HITBLockdown002 DIR815 fuzzing

### ISSUE THREAD

**Issue by wfwerf** [qilingframework/qiling#829]
ImportError: ERROR: fail to load the dynamic library.

I have watched the youtube video from HITBLockdown002 and was trying to recreate the scenario, the paths etc I have changed as required but now when I execute the sh script I am getting this error

![image](https://user-images.githubusercontent.com/85725095/123224020-65ef4400-d49f-11eb-8aa1-a4512b7eb7be.png)

I put AFL-DEBUG=1 in the sh script, but that didnt change anything and using the ulimit command wouldnt run the fuzzer. 

strange enough that its saying 
![image](https://user-images.githubusercontent.com/85725095/123243802-5a0c7d80-d4b1-11eb-8781-ec9e7f85f11f.png)

where as I have run pip3 install unicornafl and it says Requirement already satisfied now.

Please help

**Comment by elicn** [comment]
For some reason unicornafl cannot find its library dir. Try to prepend the fuzzing command line with:
`LIBUNICORNAFL_PATH=/home/rambo/.local/lib/python3.8/site-packages/unicornafl-1.0.3-py3.8.egg/unicornafl/lib`

**Comment by xwings** [comment]
Thanks for the help @elicn

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
