### ISSUE TITLE
When X64 simulates the Alloc probe function,GS is 0

### ISSUE THREAD

**Issue by VirMinions** [qilingframework/qiling#869]
![1695059d8303acaf00e3f20d08ab0304](https://user-images.githubusercontent.com/36877673/127306759-2b646560-80c4-491c-be20-5e5d4e4029d0.png)

**Comment by xwings** [comment]
Hi,

how can we reproduce this error ?

**Comment by VirMinions** [comment]
https://github.com/Lastline-Inc/iocs-tools/tree/main/2021-07-IcedID-Part-2，


I am running this script, sample MD5:4540798E2C25CC6BA15340C28D4D7FD5。
The script and sample are in the attachment


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qilingframework/qiling"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 晚上10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qilingframework/qiling] When X64 simulates the Alloc probe function,GS is 0 (#869)





 
Hi,
 
how can we reproduce this error ?

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
