### ISSUE TITLE
Profile option: set the list of allowed syscalls & apis

### ISSUE THREAD

**Issue by rakovskij-stanislav** [qilingframework/qiling#872]
During unpack process I usually know the list of syscalls and apis that I will face. For more accurate unpack process and lowering the chance of some unintended effects, I would like to set the list of allowed syscalls and & apis - so the emulation process will end on one of the unlisted syscall/api.

Feature request: setting the list of allowed functions in Profile file.

**Comment by xwings** [comment]
Sorry for the late reply.

profile is not for this purpose. But i think can easilly write an extension for the bypass ? 

This issue will close for now. If you have any more question, feel free to open it.
