### ISSUE TITLE
Qiling Sandbox - a trigger that will explicitly will turn on & off network.

### ISSUE THREAD

**Issue by rakovskij-stanislav** [qilingframework/qiling#873]
Windows network functions in qiling are mocking the internet abilities, like:
- `qiling/os/windows/dlls/wsock32.py`
- `qiling/os/windows/dlls/wininet.py`

But as for POSIX, syscalls are real: `ql_syscall_socket` uses class ql_socket from `qiling/os/posix/filestruct.py` that implements socket functionality.

It will be nice to make network things more clear for the user. We need to have a flag in a profile or as one of Sandbox params. This way winapi malware analysts will feel themselves free to implement winapi without any hesitations.

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
