### ISSUE TITLE
Failed to hijack stdin using the example from the doc

### ISSUE THREAD

**Issue by aesophor** [qilingframework/qiling#877]
**Describe the bug**
I followed [this page in the documentation](https://docs.qiling.io/en/latest/hijack/), but I couldn't successfully hijack stdin.

**Sample Code**
Unable to hijack stdin (extracted and modified from the doc):
```python
ql = Qiling(path, rootfs)
ql.stdin = StringBuffer()
ql.stdin.write(b"AAAA\n")
```

Able to hijack stdin:
```python
ql = Qiling(path, rootfs, stdin=StringBuffer())
ql.stdin.write(b"AAAA\n")
```

**Expected behavior**
The doc showed this example, and users should be able to hijack stdin with:
```python
ql = Qiling(path, rootfs)
ql.stdin = StringBuffer()
```

**Screenshots**
(None)

**Additional context**
(None)

**Comment by elicn** [comment]
Thanks for reporting this.

It looks like the reason for that is the OS initialization that takes the current values of `stdin`, `stdout` and `stderr` at the time of Qiling instance initialization and do not update it upon setting new values. To solve this, the OS object would need to both run:
```python
if self.ql.stdin != 0:
     self.stdin = self.ql.stdin

if self.ql.stdout != 0:
    self.stdout = self.ql.stdout

if self.ql.stderr != 0:
    self.stderr = self.ql.stderr
```
and
```python
self._fd[0] = self.stdin
self._fd[1] = self.stdout
self._fd[2] = self.stderr
```
at the time of OS `run` (confirmed to work for Linux OS).
That said, an elegant fix will most likely have to standardize the access to `stdin`, `stdout` and `stderr` across all OS types (perhaps by turning them into properties)

**Comment by elicn** [comment]
@xwings 
I am thinking of detaching `stdin`, `stdout` and `stderr` from the `Qiling` class and move them to OS as properties.
That would help offloading some of the `Qiling` accessors to their appropriate locations.
What do you think?

**Comment by xwings** [comment]
so u gonna set using ql.os.stdin ?

i dont remember why we put it in core. but u can try

**Comment by elicn** [comment]
Done (see #898)
@aesophor, let me know whether that solved the problem (once the PR merges).

**Comment by aesophor** [comment]
@elicn
Many thanks for your time and effort. I'll let you know once it has been merged.

**Comment by xwings** [comment]
looks ok, let me do some test. should be quick

**Comment by elicn** [comment]
@aesophor merged.

**Comment by aesophor** [comment]
@elicn 

I cloned the entire repo again, and checkout to the `dev` branch (just to make sure everything is up-to-date), and I have this little script which is modified from [the doc](https://docs.qiling.io/en/latest/hijack/). However, hijacking still seems to fail.

```python3
#!/usr/bin/env python3

from qiling import *

class StringBuffer:
    def __init__(self):
        self.buffer = b''

    def read(self, n):
        ret = self.buffer[:n]
        self.buffer = self.buffer[n:]
        return ret

    def readline(self, end=b'\n'):
        ret = b''
        while True:
            c = self.read(1)
            ret += c
            if c == end:
                break
        return ret

    def write(self, string):
        self.buffer += string
        return len(string)


def our_sandbox(path, rootfs):
    ql = Qiling(path, rootfs)
    ql.os.stdin = StringBuffer()
    ql.os.stdin.write(b'A' * 100)
    ql.run()


if __name__ == '__main__':
    our_sandbox(["bof"], "rootfs/x8664_linux")
```

However, if I pass an instance of `StringBuffer` as the Qiling ctor's stdin argument, then hijacking works.

```python3
def our_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, stdin = StringBuffer())
    ql.os.stdin.write(b'A' * 100)
    ql.run()
```

As for the program I'm trying to emulate, here's the source code:

```c
#include <stdio.h>
#include <unistd.h>

int main() {
    char buf[16];
    puts("overflow me:");
    read(0, buf, 400);
}
```

If I run the full example provided above (which is taken from the doc and slightly modified), qiling will not write anything to stdin, and the program will pause at "overflow me:", waiting for user to type something.

But if I rewrite `our_sandbox`, then qiling will show this error: `[x]     Error: PC(0x4141414141414141) Unreachable`, which proves my input (b'A' * 100) has been correctly written to the program's stdin.

Thank you again!

**Comment by elicn** [comment]
@aesophor, thanks for the details.

I compiled the C code you provided and used your Python script as is, and it seems to work as intended; that is, crashing with `[x] Error: PC(0x4141414141414141) Unreachable`. I made sure that I indeed used the post-initialization assignment and not in the constructor. Tested on a WSL Ubuntu 20.04.2

Can you make sure you are using the most recent `dev` copy?
When in `qiling` directory, what is the output of `git branch -vv` ?

**Comment by aesophor** [comment]
@elicn

Here's the output of `git branch -vv`. So weird... 😖 

<img width="731" alt="Screen Shot 2021-08-25 at 3 51 37 PM" src="https://user-images.githubusercontent.com/32998585/130749821-be437341-9183-42bb-8d80-8119a5f9264a.png">

**Comment by elicn** [comment]
Here are the steps on my side, perhaps you'll notice which I didn't:

`git` output:
![1](https://user-images.githubusercontent.com/10291650/130762343-6f52670f-4276-4056-b627-ec597fc570ab.png)

Python script:
![2](https://user-images.githubusercontent.com/10291650/130762394-862623f2-fb06-4a31-9243-816ed1e4647a.png)

C source and compilation:
![3](https://user-images.githubusercontent.com/10291650/130762445-9805978c-ab3c-47e8-af7e-17819f6b5874.png)

Script crashes as intended:
![4](https://user-images.githubusercontent.com/10291650/130762526-64a5918c-86c9-4c1e-8ee5-b215bc59a426.png)

**Comment by elicn** [comment]
@aesophor, any news regarding this one..?

**Comment by aesophor** [comment]
@elicn HI, sorry for late reply!
Could you give me a few more days? I'll reach back to you soon.

**Comment by aesophor** [comment]
I was a little busy the other day, so sorry for late reply.

I found that if I place that python script (say, `test.py`) inside qiling's directory, then it crashes as intended.
However, if it is placed outside qiling's directory, then stdin won't get any input at all.

In your screenshot, I notice your script is also placed outside qiling's directory, so I try to mimic your directory layout:

![Screen Shot 2021-09-05 at 1 30 56 AM](https://user-images.githubusercontent.com/32998585/132103426-79e2d64c-aa81-4e1c-8a74-134e05b75cd2.png)

As shown in the above screenshot, `test.py` is placed at ../test/test.py (relative to qiling's dir), and running it like this and the program gets stuck at read().

```bash
/home/aesophor/Code/requiem/libs/qiling [git::dev] [aesophor@valkyrie] [1:32]
> ../test/test.py
```

However, if I move that `test.py` inside the qiling directory, then everything works. (I'm on Arch linux 5.13.13-arch1-1, but I think this should be irrelevant...?)

**Comment by elicn** [comment]
It looks like you have a Qiling installation on your system, and it is being used when the script is outside of the Qiling git dir.
To ensure you are using the dev Qiling, prepend the command line with PYTHONPATH like this: `PYTHONPATH=path/to/qiling/dir python3 my_script.py`

**Comment by aesophor** [comment]
lol I forgot that I've installed it with `pip`
Now it works like a charm, thank you so much for your support! 😄
