### ISSUE TITLE
Memory search

### ISSUE THREAD

**Issue by nescafename** [qilingframework/qiling#904]
https://github.com/qilingframework/qiling/blob/4cae8b6cca92ec9423ba0d8e9a8bb814be2ace10/qiling/os/memory.py#L315

Is that supposed logic? I don't understand why mem.search doesn't cover the case(3) when full region(begin-end) in range of mapped region(lbound-ubound)?

```js
   begin                                        end
1) [                      [                      ] 
                        lbound

   begin                                        end
2) [                      ]                      ] 
                        ubound

   lbound                                              ubound
3) [                      [           ]                   ] 
                      begin           end
```

ref: https://stackoverflow.com/questions/325933/determine-whether-two-date-ranges-overlap/325964#325964

example:

![Snipaste_2021-08-29_23-34-25](https://user-images.githubusercontent.com/77633834/131264608-d2298cac-7b5f-4420-8839-f9cc5e9f9c71.png)
```
[PE]: 0x18026830b <= 0x180000000 < 0x18026833d or 0x18026830b < 0x1802a7000 <= 0x18026833d
```

It won't return any occurences if full range in mapped region.
Meanwhile:
```python
def overlap(start1, end1, start2, end2):
    """Does the range (start1, end1) overlap with (start2, end2)?"""
    return not (end1 < start2 or end2 < start1)

def mem_search(ql, needle: bytes, begin: int = None, end: int = None):

    assert begin < end, 'search arguments do not make sense'

    ranges = [(max(begin, lbound), min(ubound, end)) for lbound, ubound, _, _ in ql.mem.map_info if overlap(begin, end, lbound, ubound)]

    results = []

    for lbound, ubound in ranges:
        haystack = ql.mem.read(lbound, ubound - lbound)
        local_results = (match.start(0) + lbound for match in re.finditer(re.escape(needle), haystack))

        results.extend(local_results)

    return results
```
works fine

**Comment by elicn** [comment]
This is indeed a good catch; the existing code seems to overlook that case.
Would you create a PR for it?

**Comment by xwings** [comment]
Good catch indeed. Please create a PR and thanks @andrwnoskov in advance
