### ISSUE TITLE
Disassembler throws hex() error

### ISSUE THREAD

**Issue by junyian** [qilingframework/qiling#908]
I get this error when starting Qiling with QL_VERBOSE.DISASM.

 File "C:\Python37\lib\site-packages\qiling\arch\utils.py", line 39, in disassembler
    log_data = f'{address:0{ql.archbit // 4}x} [{name:20s} + {offset:#08x}]  {tmp.hex(" "):30s}'
TypeError: hex() takes no arguments (1 given)

Locally I fixed this by change to tmp.hex():30s.

I'm not very well versed with github usage yet so I'm not so comfortable pushing code to a public repository like this one, especially for such an amazing tool :)

**Comment by nullableVoidPtr** [comment]
`bytes.hex(sep)` is an addition to Python 3.8, though I'm not exactly certain on what minimum version this project would want to target. For the time being, you should probably update Python. :wink:

**Comment by junyian** [comment]
Interesting... I tried that line of code on 3.9 console (different VM) and it threw the same error. But now I can't replicate it anymore. But yeah, I need to update Python on this VM as soon as I can, or setup pyenv due to other lib dependencies.

Thanks for responding. :D
