### ISSUE TITLE
os\utils.py ql_asm2bytes issue

### ISSUE THREAD

**Issue by kabeor** [qilingframework/qiling#91]
the function **compile_instructions** in ql_asm2bytes used **unhexlify**, but it haven‘t import unhexlify from binascii.

This will cause the following problems:
 **NameError: name 'unhexlify' is not defined**

**Comment by xwings** [comment]
will you be able to do a pull request ?

**Comment by kabeor** [comment]
> will you be able to do a pull request ?

ok, I had pull that

**Comment by xwings** [comment]
Thanks for the PR and i will close
