### ISSUE TITLE
STM32的案例可以运行吗？

### ISSUE THREAD

**Issue by JiaDuo** [qilingframework/qiling#913]
***Describe the bug**
examples/rootfs/mcu/stm32f411 存在stm32的案例，这个案例我尝试运行有些错误。
轻微是否有这个案例的使用说明或者成功经验。

**Sample Code**
```python
from qiling import *

# sandbox to emulate the EXE
def my_sandbox(path, rootfs):
    # setup Qiling engine
    ql = Qiling(path, rootfs)
    # now emulate the EXE
    ql.run()

if __name__ == "__main__":
    my_sandbox(["examples/rootfs/mcu/stm32f411/os-demo.elf"], "examples/rootfs/mcu/")

```

**Screenshots**
zer0usn@zer0usn:~/tools/qiling-1.2.4$ python3 stm32.py 
[x]	

[x]	r0	:	 0x20000000
[x]	r1	:	 0x20000010
[x]	r2	:	 0xe000ed00
[x]	r3	:	 0x0
[x]	r4	:	 0x20004020
[x]	r5	:	 0x0
[x]	r6	:	 0x0
[x]	r7	:	 0x0
[x]	r8	:	 0x0
[x]	r9	:	 0x0
[x]	r10	:	 0x0
[x]	r11	:	 0x0
[x]	r12	:	 0x0
[x]	sp	:	 0x20020000
[x]	lr	:	 0x80021c7
[x]	pc	:	 0x80010c4
[x]	f0	:	 0x0
[x]	f1	:	 0x0
[x]	f2	:	 0x0
[x]	f3	:	 0x0
[x]	f4	:	 0x0
[x]	f5	:	 0x0
[x]	f6	:	 0x0
[x]	f7	:	 0x0
[x]	fps	:	 0x0
[x]	cpsr	:	 0x600001f3
[x]	c1_c0_2	:	 0xf00000
[x]	c13_c0_3	:	 0x0
[x]	fpexc	:	 0x40000000
[x]	

[x]	PC = 0x80010c4
[x]	 (/home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf+0x80010c4)
[=]	Start      End        Perm    Label          Image
[=]	08000000 - 08003000   rwx     /home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf   /home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf
[=]	20000000 - 20005000   rw-     /home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf   /home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf
[=]	20005000 - 20007000   rwx     [hook_mem]     
[=]	7ff0d000 - 7ff3d000   rwx     [stack]        
[=]	ffff0000 - ffff1000   rwx     [arm_tls]      
[x]	['0x3', '0x4a', '0xd2', '0xf8', '0x88', '0x30', '0x43', '0xf4']
[=]	

[=]	0x080010c4 {os-demo.elf          + 0x0010c4}   03 4a d2 f8 88 30 43 f4 70 03 c2 f8 88 30 70 47 00 ed 00 e0 03 4b 03 60 03 4b 0b 60 80 23 13 60 70 47 00 bf 2c 02 00 20 2c 00 00 20 70 b5 04 46 02 68 13 69 23 f4 40 53 c1 68 0b 43 13 61 83 68 ldr r2, [pc, #0xc]
> ldr.w r3, [r2, #0x88]
> orr r3, r3, #0xf00000
> str.w r3, [r2, #0x88]
> bx lr
> stc p0, c14, [r0, #-0]
> ldr r3, [pc, #0xc]
> str r3, [r0]
> ldr r3, [pc, #0xc]
> str r3, [r1]
> movs r3, #0x80
> str r3, [r2]
> bx lr
> nop 
> lsls r4, r5, #8
> movs r0, #0
> movs r4, r5
> movs r0, #0
> push {r4, r5, r6, lr}
> mov r4, r0
> ldr r2, [r0]
> ldr r3, [r2, #0x10]
> bic r3, r3, #0x3000
> ldr r1, [r0, #0xc]
> orrs r3, r1
> str r3, [r2, #0x10]
> ldr r3, [r0, #8]
Traceback (most recent call last):
  File "stm32.py", line 11, in <module>
    my_sandbox(["examples/rootfs/mcu/stm32f411/os-demo.elf"], "examples/rootfs/mcu/")
  File "stm32.py", line 8, in my_sandbox
    ql.run()
  File "/home/zer0usn/tools/qiling-1.2.4/qiling/core.py", line 755, in run
    self.os.run()
  File "/home/zer0usn/tools/qiling-1.2.4/qiling/os/linux/linux.py", line 136, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/zer0usn/tools/qiling-1.2.4/qiling/core.py", line 896, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/home/zer0usn/.local/lib/python3.8/site-packages/unicorn/unicorn.py", line 318, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)

**Comment by wtdcode** [comment]
目前mcu尚未发布，感谢关注
________________________________
From: jiaduo ***@***.***>
Sent: Tuesday, September 14, 2021 10:02:14 AM
To: qilingframework/qiling ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [qilingframework/qiling] STM32的案例可以运行吗？ (#913)


*Describe the bug
examples/rootfs/mcu/stm32f411 存在stm32的案例，这个案例我尝试运行有些错误。
轻微是否有这个案例的使用说明或者成功经验。

Sample Code

from qiling import *



# sandbox to emulate the EXE

def my_sandbox(path, rootfs):

    # setup Qiling engine

    ql = Qiling(path, rootfs)

    # now emulate the EXE

    ql.run()



if __name__ == "__main__":

    my_sandbox(["examples/rootfs/mcu/stm32f411/os-demo.elf"], "examples/rootfs/mcu/")

Screenshots
***@***.***:~/tools/qiling-1.2.4$ python3 stm32.py
[x]

[x] r0 : 0x20000000
[x] r1 : 0x20000010
[x] r2 : 0xe000ed00
[x] r3 : 0x0
[x] r4 : 0x20004020
[x] r5 : 0x0
[x] r6 : 0x0
[x] r7 : 0x0
[x] r8 : 0x0
[x] r9 : 0x0
[x] r10 : 0x0
[x] r11 : 0x0
[x] r12 : 0x0
[x] sp : 0x20020000
[x] lr : 0x80021c7
[x] pc : 0x80010c4
[x] f0 : 0x0
[x] f1 : 0x0
[x] f2 : 0x0
[x] f3 : 0x0
[x] f4 : 0x0
[x] f5 : 0x0
[x] f6 : 0x0
[x] f7 : 0x0
[x] fps : 0x0
[x] cpsr : 0x600001f3
[x] c1_c0_2 : 0xf00000
[x] c13_c0_3 : 0x0
[x] fpexc : 0x40000000
[x]

[x] PC = 0x80010c4
[x] (/home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf+0x80010c4)
[=] Start End Perm Label Image
[=] 08000000 - 08003000 rwx /home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf /home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf
[=] 20000000 - 20005000 rw- /home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf /home/zer0usn/tools/qiling-1.2.4/examples/rootfs/mcu/stm32f411/os-demo.elf
[=] 20005000 - 20007000 rwx [hook_mem]
[=] 7ff0d000 - 7ff3d000 rwx [stack]
[=] ffff0000 - ffff1000 rwx [arm_tls]
[x] ['0x3', '0x4a', '0xd2', '0xf8', '0x88', '0x30', '0x43', '0xf4']
[=]

[=] 0x080010c4 {os-demo.elf + 0x0010c4} 03 4a d2 f8 88 30 43 f4 70 03 c2 f8 88 30 70 47 00 ed 00 e0 03 4b 03 60 03 4b 0b 60 80 23 13 60 70 47 00 bf 2c 02 00 20 2c 00 00 20 70 b5 04 46 02 68 13 69 23 f4 40 53 c1 68 0b 43 13 61 83 68 ldr r2, [pc, #0xc]

ldr.w r3, [r2, #0x88]
orr r3, r3, #0xf00000
str.w r3, [r2, #0x88]
bx lr
stc p0, c14, [r0, #-0]
ldr r3, [pc, #0xc]
str r3, [r0]
ldr r3, [pc, #0xc]
str r3, [r1]
movs r3, #0x80
str r3, [r2]
bx lr
nop
lsls r4, r5, #8<https://github.com/qilingframework/qiling/pull/8>
movs r0, #0
movs r4, r5
movs r0, #0
push {r4, r5, r6, lr}
mov r4, r0
ldr r2, [r0]
ldr r3, [r2, #0x10]
bic r3, r3, #0x3000
ldr r1, [r0, #0xc]
orrs r3, r1
str r3, [r2, #0x10]
ldr r3, [r0, #8<https://github.com/qilingframework/qiling/pull/8>]
Traceback (most recent call last):
File "stm32.py", line 11, in
my_sandbox(["examples/rootfs/mcu/stm32f411/os-demo.elf"], "examples/rootfs/mcu/")
File "stm32.py", line 8, in my_sandbox
ql.run()
File "/home/zer0usn/tools/qiling-1.2.4/qiling/core.py", line 755, in run
self.os.run()
File "/home/zer0usn/tools/qiling-1.2.4/qiling/os/linux/linux.py", line 136, in run
self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
File "/home/zer0usn/tools/qiling-1.2.4/qiling/core.py", line 896, in emu_start
self.uc.emu_start(begin, end, timeout, count)
File "/home/zer0usn/.local/lib/python3.8/site-packages/unicorn/unicorn.py", line 318, in emu_start
raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)

―

**Comment by xwings** [comment]
Soon!

**Comment by cla7aye15I4nd** [comment]
mcu has been released, so I close the issue.

**Comment by wllis** [comment]
期待✌
