### ISSUE TITLE
Rebase before merge

### ISSUE THREAD

**Issue by Inndy** [qilingframework/qiling#94]
Git commits like these should be [squashed](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) before merging into master branch

![image](https://user-images.githubusercontent.com/3402337/74304325-9ac19600-4d97-11ea-9be7-c9338cec8267.png)

**Comment by xwings** [comment]
fair enuf. i agree.

thanks for brining it out !

**Comment by chfl4gs** [comment]
noted
