### ISSUE TITLE
I am trying to fuzz tenda c15

### ISSUE THREAD

**Issue by KA2010** [qilingframework/qiling#983]
<img width="1056" alt="Screen Shot 2021-11-07 at 2 44 27 AM" src="https://user-images.githubusercontent.com/70834906/140636833-f86894cc-cd36-4a65-9054-a6ade377472c.png">
 It gave me error about arm arch, How I can solve this error?

**Comment by wtdcode** [comment]
Your Unicorn version is too old. Switch to Unicorn2.

**Comment by KA2010** [comment]
I did not find Unicorn2

**Comment by KA2010** [comment]
I have install Unicorn2 but the issue still same.

**Comment by wtdcode** [comment]
> I have install Unicorn2 but the issue still same.

What's your `python3 -c "import unicorn;print(unicorn.__version__)"` output?

**Comment by KA2010** [comment]
kawkab@cysecuga:~$ python3 -c "import unicorn;print(unicorn.__version__)"
2.0.0

**Comment by wtdcode** [comment]
> kawkab@cysecuga:~$ python3 -c "import unicorn;print(unicorn.**version**)" 2.0.0

Ah, sry I got it. The unicornafl doesn't support uc2 for now and I will release a new unicornafl for that. You may revert to an older version of qiling for a temporary fix.

**Comment by KA2010** [comment]
How to revert to an older version of qiling ?

**Comment by wtdcode** [comment]
a6914111c47a7e0d372b08ec0dce95842229a3c1

**Comment by KA2010** [comment]
> > kawkab@cysecuga:~$ python3 -c "import unicorn;print(unicorn.**version**)" 2.0.0
> 
> Ah, sry I got it. The unicornafl doesn't support uc2 for now and I will release a new unicornafl for that. You may revert to an older version of qiling for a temporary fix.
Is the new unicornafl support uc2 release yet ?
If not, What time may you will release it ?

**Comment by KA2010** [comment]
Is the new unicornafl support uc2 release yet ?
If not, What time may you will release it ?

**Comment by wtdcode** [comment]
> Is the new unicornafl support uc2 release yet ?
> If not, What time may you will release it ?

https://github.com/wtdcode/unicorn2afl
The backport is done already, however you may get a lower speed (about 60%) compared to unicorn1 and that’s why it hasn’t been officially released.

**Comment by KA2010** [comment]
**even I download unicorn2afl correctly but still gave me same error.** 
 File "./fuzz_tendaac15_httpd.py", line 23, in <module>
    from qiling.arch.arm_const import *
  File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/arch/arm_const.py", line 30, in <module>
    "xpsr_nzcvqg": UC_ARM_REG_XPSR_NZCVQG,
NameError: name 'UC_ARM_REG_XPSR_NZCVQG' is not defined

[-] Hmm, looks like the target binary terminated before we could complete a
handshake with the injected code. You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
      1. Run again with AFL_DEBUG=1 set and check the output of the target
         binary for clues.
      2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
         generated core dump.

    - Possibly the target requires a huge coverage map and has CTORS.
      Retry with setting AFL_MAP_SIZE=10000000.

Otherwise there is a horrible bug in the fuzzer.
Poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : afl_fsrv_start(), src/afl-forkserver.c:1032

**Comment by wtdcode** [comment]
> **even I download unicorn2afl correctly but still gave me same error.** File "./fuzz_tendaac15_httpd.py", line 23, in from qiling.arch.arm_const import * File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/arch/arm_const.py", line 30, in "xpsr_nzcvqg": UC_ARM_REG_XPSR_NZCVQG, NameError: name 'UC_ARM_REG_XPSR_NZCVQG' is not defined
> 
> [-] Hmm, looks like the target binary terminated before we could complete a handshake with the injected code. You can try the following:
> 
> ```
> - The target binary crashes because necessary runtime conditions it needs
>   are not met. Try to:
>   1. Run again with AFL_DEBUG=1 set and check the output of the target
>      binary for clues.
>   2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
>      generated core dump.
> 
> - Possibly the target requires a huge coverage map and has CTORS.
>   Retry with setting AFL_MAP_SIZE=10000000.
> ```
> 
> Otherwise there is a horrible bug in the fuzzer. Poke [afl-users@googlegroups.com](mailto:afl-users@googlegroups.com) for troubleshooting tips.
> 
> [-] PROGRAM ABORT : Fork server handshake failed Location : afl_fsrv_start(), src/afl-forkserver.c:1032

What's your `python3 -c "import unicorn;import importlib.metadata;print(importlib.metadata.version('unicorn'))"` outputs?

**Comment by KA2010** [comment]
1.0.2rc4

**Comment by wtdcode** [comment]
> 1.0.2rc4

Obviously, you are using an extremely outdated unicorn.

**Comment by elicn** [comment]
Also recommending to update to most recent Qiling `dev` code, which fixed an infinite wait loop in Tenda
See: #1024

**Comment by KA2010** [comment]
**I have upgrade unicorn but still error occurs** pip install unicorn --upgrade
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting unicorn
  Using cached unicorn-1.0.3-py2.py3-none-manylinux1_x86_64.whl (8.1 MB)
**ERROR: qiling 1.4.0 has requirement unicorn>=2.0.0-rc3, but you'll have unicorn 1.0.3 which is incompatible.
ERROR: angr 9.0.10534 has requirement unicorn==1.0.2rc4, but you'll have unicorn 1.0.3 which is incompatible.**
Installing collected packages: unicorn
  Attempting uninstall: unicorn
    Found existing installation: unicorn 1.0.2rc4
    Uninstalling unicorn-1.0.2rc4:
      Successfully uninstalled unicorn-1.0.2rc4
Successfully installed unicorn-1.0.3
**When I upgrade it it gave me "1.0.3" note that I already install unicorn2** 
I am kind of confuse, I do not know how to solve this issue.

**Comment by KA2010** [comment]
**I have upgrade unicorn but still error occurs** 
>pip install unicorn --upgrade
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
from cryptography.utils import int_from_bytes
Collecting unicorn
Using cached unicorn-1.0.3-py2.py3-none-manylinux1_x86_64.whl (8.1 MB)
**ERROR: qiling 1.4.0 has requirement unicorn>=2.0.0-rc3, but you'll have unicorn 1.0.3 which is incompatible.
ERROR: angr 9.0.10534 has requirement unicorn==1.0.2rc4, but you'll have unicorn 1.0.3 which is incompatible.**
Installing collected packages: unicorn
Attempting uninstall: unicorn
Found existing installation: unicorn 1.0.2rc4
Uninstalling unicorn-1.0.2rc4:
Successfully uninstalled unicorn-1.0.2rc4
Successfully installed unicorn-1.0.3

**When I upgrade it it gave me "1.0.3" note that I already install unicorn2
I am kind of confuse, I do not know how to solve this issue.**

**Comment by wtdcode** [comment]
> **I have upgrade unicorn but still error occurs**
> 
> > pip install unicorn --upgrade
> > /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
> > from cryptography.utils import int_from_bytes
> > /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
> > from cryptography.utils import int_from_bytes
> > Collecting unicorn
> > Using cached unicorn-1.0.3-py2.py3-none-manylinux1_x86_64.whl (8.1 MB)
> > **ERROR: qiling 1.4.0 has requirement unicorn>=2.0.0-rc3, but you'll have unicorn 1.0.3 which is incompatible.
> > ERROR: angr 9.0.10534 has requirement unicorn==1.0.2rc4, but you'll have unicorn 1.0.3 which is incompatible.**
> > Installing collected packages: unicorn
> > Attempting uninstall: unicorn
> > Found existing installation: unicorn 1.0.2rc4
> > Uninstalling unicorn-1.0.2rc4:
> > Successfully uninstalled unicorn-1.0.2rc4
> > Successfully installed unicorn-1.0.3
> 
> **When I upgrade it it gave me "1.0.3" note that I already install unicorn2 I am kind of confuse, I do not know how to solve this issue.**

Unicorn2 means unicorn 2.0.0. You may install it via pip install —pre unicorn

**Comment by KA2010** [comment]
**pip install --pre unicorn**
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
**Requirement already satisfied: unicorn in ./.local/lib/python3.8/site-packages (1.0.3)**
**It just install 1.0.3 as before**
**Why Is not install unicorn 2.0.0?**

**Comment by wtdcode** [comment]
> **pip install --pre unicorn** /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes **Requirement already satisfied: unicorn in ./.local/lib/python3.8/site-packages (1.0.3)** **It just install 1.0.3 as before** **Why Is not install unicorn 2.0.0?**

`pip install --pre --upgrade unicorn`

**Comment by KA2010** [comment]
**Thanks it does install correctly but the issue still not solved**[*] Spinning up the fork server...
Traceback (most recent call last):
  File "./fuzz_tendaac15_httpd.py", line 23, in <module>
    from qiling.arch.arm_const import *
  File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/arch/arm_const.py", line 30, in <module>
    "xpsr_nzcvqg": UC_ARM_REG_XPSR_NZCVQG,
NameError: name 'UC_ARM_REG_XPSR_NZCVQG' is not defined

[-] Hmm, looks like the target binary terminated before we could complete a
handshake with the injected code. You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
      1. Run again with AFL_DEBUG=1 set and check the output of the target
         binary for clues.
      2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
         generated core dump.

    - Possibly the target requires a huge coverage map and has CTORS.
      Retry with setting AFL_MAP_SIZE=10000000.

Otherwise there is a horrible bug in the fuzzer.
Poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : afl_fsrv_start(), src/afl-forkserver.c:1032

**Comment by KA2010** [comment]
**Thanks it does install correctly but the issue still not solved**
[*] Spinning up the fork server...
Traceback (most recent call last):
File "./fuzz_tendaac15_httpd.py", line 23, in
from qiling.arch.arm_const import *
File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/arch/arm_const.py", line 30, in
"xpsr_nzcvqg": UC_ARM_REG_XPSR_NZCVQG,
NameError: name 'UC_ARM_REG_XPSR_NZCVQG' is not defined

[-] Hmm, looks like the target binary terminated before we could complete a
handshake with the injected code. You can try the following:

- The target binary crashes because necessary runtime conditions it needs
  are not met. Try to:
  1. Run again with AFL_DEBUG=1 set and check the output of the target
     binary for clues.
  2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
     generated core dump.

- Possibly the target requires a huge coverage map and has CTORS.
  Retry with setting AFL_MAP_SIZE=10000000.
Otherwise there is a horrible bug in the fuzzer.
Poke afl-users@googlegroups.com for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
Location : afl_fsrv_start(), src/afl-forkserver.c:1032

**Comment by wtdcode** [comment]
> **Thanks it does install correctly but the issue still not solved** [*] Spinning up the fork server... Traceback (most recent call last): File "./fuzz_tendaac15_httpd.py", line 23, in from qiling.arch.arm_const import * File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/arch/arm_const.py", line 30, in "xpsr_nzcvqg": UC_ARM_REG_XPSR_NZCVQG, NameError: name 'UC_ARM_REG_XPSR_NZCVQG' is not defined
> 
> [-] Hmm, looks like the target binary terminated before we could complete a handshake with the injected code. You can try the following:
> 
> * The target binary crashes because necessary runtime conditions it needs
>   are not met. Try to:
>   
>   1. Run again with AFL_DEBUG=1 set and check the output of the target
>      binary for clues.
>   2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
>      generated core dump.
> * Possibly the target requires a huge coverage map and has CTORS.
>   Retry with setting AFL_MAP_SIZE=10000000.
>   Otherwise there is a horrible bug in the fuzzer.
>   Poke [afl-users@googlegroups.com](mailto:afl-users@googlegroups.com) for troubleshooting tips.
> 
> [-] PROGRAM ABORT : Fork server handshake failed Location : afl_fsrv_start(), src/afl-forkserver.c:1032

Are you sure `python3 -c "import unicorn;import importlib.metadata;print(importlib.metadata.version('unicorn'))"` outputs `2.0.0rc5`?

**Comment by KA2010** [comment]
**Yes it is.**
>python3 -c "import unicorn;import importlib.metadata;print(importlib.metadata.version('unicorn'))"
2.0.0rc5.post1

**Comment by wtdcode** [comment]
> **Yes it is.**
> 
> > python3 -c "import unicorn;import importlib.metadata;print(importlib.metadata.version('unicorn'))"
> > 2.0.0rc5.post1

Then, what's your `python3 -c "import importlib.metadata;print(importlib.metadata.version('unicornafl'))"` outputs? It it's not `2.0.0`, could you try `pip install --upgrade unicornafl`?

**Comment by KA2010** [comment]
**Thank you so much the issue is solved.**
But I am getting new issue that 'snapshot.bin' is not found ! Why ?
[*] Spinning up the fork server...
Traceback (most recent call last):
  File "./fuzz_tendaac15_httpd.py", line 81, in <module>
    main(sys.argv[1])
  File "./fuzz_tendaac15_httpd.py", line 34, in main
    ql.restore(snapshot="snapshot.bin")
  File "/home/kawkab/.local/lib/python3.8/site-packages/qiling/core.py", line 769, in restore
    with open(snapshot, "rb") as load_state:
FileNotFoundError: [Errno 2] No such file or directory: 'snapshot.bin'

**Comment by KA2010** [comment]
**I know that I have to run ./addressNat_overflow.sh to crash to generate snapshot.bin
But it gave me permission denied even if I am root.**
 root@cysecuga:/home/kawkab/qiling/examples/fuzzing/tenda_ac15# ./addressNat_overflow.sh
bash: ./addressNat_overflow.sh: Permission denied

**Comment by KA2010** [comment]
Thank you so much the issue is solved.

**Comment by KA2010** [comment]
I am getting new issue
[*] Spinning up the fork server...
Traceback (most recent call last):
  File "./fuzz_tendaac15_httpd.py", line 80, in <module>
    main(sys.argv[1])
  File "./fuzz_tendaac15_httpd.py", line 30, in main
    ql = Qiling(["rootfs/bin/httpd"], "rootfs", verbose=QL_VERBOSE.DEBUG, console = True if enable_trace else False)
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 143, in __init__
    raise QlErrorFileNotFound("Target binary not found: %s" %(self._argv[0]))
qiling.exception.QlErrorFileNotFound: Target binary not found: **rootfs/bin/httpd**

**Comment by wtdcode** [comment]
> I am getting new issue [*] Spinning up the fork server... Traceback (most recent call last): File "./fuzz_tendaac15_httpd.py", line 80, in main(sys.argv[1]) File "./fuzz_tendaac15_httpd.py", line 30, in main ql = Qiling(["rootfs/bin/httpd"], "rootfs", verbose=QL_VERBOSE.DEBUG, console = True if enable_trace else False) File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 143, in **init** raise QlErrorFileNotFound("Target binary not found: %s" %(self._argv[0])) qiling.exception.QlErrorFileNotFound: Target binary not found: **rootfs/bin/httpd**

The error itself speaks loudly.

**Comment by KA2010** [comment]
Yes it's,
but the target binary is already in rootfs directory.
