### ISSUE TITLE
posix lseek gives wrong return value

### ISSUE THREAD

**Issue by dkw72n** [qilingframework/qiling#987]
**Describe the bug**
posix lseek gives wrong return value

**Sample Code**
```bash
$ qltool run -f `which tail` --rootfs / --args `which tail`
...
[=]	openat(fd = 0xffffff9c, path = 0x80000000dfe0, flags = 0x0, mode = 0x0) = 0x3
[=]	lseek(fd = 0x3, offset = 0x0, origin = 0x2) = 0x0
...
```

**Expected behavior**
lseek with `origin = 0x2` on an non-empty file should not return  0x0

**Additional context**
The root cause is lying in https://github.com/qilingframework/qiling/blob/94bf7a3bc4e3ea0cffaaa52dbc477c11030f631b/qiling/os/posix/syscall/unistd.py#L148
```
        try:
            regreturn = ql.os.fd[fd].lseek(offset, lseek_origin)
        except OSError:
            regreturn = -1
        else:
            regreturn = 0
```
`else` should not be used here. According to the Python doc:
> The try … except statement has an optional else clause, which, when present, must follow all except clauses. It is useful for code that must be executed if the try clause does **NOT** raise an exception.

**Comment by wtdcode** [comment]
Fixed in ac7c9f69890c37fde7c8ac5f957aa112485fe3fb.

**Comment by elicn** [comment]
I believe `ql.os.fd` holds an array of `ql_file` objects, not `SimpleStringBuffer` ones so I don't see how that PR fixes this.
The fix should be as proposed: removing the `else` clause to let `regreturn` keep the value that was returned from `lseek`.

**Comment by wtdcode** [comment]
> I believe `ql.os.fd` holds an array of `ql_file` objects, not `SimpleStringBuffer` ones so I don't see how that PR fixes this. The fix should be as proposed: removing the `else` clause to let `regreturn` keep the value that was returned from `lseek`.

That PR is irrelevant to this one and I had posted a fix.
